// Always call add_stage_profile first to create the profile
add_stage_profile(competitive, "Competitive")

// Then call add_to_stage_profile for every stage you want toggled on for this profile
add_to_stage_profile(competitive, dream_land)
add_to_stage_profile(competitive, meta_crystal)
add_to_stage_profile(competitive, duel_zone)
add_to_stage_profile(competitive, mini_yoshis_island)
add_to_stage_profile(competitive, first_destination)
add_to_stage_profile(competitive, ganons_tower)
add_to_stage_profile(competitive, kalos_pokemon_league)
add_to_stage_profile(competitive, pokemon_stadium_2)
add_to_stage_profile(competitive, taltal)
add_to_stage_profile(competitive, glacial)
add_to_stage_profile(competitive, warioware)
add_to_stage_profile(competitive, battlefield)
add_to_stage_profile(competitive, dr_mario)
add_to_stage_profile(competitive, toh)
add_to_stage_profile(competitive, fod)
add_to_stage_profile(competitive, spiralm)
add_to_stage_profile(competitive, mute)
add_to_stage_profile(competitive, delfino)
add_to_stage_profile(competitive, kitchen)
add_to_stage_profile(competitive, zlanding)
add_to_stage_profile(competitive, smashville2)
add_to_stage_profile(competitive, yoshi_story_2)
add_to_stage_profile(competitive, gerudo)
add_to_stage_profile(competitive, goomba_road)
add_to_stage_profile(competitive, bowsers_keep)
add_to_stage_profile(competitive, data)
add_to_stage_profile(competitive, clancer)
add_to_stage_profile(competitive, saffron_dl)
add_to_stage_profile(competitive, data)
add_to_stage_profile(competitive, clancer)
add_to_stage_profile(competitive, csiege)
add_to_stage_profile(competitive, yoshis_island_II)
add_to_stage_profile(competitive, ghz)
add_to_stage_profile(competitive, glacial_remix)