// Always call add_stage_profile first to create the profile
add_stage_profile(staff, "Staff Picks")

// Then call add_to_stage_profile for every stage you want toggled on for this profile
add_to_stage_profile(staff, goomba_road)
add_to_stage_profile(staff, norfair)
add_to_stage_profile(staff, great_bay)
add_to_stage_profile(staff, bowsers_keep)
add_to_stage_profile(staff, smashketball)
add_to_stage_profile(staff, deku_tree)
add_to_stage_profile(staff, glacial)
add_to_stage_profile(staff, delfino)
add_to_stage_profile(staff, smashville2)
add_to_stage_profile(staff, warioware)
add_to_stage_profile(staff, frays_stage)
add_to_stage_profile(staff, frays_stage_night)
add_to_stage_profile(staff, dream_land_sr)
add_to_stage_profile(staff, yoshis_island_II)
add_to_stage_profile(staff, madmm)
add_to_stage_profile(staff, falls)
add_to_stage_profile(staff, dr_mario)
add_to_stage_profile(staff, windy)
add_to_stage_profile(staff, japes)
add_to_stage_profile(staff, gb_land)
add_to_stage_profile(staff, world1)
add_to_stage_profile(staff, frosty)
add_to_stage_profile(staff, data)
add_to_stage_profile(staff, fod)
add_to_stage_profile(staff, blue)
add_to_stage_profile(staff, congoj_dl)
add_to_stage_profile(staff, kitchen)
add_to_stage_profile(staff, bowserb)
add_to_stage_profile(staff, clancer)
add_to_stage_profile(staff, gerudo)
add_to_stage_profile(staff, rith_essa)
add_to_stage_profile(staff, first_destination)
add_to_stage_profile(staff, ganons_tower)
add_to_stage_profile(staff, mmadness)
add_to_stage_profile(staff, casino)
add_to_stage_profile(staff, ghz)
add_to_stage_profile(staff, pirate)
add_to_stage_profile(staff, rainbowroad)
add_to_stage_profile(staff, toadsturnpike)
add_to_stage_profile(staff, draculas_castle)