// NBanjo.asm

// This file contains file inclusions, action edits, and assembly for NBanjo the Honey Bear and NKazooie the Breegull.

scope NBanjo {

    CSS:; insert "moveset/CSS.bin"

    // Modify Action Parameters             // Action                       // Animation                        // Moveset Data             // Flags
    Character.edit_action_parameters(NBANJO, Action.DeadU,                   File.BANJO_TUMBLE,                  Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ScreenKO,                File.BANJO_TUMBLE,                  Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Entry,                   File.BANJO_IDLE,                    -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, 0x006,                          File.BANJO_IDLE,                    -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Revive1,                 File.BANJO_DOWN_BNCE_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Revive2,                 File.BANJO_DOWN_STND_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ReviveWait,              File.BANJO_IDLE,                    -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Idle,                    File.BANJO_IDLE,                    -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Walk1,                   File.BANJO_WALK_1,                  -1,                         0x00000000)
    Character.edit_action_parameters(NBANJO, Action.Walk2,                   File.BANJO_WALK_2,                  -1,                         0x00000000)
    Character.edit_action_parameters(NBANJO, Action.Walk3,                   File.BANJO_WALK_3,                  -1,                         0x00000000)
    Character.edit_action_parameters(NBANJO, 0x00E,                          File.BANJO_WALK_END,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Dash,                    File.BANJO_DASH,                    Banjo.DASH,                       -1)
    Character.edit_action_parameters(NBANJO, Action.Run,                     File.BANJO_RUN,                     -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.RunBrake,                File.BANJO_RUN_BRAKE,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Turn,                    File.BANJO_TURN,                    Banjo.TURN,                       -1)
    Character.edit_action_parameters(NBANJO, Action.TurnRun,                 File.BANJO_TURN_RUN,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.JumpSquat,               File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ShieldJumpSquat,         File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.JumpF,                   File.BANJO_JUMP_F,                  Banjo.JUMP_1,                     -1)
    Character.edit_action_parameters(NBANJO, Action.JumpB,                   File.BANJO_JUMP_B,                  Banjo.JUMP_1,                     0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.JumpAerialF,             File.BANJO_JUMP_AERIAL_F,           Banjo.JUMP_2,                     0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.JumpAerialB,             File.BANJO_JUMP_AERIAL_B,           Banjo.JUMP_2,                     0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Fall,                    File.BANJO_FALL,                    -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FallAerial,              File.BANJO_FALL_AERIAL,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Crouch,                  File.BANJO_CROUCH,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CrouchIdle,              File.BANJO_CROUCH_IDLE,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CrouchEnd,               File.BANJO_CROUCH_END,              -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LandingLight,            File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LandingHeavy,            File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Pass,                    File.BANJO_PLAT_DROP,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ShieldDrop,              File.BANJO_PLAT_DROP,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Teeter,                  File.BANJO_TEETER,                  0x80000000,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.TeeterStart,             File.BANJO_TEETERSTART,             0x80000000,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.DamageHigh1,             File.BANJO_DMG_HIGH_1,              Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageHigh2,             File.BANJO_DMG_HIGH_2,              Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageHigh3,             File.BANJO_DMG_HIGH_3,              Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageMid1,              File.BANJO_DMG_MID_1,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageMid2,              File.BANJO_DMG_MID_2,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageMid3,              File.BANJO_DMG_MID_3,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageLow1,              File.BANJO_DMG_LOW_1,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageLow2,              File.BANJO_DMG_LOW_2,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageLow3,              File.BANJO_DMG_LOW_3,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageAir1,              File.BANJO_DMG_AIR_1,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageAir2,              File.BANJO_DMG_AIR_2,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageAir3,              File.BANJO_DMG_AIR_3,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageElec1,             File.BANJO_DMG_ELEC,                Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageElec2,             File.BANJO_DMG_ELEC,                Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageFlyHigh,           File.BANJO_DMG_FLY_HIGH,            Banjo.DMG_2,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageFlyMid,            File.BANJO_DMG_FLY_MID,             Banjo.DMG_2,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageFlyLow,            File.BANJO_DMG_FLY_LOW,             Banjo.DMG_2,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageFlyTop,            File.BANJO_DMG_FLY_TOP,             Banjo.DMG_2,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DamageFlyRoll,           File.BANJO_DMG_FLY_ROLL,            Banjo.DMG_2,                         -1)
    Character.edit_action_parameters(NBANJO, Action.WallBounce,              File.BANJO_TUMBLE,                  Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Tumble,                  File.BANJO_TUMBLE,                  Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FallSpecial,             File.BANJO_FALL_SPECIAL,            -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.LandingSpecial,          File.BANJO_USP_LAND,                -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Tornado,                 File.BANJO_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.EnterPipe,               File.BANJO_ENTER_PIPE,              -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ExitPipe,                File.BANJO_EXIT_PIPE,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ExitPipeWalk,            File.BANJO_EXIT_PIPE_WALK,          -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CeilingBonk,             File.BANJO_CEILING_BONK,            -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownBounceD,             File.BANJO_DOWN_BNCE_D,             Banjo.DOWN_BOUNCE,                -1)
    Character.edit_action_parameters(NBANJO, Action.DownBounceU,             File.BANJO_DOWN_BNCE_U,             Banjo.DOWN_BOUNCE,                -1)
    Character.edit_action_parameters(NBANJO, Action.DownStandD,              File.BANJO_DOWN_STND_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownStandU,              File.BANJO_DOWN_STND_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.TechF,                   File.BANJO_TECH_F,                  Banjo.TECH_ROLL,                       -1)
    Character.edit_action_parameters(NBANJO, Action.TechB,                   File.BANJO_TECH_B,                  Banjo.TECH_ROLL,                       -1)
    Character.edit_action_parameters(NBANJO, Action.DownForwardD,            File.BANJO_DOWN_FWRD_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownForwardU,            File.BANJO_DOWN_FWRD_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownBackD,               File.BANJO_DOWN_BACK_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownBackU,               File.BANJO_DOWN_BACK_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.DownAttackD,             File.BANJO_DOWN_ATK_D,              Banjo.DOWNATTACKD,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.DownAttackU,             File.BANJO_DOWN_ATK_U,              Banjo.DOWNATTACKU,                0x10000000)
    Character.edit_action_parameters(NBANJO, Action.Tech,                    File.BANJO_TECH,                    Banjo.TECH,                       -1)
    Character.edit_action_parameters(NBANJO, Action.ClangRecoil,             File.BANJO_CLANG_RECOIL,            -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffCatch,              File.BANJO_CLF_CATCH,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffWait,               File.BANJO_CLF_WAIT,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffQuick,              File.BANJO_CLF_QUICK,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffClimbQuick1,        File.BANJO_CLF_CLM_Q_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffClimbQuick2,        File.BANJO_CLF_CLM_Q_2,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffSlow,               File.BANJO_CLF_SLOW,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffClimbSlow1,         File.BANJO_CLF_CLM_S_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffClimbSlow2,         File.BANJO_CLF_CLM_S_2,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffAttackQuick1,       File.BANJO_CLF_ATK_Q_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffAttackQuick2,       File.BANJO_CLF_ATK_Q_2,             Banjo.CLIFF_ATTACK_QUICK_2,       -1)
    Character.edit_action_parameters(NBANJO, Action.CliffAttackSlow1,        File.BANJO_CLF_ATK_S_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffAttackSlow2,        File.BANJO_CLF_ATK_S_2,             Banjo.CLIFF_ATTACK_SLOW_2,        0x4FE00000)
    Character.edit_action_parameters(NBANJO, Action.CliffEscapeQuick1,       File.BANJO_CLF_ESC_Q_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffEscapeQuick2,       File.BANJO_CLF_ESC_Q_2,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffEscapeSlow1,        File.BANJO_CLF_ESC_S_1,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.CliffEscapeSlow2,        File.BANJO_CLF_ESC_S_2,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LightItemPickup,         File.BANJO_L_ITM_PICKUP,            -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HeavyItemPickup,         File.BANJO_H_ITM_PICKUP,            -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemDrop,                File.BANJO_ITM_DROP,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowDash,           File.BANJO_ITM_THROW_DASH,          -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowF,              File.BANJO_ITM_THROW_F,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowB,              File.BANJO_ITM_THROW_F,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowU,              File.BANJO_ITM_THROW_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowD,              File.BANJO_ITM_THROW_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowSmashF,         File.BANJO_ITM_THROW_F,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowSmashB,         File.BANJO_ITM_THROW_F,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowSmashU,         File.BANJO_ITM_THROW_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowSmashD,         File.BANJO_ITM_THROW_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirF,           File.BANJO_ITM_THROW_AIR_F,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirB,           File.BANJO_ITM_THROW_AIR_F,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirU,           File.BANJO_ITM_THROW_AIR_U,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirD,           File.BANJO_ITM_THROW_AIR_D,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirSmashF,      File.BANJO_ITM_THROW_AIR_F,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirSmashB,      File.BANJO_ITM_THROW_AIR_F,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirSmashU,      File.BANJO_ITM_THROW_AIR_U,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ItemThrowAirSmashD,      File.BANJO_ITM_THROW_AIR_D,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HeavyItemThrowF,         File.BANJO_HEAVY_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HeavyItemThrowB,         File.BANJO_HEAVY_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HeavyItemThrowSmashF,    File.BANJO_HEAVY_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HeavyItemThrowSmashB,    File.BANJO_HEAVY_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BeamSwordNeutral,        File.BANJO_ITM_NEUTRAL,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BeamSwordTilt,           File.BANJO_ITM_TILT,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BeamSwordSmash,          File.BANJO_ITM_SMASH,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BeamSwordDash,           File.BANJO_ITM_DASH,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BatNeutral,              File.BANJO_ITM_NEUTRAL,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BatTilt,                 File.BANJO_ITM_TILT,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BatSmash,                File.BANJO_ITM_SMASH,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.BatDash,                 File.BANJO_ITM_DASH,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FanNeutral,              File.BANJO_ITM_NEUTRAL,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FanTilt,                 File.BANJO_ITM_TILT,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FanSmash,                File.BANJO_ITM_SMASH,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FanDash,                 File.BANJO_ITM_DASH,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StarRodNeutral,          File.BANJO_ITM_NEUTRAL,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StarRodTilt,             File.BANJO_ITM_TILT,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StarRodSmash,            File.BANJO_ITM_SMASH,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StarRodDash,             File.BANJO_ITM_DASH,                -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.RayGunShoot,             File.BANJO_ITM_SHOOT,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.RayGunShootAir,          File.BANJO_ITM_SHOOT_AIR,           -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FireFlowerShoot,         File.BANJO_ITM_SHOOT,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FireFlowerShootAir,      File.BANJO_ITM_SHOOT_AIR,           -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.HammerIdle,              File.BANJO_HAMMER_IDLE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.HammerWalk,              File.BANJO_HAMMER_MOVE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.HammerTurn,              File.BANJO_HAMMER_MOVE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.HammerJumpSquat,         File.BANJO_HAMMER_MOVE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.HammerAir,               File.BANJO_HAMMER_MOVE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.HammerLanding,           File.BANJO_HAMMER_MOVE,             -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.ShieldOn,                File.BANJO_SHIELD_ON,               -1,                         0xAFE00000)
    Character.edit_action_parameters(NBANJO, Action.ShieldOff,               File.BANJO_SHIELD_OFF,              -1,                         0xAFE00000)
    Character.edit_action_parameters(NBANJO, Action.RollF,                   File.BANJO_ROLL_F,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.RollB,                   File.BANJO_ROLL_B,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ShieldBreak,             File.BANJO_DMG_FLY_TOP,             Banjo.SHIELD_BREAK,               -1)
    Character.edit_action_parameters(NBANJO, Action.ShieldBreakFall,         File.BANJO_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StunLandD,               File.BANJO_DOWN_BNCE_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StunLandU,               File.BANJO_DOWN_BNCE_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StunStartD,              File.BANJO_DOWN_STND_D,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.StunStartU,              File.BANJO_DOWN_STND_U,             -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Stun,                    File.BANJO_STUN,                    Banjo.STUN,                       0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Sleep,                   File.BANJO_STUN,                    Banjo.ASLEEP,                     0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Grab,                    File.BANJO_GRAB,                    Banjo.GRAB,                         -1)
    Character.edit_action_parameters(NBANJO, Action.GrabPull,                File.BANJO_GRAB_PULL,               -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ThrowF,                  File.BANJO_THROW_F,                 Banjo.THROW_F,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ThrowB,                  File.BANJO_THROW_B,                 Banjo.THROW_B,                    -1)
    Character.edit_action_parameters(NBANJO, Action.CapturePulled,           File.BANJO_CAPTURE_PULLED,          Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.InhalePulled,            File.BANJO_TUMBLE,                  Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.InhaleSpat,              File.BANJO_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.InhaleCopied,            File.BANJO_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.EggLayPulled,            File.BANJO_CAPTURE_PULLED,          Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.EggLay,                  File.BANJO_IDLE,                    -1,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.FalconDivePulled,        File.BANJO_DMG_HIGH_3,              Banjo.FALCON_DIVE_PULLED,                         -1)
    Character.edit_action_parameters(NBANJO, 0x0B4,                          File.BANJO_TUMBLE,                  Banjo.UNKNOWN_0B4,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ThrownDKPulled,          File.BANJO_THROWN_DKPULLED,         Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.ThrownMarioBros,         File.BANJO_THROWN_MARIO_BROS,       Banjo.DMG_1,                         -1)
    // B7
    Character.edit_action_parameters(NBANJO, Action.ThrownDK,                File.BANJO_THROWN_DK,               Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Thrown1,                 File.BANJO_THROWN_1,                Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Thrown2,                 File.BANJO_THROWN_2,                Banjo.DMG_1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Taunt,                   File.BANJO_TAUNT,                   Banjo.TAUNT,                      0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.Jab1,                    File.BANJO_JAB_1,                   Banjo.JAB1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.Jab2,                    File.BANJO_JAB_2,                   Banjo.JAB2,                         -1)
    Character.edit_action_parameters(NBANJO, Banjo.Action.Jab3,                    File.BANJO_JAB_3,                   Banjo.JAB3,                       0x40000000)
    Character.edit_action_parameters(NBANJO, Action.DashAttack,              File.BANJO_DASH_ATTACK,             -1,                         0x4FE00000)
    Character.edit_action_parameters(NBANJO, Action.FTiltHigh,               File.BANJO_FTILT_HIGH,              Banjo.F_TILT_HIGH,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.FTiltMidHigh,            0,                                  0x80000000,                 -1)
    Character.edit_action_parameters(NBANJO, Action.FTilt,                   File.BANJO_FTILT,                   Banjo.F_TILT_MID,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.FTiltMidLow,             0,                                  0x80000000,                 -1)
    Character.edit_action_parameters(NBANJO, Action.FTiltLow,                File.BANJO_FTILT_LOW,               Banjo.F_TILT_LOW,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.UTilt,                   File.BANJO_UTILT,                   Banjo.U_TILT,                     0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.DTilt,                   File.BANJO_DTILT,                   Banjo.D_TILT,                 0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.FSmashHigh,              0,                                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.FSmash,                  File.BANJO_FSMASH,                  Banjo.F_SMASH,                    0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.FSmashLow,               0,                                  -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.USmash,                  File.BANJO_USMASH,                  Banjo.U_SMASH,                         0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.DSmash,                  File.BANJO_DSMASH,                  Banjo.D_SMASH,                    0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.AttackAirN,              File.BANJO_ATTACK_AIR_N,            Banjo.ATTACK_AIR_N,               0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.AttackAirF,              File.BANJO_ATTACK_AIR_F,            Banjo.ATTACK_AIR_F,               0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.AttackAirB,              File.BANJO_ATTACK_AIR_B,            Banjo.ATTACK_AIR_B,               0x10000000)
    Character.edit_action_parameters(NBANJO, Action.AttackAirU,              File.BANJO_ATTACK_AIR_U,            Banjo.ATTACK_AIR_U,               0x0FE00000)
    Character.edit_action_parameters(NBANJO, Action.AttackAirD,              File.BANJO_ATTACK_AIR_D,            Banjo.ATTACK_AIR_D,               -1)
    Character.edit_action_parameters(NBANJO, Action.LandingAirF,             File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LandingAirD,             File.BANJO_LANDING_AIR_D,           -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LandingAirB,             File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, Action.LandingAirX,             File.BANJO_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NBANJO, 0xE0,                           File.BANJO_IDLE,                     0x80000000,                0x0FE00000)
    Character.edit_action_parameters(NBANJO, 0xE1,                           File.BANJO_IDLE,                     0x80000000,                0x0FE00000)
    Character.edit_action_parameters(NBANJO, 0xDF,                           File.BANJO_ACTION_0DF,              -1,                         -1)


    // Modify Actions             // Action             // Staling ID   // Main ASM                     // Interrupt/Other ASM          // Physics ASM              // Collision ASM
    Character.edit_action(NBANJO, 0xE0,         -1,             0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)
    Character.edit_action(NBANJO, 0xE1,         -1,             0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)
    Character.edit_action(NBANJO, Banjo.Action.Jab3,           0x3,            0x800D94C4,                     0,                              0x800D8C14,                 0x800DDF44)

    // Add Action Parameters                // Action Name      // Base Action  // Animation                    // Moveset Data             // Flags
    Character.add_new_action_params(NBANJO,  USPBegin,           -1,             File.BANJO_USP_BEGIN,           Banjo.USP_BEGIN,                  0x0FE00000)
    Character.add_new_action_params(NBANJO,  USPAttack,          -1,             File.BANJO_USP_ATTACK,          Banjo.USP_ATTACK,                 0x0FE00000)
    Character.add_new_action_params(NBANJO,  USPAttackEnd,       -1,             File.BANJO_USP_ATTACK_END,      Banjo.USP_ATTACK_END,             0x0FE00000)
    Character.add_new_action_params(NBANJO,  USPRecoil,          -1,             File.BANJO_USP_RECOIL,          Banjo.USP_RECOIL,                 0x0FE00000)
    Character.add_new_action_params(NBANJO,  USPWallSplat,       -1,             File.BANJO_USP_WALL_SPLAT,      Banjo.USP_SPLAT,                  0x0FE00000)


    // Add Actions                   // Action Name     // Base Action  //Parameters                // Staling ID   // Main ASM                 // Interrupt/Other ASM      // Movement/Physics ASM     // Collision ASM
    Character.add_new_action(NBANJO,  USPBegin,          -1,             ActionParams.USPBegin,      0x11,           BanjoUSP.begin_main_,       0,                          BanjoUSP.begin_physics_,    BanjoUSP.begin_collision_)
    Character.add_new_action(NBANJO,  USPAttack,         -1,             ActionParams.USPAttack,     0x11,           BanjoUSP.attack_main_,      BanjoUSP.attack_interupt_,  BanjoUSP.attack_physics_,   BanjoUSP.attack_collision_)
    Character.add_new_action(NBANJO,  USPAttackEnd,      -1,             ActionParams.USPAttackEnd,  0x11,           BanjoUSP.attack_end_main_,  0,                          0x800D91EC,                 BanjoUSP.collision_)
    Character.add_new_action(NBANJO,  USPRecoil,         -1,             ActionParams.USPRecoil,     0x11,           0x800D94E8,                 BanjoUSP.recoil_move_,      BanjoUSP.recoil_physics_,   0x800DE99C)
    Character.add_new_action(NBANJO,  USPWallSplat,      -1,             ActionParams.USPWallSplat,  0x11,           BanjoUSP.wall_splat_main_,  0,                          BanjoUSP.splat_physics_,    BanjoUSP.collision_)

    // Modify Menu Action Parameters              // Action     // Animation                // Moveset Data             // Flags
    Character.edit_menu_action_parameters(NBANJO, 0x0,           File.BANJO_IDLE,            -1,                         0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x1,           File.BANJO_VICTORY_1,       CSS,                        0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x2,           File.BANJO_VICTORY_2,       Banjo.VICTORY2,             0x1FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x3,           File.BANJO_VICTORY_3,       Banjo.VICTORY3,             0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x4,           File.BANJO_VICTORY_1,       CSS,                        0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x5,           File.BANJO_CLAP,            Banjo.CLAP,                 0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0x9,           File.BANJO_CONTINUE_FALL,   Banjo.CONTINUE,             0x4FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0xA,           File.BANJO_CONTINUE_UP,     -1,                         -1)
    Character.edit_menu_action_parameters(NBANJO, 0xD,           File.BANJO_1P_POSE,         -1,                         0x0FE00000)
    Character.edit_menu_action_parameters(NBANJO, 0xE,           File.BANJO_1P_CPU_POSE,     Banjo.CPU_POSE,             0x1FE00000)

    Character.table_patch_start(air_nsp, Character.id.NBANJO, 0x4)
    dw      BanjoNSP.air_begin_initial_
    OS.patch_end()
    Character.table_patch_start(ground_nsp, Character.id.NBANJO, 0x4)
    dw      BanjoNSP.ground_begin_initial_
    OS.patch_end()
    Character.table_patch_start(air_usp, Character.id.NBANJO, 0x4)
    dw      BanjoUSP.initial_
    OS.patch_end()
    Character.table_patch_start(ground_usp, Character.id.NBANJO, 0x4)
    dw      BanjoUSP.initial_
    OS.patch_end()
    Character.table_patch_start(air_dsp, Character.id.NBANJO, 0x4)
    dw      BanjoDSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_dsp, Character.id.NBANJO, 0x4)
    dw      BanjoDSP.ground_initial_
    OS.patch_end()

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NBANJO, 0x4)
    float32 0.72
    OS.patch_end()

    // Set Magnifying Glass Scale Override
    Character.table_patch_start(magnifying_glass_zoom, Character.id.NBANJO, 0x2)
    dh  0x0053
    OS.patch_end()

    // Add Jab 3
    Character.table_patch_start(jab_3_timer, Character.id.NBANJO, 0x4)
    dw 0x8014EB54                           // jab 3 timer routine copied from Mario
    OS.patch_end()
    Character.table_patch_start(jab_3_action, Character.id.NBANJO, 0x4)
    dw Banjo.set_jab_3_action_                    // subroutine which sets action id
    OS.patch_end()
    Character.table_patch_start(jab_3, Character.id.NBANJO, 0x4)
    dw Character.jab_3.ENABLED              // jab 3 = ENABLED
    OS.patch_end()
    Character.table_patch_start(rapid_jab, Character.id.NBANJO, 0x4)
    dw Character.rapid_jab.DISABLED         // disable rapid jab
    OS.patch_end()

    // Remove grounded script.
    Character.table_patch_start(grounded_script, Character.id.NBANJO, 0x4)
    dw Character.grounded_script.DISABLED   // skips grounded script
    OS.patch_end()

    // Set action strings
    Character.table_patch_start(action_string, Character.id.NBANJO, 0x4)
    dw  Banjo.Action.action_string_table
    OS.patch_end()

    // Set Kirby star damage
    Character.table_patch_start(kirby_inhale_struct, 0x8, Character.id.NBANJO, 0xC)
    dw Character.kirby_inhale_struct.star_damage.YOSHI
    OS.patch_end()

    // Set CPU behaviour
    Character.table_patch_start(ai_behaviour, Character.id.NBANJO, 0x4)
    dw      Banjo.CPU_ATTACKS
    OS.patch_end()
    

    // Handles common things for Polygons
    Character.polygon_setup(NBANJO, BANJO)


}
