// Playlist created by: Pringles
// Features new and/or revamped tracks.
// Always call add_music_profile first to create the profile
add_music_profile(freshjams, "Fresh Jams")

// Then call add_to_music_profile for every track you want toggled on for this profile
add_to_music_profile(freshjams, MAIN_MENU2)
add_to_music_profile(freshjams, WL2_PERFECT)
add_to_music_profile(freshjams, CONTROL)
add_to_music_profile(freshjams, OEDO_EDO)
add_to_music_profile(freshjams, BIS_THEGRANDFINALE)
add_to_music_profile(freshjams, MAJORA_MIDBOSS)
add_to_music_profile(freshjams, WATCH_THEME)
add_to_music_profile(freshjams, KAI_HIGHWAY)
add_to_music_profile(freshjams, SMW_ATHLETIC)
add_to_music_profile(freshjams, CRATERIA_MAIN)
add_to_music_profile(freshjams, OBSTACLE)
add_to_music_profile(freshjams, INVESTIGATION_X)
add_to_music_profile(freshjams, BANJO_MAIN)
add_to_music_profile(freshjams, EASTON_KINGDOM)
add_to_music_profile(freshjams, MADMONSTER)
add_to_music_profile(freshjams, GAME_CORNER)
add_to_music_profile(freshjams, SAMBA_DE_COMBO)
add_to_music_profile(freshjams, ZEBES_LANDING)
add_to_music_profile(freshjams, POLLYANNA)
add_to_music_profile(freshjams, FINALTEMPLE)
add_to_music_profile(freshjams, POKEMON_STADIUM)
add_to_music_profile(freshjams, RBY_GYMLEADER)
add_to_music_profile(freshjams, SNES_RAINBOW)
add_to_music_profile(freshjams, BRAWL_OOT)
add_to_music_profile(freshjams, BOSS_E)
add_to_music_profile(freshjams, POKEFLOATS)
add_to_music_profile(freshjams, MARINE_FORTRESS)
add_to_music_profile(freshjams, TWILIGHT_CITY)
add_to_music_profile(freshjams, SOUTHERNISLAND)
add_to_music_profile(freshjams, QUEST64_BATTLE)
add_to_music_profile(freshjams, MUSICAL_CASTLE)
add_to_music_profile(freshjams, DECISIVE)
add_to_music_profile(freshjams, BATTLEFIELD)
add_to_music_profile(freshjams, BOB)
add_to_music_profile(freshjams, SMB3OVERWORLD)
add_to_music_profile(freshjams, AREA6)
