// Playlist created by: Fray
// Mostly comprised of dramatic, intense, or exciting music.
// Always call add_music_profile first to create the profile
add_music_profile(battle, "Into Battle")

// Then call add_to_music_profile for every track you want toggled on for this profile
add_to_music_profile(battle, DREAM_LAND)
add_to_music_profile(battle, DUEL_ZONE)
add_to_music_profile(battle, FINAL_DESTINATION)
add_to_music_profile(battle, META_CRYSTAL)
add_to_music_profile(battle, GANONDORF_BATTLE)
add_to_music_profile(battle, CORNERIA)
add_to_music_profile(battle, KALOS)
add_to_music_profile(battle, FIRST_DESTINATION)
add_to_music_profile(battle, TOWEROFHEAVEN)
add_to_music_profile(battle, FOD)
add_to_music_profile(battle, MEMENTOS)
add_to_music_profile(battle, MUTE_CITY)
add_to_music_profile(battle, BOWSERBOSS)
add_to_music_profile(battle, POKEMON_STADIUM)
add_to_music_profile(battle, BOWSERROAD)
add_to_music_profile(battle, BOWSERFINAL)
add_to_music_profile(battle, BIG_BLUE)
add_to_music_profile(battle, ZEBES_LANDING)
add_to_music_profile(battle, METAL_CAP)
add_to_music_profile(battle, PIKA_CUP)
add_to_music_profile(battle, GLACIAL)
add_to_music_profile(battle, MACHRIDER)
add_to_music_profile(battle, ELITE_FOUR)
add_to_music_profile(battle, STAR_WOLF)
add_to_music_profile(battle, POKEMON_CHAMPION)
add_to_music_profile(battle, UNFOUNDED_REVENGE)
add_to_music_profile(battle, BLOOMING_VILLAIN)
add_to_music_profile(battle, KENGJR)
add_to_music_profile(battle, CLOCKTOWER)
add_to_music_profile(battle, EVEN_DRIER_GUYS)
add_to_music_profile(battle, FIRE_FIELD)
add_to_music_profile(battle, MULTIMAN)
add_to_music_profile(battle, GANGPLANK)
add_to_music_profile(battle, ARIA_OF_THE_SOUL)
add_to_music_profile(battle, PAPER_MARIO_BATTLE)
add_to_music_profile(battle, KING_OF_THE_KOOPAS)
add_to_music_profile(battle, MRPATCH)
add_to_music_profile(battle, KROOLS_ACID_PUNK)
add_to_music_profile(battle, FIGHT_AGAINST_BOWSER)
add_to_music_profile(battle, DKR_BOSS)
add_to_music_profile(battle, TARGET_TEST)
add_to_music_profile(battle, SURPRISE_ATTACK)
add_to_music_profile(battle, BK_FINALBATTLE)
add_to_music_profile(battle, OLE)
add_to_music_profile(battle, STARFOX_MEDLEY)
add_to_music_profile(battle, DATADYNE)
add_to_music_profile(battle, CRADLE)
add_to_music_profile(battle, TROUBLE_MAKER)
add_to_music_profile(battle, SLOPRANO)
add_to_music_profile(battle, GB_MEDLEY)
add_to_music_profile(battle, FE_MEDLEY)
add_to_music_profile(battle, VS_MARX)
add_to_music_profile(battle, SS_AQUA)
add_to_music_profile(battle, METAL_BATTLE)
add_to_music_profile(battle, MULTIMAN2)
add_to_music_profile(battle, FIRE_EMBLEM)
add_to_music_profile(battle, KANTO_WILD_BATTLE)