// Playlist created by: Fray
// Mostly comprised of upbeat, energetic, or happy music.
// Always call add_music_profile first to create the profile
add_music_profile(happy, "Positive Vibes")

// Then call add_to_music_profile for every track you want toggled on for this profile
add_to_music_profile(happy, CREDITS)
add_to_music_profile(happy, PEACHS_CASTLE)
add_to_music_profile(happy, YOSHIS_ISLAND)
add_to_music_profile(happy, COOLCOOLMOUNTAIN)
add_to_music_profile(happy, GREATBAY)
add_to_music_profile(happy, SMASHVILLE)
add_to_music_profile(happy, MUDA)
add_to_music_profile(happy, SPIRAL_MOUNTAIN)
add_to_music_profile(happy, DREAMLANDBETA)
add_to_music_profile(happy, CASTLEWALL)
add_to_music_profile(happy, DELFINO)
add_to_music_profile(happy, ONETT)
add_to_music_profile(happy, FROSTY_VILLAGE)
add_to_music_profile(happy, WING_CAP)
add_to_music_profile(happy, POP_STAR)
add_to_music_profile(happy, ALL_I_NEEDED_WAS_YOU)
add_to_music_profile(happy, POLLYANNA)
add_to_music_profile(happy, SNAKEY_CHANTEY)
add_to_music_profile(happy, TAZMILY)
add_to_music_profile(happy, YOSHI_GOLF)
add_to_music_profile(happy, OBSTACLE)
add_to_music_profile(happy, CLICKCLOCKWOODS)
add_to_music_profile(happy, CRESCENT_ISLAND)
add_to_music_profile(happy, OLE)
add_to_music_profile(happy, WINDY)
add_to_music_profile(happy, TROUBLE_MAKER)
add_to_music_profile(happy, ESPERANCE)
add_to_music_profile(happy, NSMB)
add_to_music_profile(happy, YOSHI_TALE)
add_to_music_profile(happy, FLOWER_GARDEN)
add_to_music_profile(happy, WILDLANDS)
add_to_music_profile(happy, SS_AQUA)
add_to_music_profile(happy, SLIDER)