// Playlist created by: The_Smashfather
// Features Smash Remix Staff Favorites.
// Always call add_music_profile first to create the profile
add_music_profile(staff, "Staff Picks")

// Then call add_to_music_profile for every track you want toggled on for this profile
add_to_music_profile(staff, WINDY)
add_to_music_profile(staff, CRESCENT_ISLAND)
add_to_music_profile(staff, STARRING_WARIO)
add_to_music_profile(staff, CLOCKTOWER)
add_to_music_profile(staff, ARIA_OF_THE_SOUL)
add_to_music_profile(staff, SURPRISE_ATTACK)
add_to_music_profile(staff, YOSHI_GOLF)
add_to_music_profile(staff, TOADS_TURNPIKE)
add_to_music_profile(staff, ZEBES_LANDING)
add_to_music_profile(staff, FIGHT_AGAINST_BOWSER)
add_to_music_profile(staff, EVEN_DRIER_GUYS)
add_to_music_profile(staff, BOWSERBOSS)
add_to_music_profile(staff, NBA_JAM)
add_to_music_profile(staff, CASTLEWALL)
add_to_music_profile(staff, KENGJR)
add_to_music_profile(staff, FROSTY_VILLAGE)
add_to_music_profile(staff, BIG_BLUE)
add_to_music_profile(staff, GB_MEDLEY)
add_to_music_profile(staff, SLIDER)
add_to_music_profile(staff, MULTIMAN)
add_to_music_profile(staff, YOSHI_TALE)
add_to_music_profile(staff, PEACH_CASTLE)
add_to_music_profile(staff, FLAT_ZONE)
add_to_music_profile(staff, FLAT_ZONE_2)
add_to_music_profile(staff, KROOLS_ACID_PUNK)
add_to_music_profile(staff, SLOPRANO)
add_to_music_profile(staff, GLACIAL)
add_to_music_profile(staff, GANGPLANK)
add_to_music_profile(staff, FOD)
add_to_music_profile(staff, ASTRAL_OBSERVATORY)
add_to_music_profile(staff, STAR_WOLF)
add_to_music_profile(staff, FE_MEDLEY)
add_to_music_profile(staff, ANIMAL_CROSSING)
add_to_music_profile(staff, DKR_BOSS)
add_to_music_profile(staff, MACHRIDER)
add_to_music_profile(staff, CRADLE)
add_to_music_profile(staff, BABY_BOWSER)
add_to_music_profile(staff, GREEN_HILL_ZONE)
add_to_music_profile(staff, LIVE_AND_LEARN)
add_to_music_profile(staff, SONICCD_SPECIAL)
add_to_music_profile(staff, FLYINGBATTERY)
add_to_music_profile(staff, SMB2OVERWORLD)
add_to_music_profile(staff, RAINBOWROAD)
add_to_music_profile(staff, LINKS_AWAKENING_MEDLEY)
add_to_music_profile(staff, DRACULAS_CASTLE)
add_to_music_profile(staff, IRON_BLUE_INTENTION)
add_to_music_profile(staff, BLOODY_TEARS)
add_to_music_profile(staff, FD_BRAWL)
add_to_music_profile(staff, GERUDO_VALLEY)
add_to_music_profile(staff, MK_REVENGE)


