// NMarina.asm

// This file contains file inclusions, action edits, and assembly for the Ultra-InterPolygon-Fighter N Marina Pointy-Ears.

scope NMarina {

    // Insert Moveset files
	OS.align(16)

    insert JUMP_2,"moveset/JUMP_2.bin"
	insert DASH,"moveset/DASH.bin"
	insert DASH_ATTACK,"moveset/DASH_ATTACK.bin"
	insert ROLL_F,"moveset/ROLL_F.bin"
	insert ROLL_B,"moveset/ROLL_B.bin"
	insert DOWN_ROLL,"moveset/DOWN_ROLL.bin"
    insert SHIELDBREAK,"moveset/SHIELDBREAK.bin"
    insert STUNLOOP,"moveset/STUNLOOP.bin"; Moveset.GO_TO(STUNLOOP)  //loops
    insert SLEEP,"moveset/SLEEP.bin"; Moveset.GO_TO(SLEEP)  //loops
    insert TAUNT,"moveset/TAUNT.bin"
	NO_COMMAND:
	dw 0


    // @ Description
    // Marina's extra actions
    scope Action {
        constant JabLoopStart(0x0DC)
        constant JabLoop(0x0DD)
        constant JabLoopEnd(0x0DE)
        constant Appear1(0x0DF)
        constant Appear2(0x0E0)
        constant NSPGround(0x0E1)
        constant NSPGroundPull(0x0E2)
        constant NSPGroundThrow(0x0E3)
        constant NSPGroundThrowU(0x0E4)
        constant NSPGroundThrowD(0x0E5)
        constant NSPAir(0x0E6)
        constant NSPAirPull(0x0E7)
        constant NSPAirThrow(0x0E8)
        constant NSPAirThrowU(0x0E9)
        constant NSPAirThrowD(0x0EA)
        constant Cargo(0x0EB)
        constant CargoWalk1(0x0EC)
        constant CargoWalk2(0x0ED)
        constant CargoWalk3(0x0EE)
        //constant CargoTurn(0x0EF)
        // constant CargoJumpSquat(0x0F0)
        // constant CargoAir(0x0F1)
        // constant CargoLanding(0x0F2)
        // constant CargoDamage(0x0F3)
        // constant CargoThrow(0x0F4)
        // constant CargoThrowAir(0x0F5)
        // constant CargoItemThrowF(0x0F6)
        // constant CargoItemThrowB(0x0F7)
        // constant CargoItemThrowSF(0x0F8)
        // constant CargoItemThrowSB(0x0F9)
	}

    // Modify Action Parameters              // Action                      // Animation                        // Moveset Data             // Flags
    Character.edit_action_parameters(NMARINA, Action.DeadU,                  File.MARINA_TUMBLE,                 Marina.DMG_1,                      -1)
    Character.edit_action_parameters(NMARINA, Action.ScreenKO,               File.MARINA_TUMBLE,                 Marina.DMG_1,                      -1)
    Character.edit_action_parameters(NMARINA, Action.Entry,                  File.MARINA_IDLE,                   Marina.IDLE,                       -1)
    Character.edit_action_parameters(NMARINA, 0x006,                         File.MARINA_IDLE,                   Marina.IDLE,                       -1)
    Character.edit_action_parameters(NMARINA, Action.Revive1,                File.MARINA_DOWN_BNCE_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Revive2,                File.MARINA_DOWN_STND_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ReviveWait,             File.MARINA_IDLE,                   Marina.IDLE,                       -1)
    Character.edit_action_parameters(NMARINA, Action.Idle,                   File.MARINA_IDLE,                   Marina.IDLE,                       -1)
    Character.edit_action_parameters(NMARINA, Action.Walk1,                  File.MARINA_WALK_1,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Walk2,                  File.MARINA_WALK_2,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Walk3,                  File.MARINA_WALK_3,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, 0x00E,                         File.MARINA_WALK_END,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Dash,                   File.MARINA_DASH,                   DASH,                       0x10000000)
    Character.edit_action_parameters(NMARINA, Action.Run,                    File.MARINA_RUN,                    Marina.RUN,                 -1)
    Character.edit_action_parameters(NMARINA, Action.RunBrake,               File.MARINA_RUN_BRAKE,              Marina.RUN_BRAKE,           -1)
    Character.edit_action_parameters(NMARINA, Action.Turn,                   File.MARINA_TURN,                   Marina.TURN,                       -1)
    Character.edit_action_parameters(NMARINA, Action.TurnRun,                File.MARINA_TURN_RUN,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.JumpSquat,              File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldJumpSquat,        File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.JumpF,                  File.MARINA_JUMP_F,                 Marina.JUMP_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.JumpB,                  File.MARINA_JUMP_B,                 Marina.JUMP_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.JumpAerialF,            File.MARINA_JUMP_AERIAL_F,          JUMP_2,                     0x10000000)
    Character.edit_action_parameters(NMARINA, Action.JumpAerialB,            File.MARINA_JUMP_AERIAL_B,          JUMP_2,                     0x10000000)
    Character.edit_action_parameters(NMARINA, Action.Fall,                   File.MARINA_FALL,                   -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FallAerial,             File.MARINA_FALL_AERIAL,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Crouch,                 File.MARINA_CROUCH,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CrouchIdle,             File.MARINA_CROUCH_IDLE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CrouchEnd,              File.MARINA_CROUCH_END,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LandingLight,           File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LandingHeavy,           File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Pass,                   File.MARINA_PLAT_DROP,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldDrop,             File.MARINA_PLAT_DROP,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Teeter,                 File.MARINA_TEETER,                 0x80000000,                 -1)
    Character.edit_action_parameters(NMARINA, Action.TeeterStart,            File.MARINA_TEETERSTART,            0x80000000,                 -1)
    Character.edit_action_parameters(NMARINA, Action.DamageHigh1,            File.MARINA_DMG_HIGH_1,             Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageHigh2,            File.MARINA_DMG_HIGH_2,             Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageHigh3,            File.MARINA_DMG_HIGH_3,             Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageMid1,             File.MARINA_DMG_MID_1,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageMid2,             File.MARINA_DMG_MID_2,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageMid3,             File.MARINA_DMG_MID_3,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageLow1,             File.MARINA_DMG_LOW_1,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageLow2,             File.MARINA_DMG_LOW_2,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageLow3,             File.MARINA_DMG_LOW_3,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageAir1,             File.MARINA_DMG_AIR_1,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageAir2,             File.MARINA_DMG_AIR_2,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageAir3,             File.MARINA_DMG_AIR_3,              Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageElec1,            File.MARINA_DMG_ELEC,               Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageElec2,            File.MARINA_DMG_ELEC,               Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageFlyHigh,          File.MARINA_DMG_FLY_HIGH,           Marina.DMG_2,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageFlyMid,           File.MARINA_DMG_FLY_MID,            Marina.DMG_2,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageFlyLow,           File.MARINA_DMG_FLY_LOW,            Marina.DMG_2,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageFlyTop,           File.MARINA_DMG_FLY_TOP,            Marina.DMG_2,               -1)
    Character.edit_action_parameters(NMARINA, Action.DamageFlyRoll,          File.MARINA_DMG_FLY_ROLL,           Marina.DMG_2,               -1)
    Character.edit_action_parameters(NMARINA, Action.WallBounce,             File.MARINA_TUMBLE,                 Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.Tumble,                 File.MARINA_TUMBLE,                 Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.FallSpecial,            File.MARINA_FALL_SPECIAL,           -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LandingSpecial,         File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Tornado,                File.MARINA_TUMBLE,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.EnterPipe,              File.MARINA_ENTER_PIPE,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ExitPipe,               File.MARINA_EXIT_PIPE,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ExitPipeWalk,           File.MARINA_EXIT_PIPE_WALK,         -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CeilingBonk,            File.MARINA_CEILING_BONK,           -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.DownBounceD,            File.MARINA_DOWN_BNCE_D,            Marina.DOWN_BOUNCE,         -1)
    Character.edit_action_parameters(NMARINA, Action.DownBounceU,            File.MARINA_DOWN_BNCE_U,            Marina.DOWN_BOUNCE,         -1)
    Character.edit_action_parameters(NMARINA, Action.DownStandD,             File.MARINA_DOWN_STND_D,            Marina.DOWN_STAND,          -1)
    Character.edit_action_parameters(NMARINA, Action.DownStandU,             File.MARINA_DOWN_STND_U,            Marina.DOWN_STAND,          -1)
    Character.edit_action_parameters(NMARINA, Action.TechF,                  File.MARINA_TECH_F,                 Marina.TECH_ROLL,           -1)
    Character.edit_action_parameters(NMARINA, Action.TechB,                  File.MARINA_TECH_B,                 Marina.TECH_ROLL,           -1)
    Character.edit_action_parameters(NMARINA, Action.DownForwardD,           File.MARINA_DOWN_FWRD_D,            Marina.DOWN_ROLL,           0x50000000)
    Character.edit_action_parameters(NMARINA, Action.DownForwardU,           File.MARINA_DOWN_FWRD_U,            Marina.DOWN_ROLL,           0x50000000)
    Character.edit_action_parameters(NMARINA, Action.DownBackD,              File.MARINA_DOWN_BACK_D,            Marina.DOWN_ROLL,           0x50000000)
    Character.edit_action_parameters(NMARINA, Action.DownBackU,              File.MARINA_DOWN_BACK_U,            Marina.DOWN_ROLL,           0x50000000)
    Character.edit_action_parameters(NMARINA, Action.DownAttackD,            File.MARINA_DOWN_ATK_D,             Marina.DOWN_ATTACK_D,       -1)
    Character.edit_action_parameters(NMARINA, Action.DownAttackU,            File.MARINA_DOWN_ATK_U,             Marina.DOWN_ATTACK_U,       -1)
    Character.edit_action_parameters(NMARINA, Action.Tech,                   File.MARINA_TECH,                   Marina.TECH,                -1)
    Character.edit_action_parameters(NMARINA, Action.ClangRecoil,            File.MARINA_CLANG_RECOIL,           -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffCatch,             File.MARINA_CLF_CATCH,              Marina.CLIFF_CATCH,         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffWait,              File.MARINA_CLF_WAIT,               Marina.CLIFF_WAIT,          -1)
    Character.edit_action_parameters(NMARINA, Action.CliffQuick,             File.MARINA_CLF_QUICK,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffClimbQuick1,       File.MARINA_CLF_CLM_Q_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffClimbQuick2,       File.MARINA_CLF_CLM_Q_2,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffSlow,              File.MARINA_CLF_SLOW,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffClimbSlow1,        File.MARINA_CLF_CLM_S_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffClimbSlow2,        File.MARINA_CLF_CLM_S_2,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffAttackQuick1,      File.MARINA_CLF_ATK_Q_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffAttackQuick2,      File.MARINA_CLF_ATK_Q_2,            Marina.CLIFF_ATK_QUICK_2,          -1)
    Character.edit_action_parameters(NMARINA, Action.CliffAttackSlow1,       File.MARINA_CLF_ATK_S_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffAttackSlow2,       File.MARINA_CLF_ATK_S_2,            Marina.CLIFF_ATK_SLOW_2,           -1)
    Character.edit_action_parameters(NMARINA, Action.CliffEscapeQuick1,      File.MARINA_CLF_ESC_Q_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffEscapeQuick2,      File.MARINA_CLF_ESC_Q_2,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffEscapeSlow1,       File.MARINA_CLF_ESC_S_1,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.CliffEscapeSlow2,       File.MARINA_CLF_ESC_S_2,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LightItemPickup,        File.MARINA_L_ITM_PICKUP,           -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HeavyItemPickup,        File.MARINA_NSPG_PULL,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemDrop,               File.MARINA_ITM_DROP,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowDash,          File.MARINA_ITM_THROW_DASH,         -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowF,             File.MARINA_ITM_THROW_F,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowB,             File.MARINA_ITM_THROW_F,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowU,             File.MARINA_ITM_THROW_U,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowD,             File.MARINA_ITM_THROW_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowSmashF,        File.MARINA_ITM_THROW_F,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowSmashB,        File.MARINA_ITM_THROW_F,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowSmashU,        File.MARINA_ITM_THROW_U,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowSmashD,        File.MARINA_ITM_THROW_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirF,          File.MARINA_ITM_THROW_AIR_F,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirB,          File.MARINA_ITM_THROW_AIR_F,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirU,          File.MARINA_ITM_THROW_AIR_U,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirD,          File.MARINA_ITM_THROW_AIR_D,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirSmashF,     File.MARINA_ITM_THROW_AIR_F,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirSmashB,     File.MARINA_ITM_THROW_AIR_F,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirSmashU,     File.MARINA_ITM_THROW_AIR_U,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ItemThrowAirSmashD,     File.MARINA_ITM_THROW_AIR_D,        -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HeavyItemThrowF,        File.MARINA_CARGO_THROW,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HeavyItemThrowB,        File.MARINA_CARGO_THROW,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HeavyItemThrowSmashF,   File.MARINA_CARGO_THROW,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HeavyItemThrowSmashB,   File.MARINA_CARGO_THROW,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BeamSwordNeutral,       File.MARINA_ITM_NEUTRAL,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BeamSwordTilt,          File.MARINA_ITM_TILT,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BeamSwordSmash,         File.MARINA_ITM_SMASH,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BeamSwordDash,          File.MARINA_ITM_DASH,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BatNeutral,             File.MARINA_ITM_NEUTRAL,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BatTilt,                File.MARINA_ITM_TILT,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BatSmash,               File.MARINA_ITM_SMASH,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.BatDash,                File.MARINA_ITM_DASH,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FanNeutral,             File.MARINA_ITM_NEUTRAL,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FanTilt,                File.MARINA_ITM_TILT,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FanSmash,               File.MARINA_ITM_SMASH,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FanDash,                File.MARINA_ITM_DASH,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StarRodNeutral,         File.MARINA_ITM_NEUTRAL,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StarRodTilt,            File.MARINA_ITM_TILT,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StarRodSmash,           File.MARINA_ITM_SMASH,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StarRodDash,            File.MARINA_ITM_DASH,               -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.RayGunShoot,            File.MARINA_ITM_SHOOT,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.RayGunShootAir,         File.MARINA_ITM_SHOOT_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FireFlowerShoot,        File.MARINA_ITM_SHOOT,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FireFlowerShootAir,     File.MARINA_ITM_SHOOT_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerIdle,             File.MARINA_HAMMER_IDLE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerWalk,             File.MARINA_HAMMER_MOVE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerTurn,             File.MARINA_HAMMER_MOVE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerJumpSquat,        File.MARINA_HAMMER_MOVE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerAir,              File.MARINA_HAMMER_MOVE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.HammerLanding,          File.MARINA_HAMMER_MOVE,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldOn,               File.MARINA_SHIELD_ON,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldOff,              File.MARINA_SHIELD_OFF,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.RollF,                  File.MARINA_ROLL_F,                 ROLL_F,                     -1)
    Character.edit_action_parameters(NMARINA, Action.RollB,                  File.MARINA_ROLL_B,                 ROLL_B,                     -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldBreak,            File.MARINA_DMG_FLY_TOP,            SHIELDBREAK,                -1)
    Character.edit_action_parameters(NMARINA, Action.ShieldBreakFall,        File.MARINA_TUMBLE,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StunLandD,              File.MARINA_DOWN_BNCE_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StunLandU,              File.MARINA_DOWN_BNCE_U,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StunStartD,             File.MARINA_DOWN_STND_D,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.StunStartU,             File.MARINA_DOWN_STND_U,            -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.Stun,                   File.MARINA_STUN,                   STUNLOOP,                   -1)
    Character.edit_action_parameters(NMARINA, Action.Sleep,                  File.MARINA_STUN,                   SLEEP,                      -1)
    Character.edit_action_parameters(NMARINA, Action.Grab,                   File.MARINA_GRAB,                   Marina.GRAB,                -1)
    Character.edit_action_parameters(NMARINA, Action.GrabPull,               File.MARINA_GRAB_PULL,              -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.ThrowF,                 File.MARINA_THROW_F,                Marina.THROW_F,             -1)
    Character.edit_action_parameters(NMARINA, Action.ThrowB,                 File.MARINA_THROW_B,                Marina.THROW_B,             0x50000000)
    Character.edit_action_parameters(NMARINA, Action.CapturePulled,          File.MARINA_CAPTURE_PULLED,         Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.InhalePulled,           File.MARINA_TUMBLE,                 Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.InhaleSpat,             File.MARINA_TUMBLE,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.InhaleCopied,           File.MARINA_TUMBLE,                 -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.EggLayPulled,           File.MARINA_CAPTURE_PULLED,         Marina.DMG_1,               -1)
    Character.edit_action_parameters(NMARINA, Action.EggLay,                 File.MARINA_IDLE,                   -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.FalconDivePulled,       File.MARINA_DMG_HIGH_3,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, 0x0B4,                         File.MARINA_TUMBLE,                 Marina.UNKNOWN_0B4,        -1)
    Character.edit_action_parameters(NMARINA, Action.ThrownDKPulled,         File.MARINA_THROWN_DKPULLED,        Marina.DMG_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.ThrownMarioBros,        File.MARINA_THROWN_MARIO_BROS,      Marina.DMG_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.ThrownDK,               File.MARINA_THROWN_DK,              Marina.DMG_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.Thrown1,                File.MARINA_THROWN_1,               Marina.DMG_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.Thrown2,                File.MARINA_THROWN_2,               Marina.DMG_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.Taunt,                  File.MARINA_TAUNT,                  TAUNT,                     -1)
    Character.edit_action_parameters(NMARINA, Action.Jab1,                   File.MARINA_JAB_1,                  Marina.JAB_1,              -1)
    Character.edit_action_parameters(NMARINA, Action.Jab2,                   File.MARINA_JAB_2,                  Marina.JAB_2,              -1)
    Character.edit_action_parameters(NMARINA, Action.DashAttack,             File.MARINA_DASH_ATTACK,            DASH_ATTACK,               -1)
    Character.edit_action_parameters(NMARINA, Action.FTiltHigh,              File.MARINA_FTILT_HIGH,             Marina.F_TILT_HIGH,        -1)
    Character.edit_action_parameters(NMARINA, Action.FTiltMidHigh,           0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARINA, Action.FTilt,                  File.MARINA_FTILT,                  Marina.F_TILT,                     1)
    Character.edit_action_parameters(NMARINA, Action.FTiltMidLow,            0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARINA, Action.FTiltLow,               File.MARINA_FTILT_LOW,              Marina.F_TILT_LOW,                 -1)
    Character.edit_action_parameters(NMARINA, Action.UTilt,                  File.MARINA_UTILT,                  Marina.U_TILT,                     -1)
    Character.edit_action_parameters(NMARINA, Action.DTilt,                  File.MARINA_DTILT,                  Marina.D_TILT,                     -1)
    Character.edit_action_parameters(NMARINA, Action.FSmashHigh,             0,                                  0x80000000,                 -1)
    Character.edit_action_parameters(NMARINA, Action.FSmash,                 File.MARINA_FSMASH,                 Marina.F_SMASH,                    -1)
    Character.edit_action_parameters(NMARINA, Action.FSmashLow,              0,                                  0x80000000,                 -1)
    Character.edit_action_parameters(NMARINA, Action.USmash,                 File.MARINA_USMASH,                 Marina.U_SMASH,                    0)
    Character.edit_action_parameters(NMARINA, Action.DSmash,                 File.MARINA_DSMASH,                 Marina.D_SMASH,                    -1)
    Character.edit_action_parameters(NMARINA, Action.AttackAirN,             File.MARINA_ATTACK_AIR_N,           Marina.ATTACK_AIR_N,               -1)
    Character.edit_action_parameters(NMARINA, Action.AttackAirF,             File.MARINA_ATTACK_AIR_F,           Marina.ATTACK_AIR_F,               -1)
    Character.edit_action_parameters(NMARINA, Action.AttackAirB,             File.MARINA_ATTACK_AIR_B,           Marina.ATTACK_AIR_B,               -1)
    Character.edit_action_parameters(NMARINA, Action.AttackAirU,             File.MARINA_ATTACK_AIR_U,           Marina.ATTACK_AIR_U,               -1)
    Character.edit_action_parameters(NMARINA, Action.AttackAirD,             File.MARINA_ATTACK_AIR_D,           Marina.ATTACK_AIR_D,               -1)
    Character.edit_action_parameters(NMARINA, Action.LandingAirF,            File.MARINA_LANDING_AIR_F,          -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LandingAirB,            File.MARINA_LANDING_AIR_B,          -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.LandingAirX,            File.MARINA_LANDING,                -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.JabLoopStart,           File.MARINA_JAB_LOOP_START,         0x80000000,                 0)
    Character.edit_action_parameters(NMARINA, Action.JabLoop,                File.MARINA_JAB_LOOP,               Marina.JAB_LOOP,                   0)
    Character.edit_action_parameters(NMARINA, Action.JabLoopEnd,             File.MARINA_JAB_LOOP_END,           0x80000000,                 0)
    Character.edit_action_parameters(NMARINA, 0x0DF,                         File.MARINA_ACTION_0DF,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, 0x0E0,                         File.MARINA_ACTION_0E0,             -1,                         -1)
    Character.edit_action_parameters(NMARINA, Action.NSPGround,              File.MARINA_NSPG,                   Marina.NSP,                        0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPGroundPull,          File.MARINA_NSPG_PULL,              Marina.NSP_PULL,                   0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPGroundThrow,         File.MARINA_NSPG_THROW,             Marina.NSPG_THROW,                 0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPGroundThrowU,        File.MARINA_NSPG_THROW_U,           Marina.NSPG_THROWU,                0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPGroundThrowD,        File.MARINA_NSPG_THROW_D,           Marina.NSPG_THROWD,                0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPAir,                 File.MARINA_NSPA,                   Marina.NSP,                        0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPAirPull,             File.MARINA_NSPA_PULL,              Marina.NSP_PULL,                   0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPAirThrow,            File.MARINA_NSPA_THROW,             Marina.NSPA_THROW,                 0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPAirThrowU,           File.MARINA_NSPA_THROW_U,           Marina.NSPA_THROWU,                0x10000000)
    Character.edit_action_parameters(NMARINA, Action.NSPAirThrowD,           File.MARINA_NSPA_THROW_D,           Marina.NSPA_THROWD,                0x10000000)
    Character.edit_action_parameters(NMARINA, Action.Cargo,                  File.MARINA_CARGO,                  0x80000000,                 0x10000000)
    Character.edit_action_parameters(NMARINA, Action.CargoWalk1,             File.MARINA_CARGO_WALK_1,           0x80000000,                 0x10000000)
    Character.edit_action_parameters(NMARINA, Action.CargoWalk2,             File.MARINA_CARGO_WALK_2,           0x80000000,                 0x10000000)
    Character.edit_action_parameters(NMARINA, Action.CargoWalk3,             File.MARINA_CARGO_WALK_3,           0x80000000,                 0x10000000)

    // Modify Actions             // Action                 // Staling ID   // Main ASM                     // Interrupt/Other ASM          // Movement/Physics ASM         // Collision ASM
    Character.edit_action(NMARINA, Action.JabLoopStart,      0x4,            0x8014F0D0,                     0,                              0x800D8BB4,                     0x800DDF44)
    Character.edit_action(NMARINA, Action.JabLoop,           0x4,            0x8014F2A8,                     0x8014F388,                     0x800D8BB4,                     0x800DDF44)
    Character.edit_action(NMARINA, Action.JabLoopEnd,        0x4,            0x800D94C4,                     0,                              0x800D8BB4,                     0x800DDF44)
    Character.edit_action(NMARINA, Action.NSPGround,         0x12,           0x800D94C4,                     0,                              MarinaNSP.ground_physics_,      MarinaNSP.ground_collision_)
    Character.edit_action(NMARINA, Action.NSPGroundPull,     0x12,           MarinaNSP.ground_pull_main_,    0,                              0x800D8BB4,                     MarinaNSP.grab_ground_collision_)
    Character.edit_action(NMARINA, Action.NSPGroundThrow,    0x12,           0x8014A0C0,                     MarinaNSP.throw_turn_,          0x800D8BB4,                     0x80149B78)
    Character.edit_action(NMARINA, Action.NSPGroundThrowU,   0x12,           0x8014A0C0,                     0,                              0x800D8BB4,                     0x80149B78)
    Character.edit_action(NMARINA, Action.NSPGroundThrowD,   0x12,           0x8014A0C0,                     0,                              0x800D8BB4,                     0x80149B78)
    Character.edit_action(NMARINA, Action.NSPAir,            0x12,           0x800D94E8,                     0,                              MarinaNSP.air_physics_,         MarinaNSP.air_collision_)
    Character.edit_action(NMARINA, Action.NSPAirPull,        0x12,           MarinaNSP.air_pull_main_,       0,                              0x800D91EC,                     MarinaNSP.grab_air_collision_)
    Character.edit_action(NMARINA, Action.NSPAirThrow,       0x12,           0x8014A0C0,                     MarinaNSP.throw_turn_,          MarinaNSP.throw_air_physics_,   MarinaNSP.throw_air_collision_)
    Character.edit_action(NMARINA, Action.NSPAirThrowU,      0x12,           0x8014A0C0,                     0,                              MarinaNSP.throw_air_physics_,   MarinaNSP.throw_air_collision_)
    Character.edit_action(NMARINA, Action.NSPAirThrowD,      0x12,           0x8014A0C0,                     0,                              MarinaNSP.throw_air_physics_,   MarinaNSP.throw_air_collision_)
    Character.edit_action(NMARINA, Action.Cargo,             0x23,           0,                              0x8014D400,                     0x800D8BB4,                     0x8014D478)
    Character.edit_action(NMARINA, Action.CargoWalk1,        0x23,           0,                              0x8014D590,                     0x8013E548,                     0x8014D478)
    Character.edit_action(NMARINA, Action.CargoWalk2,        0x23,           0,                              0x8014D590,                     0x8013E548,                     0x8014D478)
    Character.edit_action(NMARINA, Action.CargoWalk3,        0x23,           0,                              0x8014D590,                     0x8013E548,                     0x8014D478)

    // Add Action Parameters                // Action Name      // Base Action  // Animation                    // Moveset Data             // Flags
    Character.add_new_action_params(NMARINA, CargoTurn,          -1,             File.MARINA_CARGO_TURN,         Marina.CARGO_TURN,          0x10000000)
    Character.add_new_action_params(NMARINA, CargoJumpSquat,     -1,             File.MARINA_CARGO_JUMPSQUAT,    0x80000000,                 0x10000000)
    Character.add_new_action_params(NMARINA, CargoAir,           -1,             File.MARINA_CARGO_AIR,          0x80000000,                 0x10000000)
    Character.add_new_action_params(NMARINA, CargoLanding,       -1,             File.MARINA_CARGO_JUMPSQUAT,    0x80000000,                 0x10000000)
    Character.add_new_action_params(NMARINA, CargoDamage,        -1,             File.MARINA_CARGO_AIR,          0x80000000,                 0x10000000)
    Character.add_new_action_params(NMARINA, CargoThrow,         -1,             File.MARINA_CARGO_THROW,        Marina.CARGO_THROW,         0x10000000)
    Character.add_new_action_params(NMARINA, CargoThrowAir,      -1,             File.MARINA_CARGO_THROW_AIR,    Marina.CARGO_THROW,         0x10000000)
    Character.add_new_action_params(NMARINA, CargoItemThrowF,    -1,             File.MARINA_CARGO_THROW,        0x8F8,                      0x10000000)
    Character.add_new_action_params(NMARINA, CargoItemThrowB,    -1,             File.MARINA_CARGO_THROW,        0x908,                      0x10000000)
    Character.add_new_action_params(NMARINA, CargoItemThrowSF,   -1,             File.MARINA_CARGO_THROW,        0x918,                      0x10000000)
    Character.add_new_action_params(NMARINA, CargoItemThrowSB,   -1,             File.MARINA_CARGO_THROW,        0x928,                      0x10000000)
    Character.add_new_action_params(NMARINA, CargoJump,          -1,             File.MARINA_CARGO_JUMP,         0x80000000,                 0x10000000)
    Character.add_new_action_params(NMARINA, CargoShake,         -1,             File.MARINA_CARGO_SHAKE,        Marina.CARGO_SHAKE,         0x10000000)
    Character.add_new_action_params(NMARINA, USPG,               -1,             File.MARINA_USPG,               Marina.USP,                 0x10000000)
    Character.add_new_action_params(NMARINA, USPA,               -1,             File.MARINA_USPA,               Marina.USP,                 0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Begin,         -1,             File.MARINA_DSPG_BEGIN,         Marina.DSP_BEGIN,           0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Wait,          -1,             File.MARINA_DSPG_WAIT,          Marina.DSP_WAIT,            0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Absorb,        -1,             File.MARINA_DSPG_ABSORB,        Marina.DSP_ABSORB,          0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_End,           -1,             File.MARINA_DSPG_END,           Marina.DSP_END,             0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Pull,          -1,             File.MARINA_DSPG_PULL,          Marina.DSP_PULL,            0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Pull_Fail,     -1,             File.MARINA_DSPG_PULL_FAIL,     Marina.DSP_PULL_FAIL,       0x10000000)
    Character.add_new_action_params(NMARINA, DSPG_Stow,          -1,             File.MARINA_DSPG_STOW,          Marina.DSP_STOW,            0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Begin,         -1,             File.MARINA_DSPA_BEGIN,         Marina.DSP_BEGIN,           0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Wait,          -1,             File.MARINA_DSPA_WAIT,          Marina.DSP_WAIT,            0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Absorb,        -1,             File.MARINA_DSPA_ABSORB,        Marina.DSP_ABSORB,          0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_End,           -1,             File.MARINA_DSPA_END,           Marina.DSP_END,             0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Pull,          -1,             File.MARINA_DSPA_PULL,          Marina.DSP_PULL,            0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Pull_Fail,     -1,             File.MARINA_DSPA_PULL_FAIL,     Marina.DSP_PULL_FAIL,       0x10000000)
    Character.add_new_action_params(NMARINA, DSPA_Stow,          -1,             File.MARINA_DSPA_STOW,          Marina.DSP_STOW,            0x10000000)

    // Add Actions                   // Action Name     // Base Action  //Parameters                    // Staling ID   // Main ASM                     // Interrupt/Other ASM          // Movement/Physics ASM             // Collision ASM
    Character.add_new_action(NMARINA, CargoTurn,         -1,             ActionParams.CargoTurn,         0x23,           0x8014D740,                     0x8014D790,                     0x800D8BB4,                         0x8014D478)
    Character.add_new_action(NMARINA, CargoJumpSquat,    -1,             ActionParams.CargoJumpSquat,    0x23,           0x8014D850,                     0x8014D8E4,                     0x800D8BB4,                         0x8014D478)
    Character.add_new_action(NMARINA, CargoAir,          -1,             ActionParams.CargoAir,          0x23,           0,                              0x8014DA00,                     0x800D9160,                         0x8014DA30)
    Character.add_new_action(NMARINA, CargoLanding,      -1,             ActionParams.CargoLanding,      0x23,           0x8014DC50,                     0,                              0x800D8BB4,                         0x8014D478)
    Character.add_new_action(NMARINA, CargoDamage,       -1,             ActionParams.CargoDamage,       0x23,           0x8014E050,                     0,                              0x801407A8,                         0x800DEDF0)
    Character.add_new_action(NMARINA, CargoThrow,        -1,             ActionParams.CargoThrow,        0x23,           0x8014DD00,                     0,                              0x800D8BB4,                         0x8014DECC)
    Character.add_new_action(NMARINA, CargoThrowAir,     -1,             ActionParams.CargoThrowAir,     0x23,           0x8014DD00,                     0,                              0x800D90E0,                         0x8014DEF0)
    Character.add_new_action(NMARINA, CargoItemThrowF,   -1,             ActionParams.CargoItemThrowF,   0x23,           0x8014634C,                     0,                              0x80146618,                         0x800DEDF0)
    Character.add_new_action(NMARINA, CargoItemThrowB,   -1,             ActionParams.CargoItemThrowB,   0x23,           0x8014634C,                     0,                              0x80146618,                         0x800DEDF0)
    Character.add_new_action(NMARINA, CargoItemThrowSF,  -1,             ActionParams.CargoItemThrowSF,  0x23,           0x8014634C,                     0,                              0x80146618,                         0x800DEDF0)
    Character.add_new_action(NMARINA, CargoItemThrowSB,  -1,             ActionParams.CargoItemThrowSB,  0x23,           0x8014634C,                     0,                              0x80146618,                         0x800DEDF0)
    Character.add_new_action(NMARINA, CargoJump,         -1,             ActionParams.CargoJump,         0x23,           MarinaCargo.jump_main_,         0x8014DA00,                     0x800D9160,                         0x8014DA30)
    Character.add_new_action(NMARINA, CargoShake,        -1,             ActionParams.CargoShake,        0x23,           MarinaCargo.shake_main_,        0,                              0x800D8BB4,                         0x8014D478)
    Character.add_new_action(NMARINA, USPG,              -1,             ActionParams.USPG,              0x11,           MarinaUSP.main_,                MarinaUSP.change_direction_,    MarinaUSP.physics_,                 MarinaUSP.collision_)
    Character.add_new_action(NMARINA, USPA,              -1,             ActionParams.USPA,              0x11,           MarinaUSP.main_,                MarinaUSP.change_direction_,    MarinaUSP.physics_,                 MarinaUSP.collision_)
    Character.add_new_action(NMARINA, DSPG_Begin,        -1,             ActionParams.DSPG_Begin,        0x1E,           MarinaDSP.ground_begin_main_,   0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_Wait,         -1,             ActionParams.DSPG_Wait,         0x1E,           MarinaDSP.ground_wait_main_,    0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_Absorb,       -1,             ActionParams.DSPG_Absorb,       0x1E,           MarinaDSP.ground_absorb_main_,  0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_End,          -1,             ActionParams.DSPG_End,          0x1E,           MarinaDSP.ground_end_main_,     0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_Pull,         -1,             ActionParams.DSPG_Pull,         0x1E,           MarinaDSP.pull_main_,           0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_Pull_Fail,    -1,             ActionParams.DSPG_Pull_Fail,    0x1E,           0x800D94C4,                     0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPG_Stow,         -1,             ActionParams.DSPG_Stow,         0x1E,           MarinaDSP.stow_main_,           0,                              0x800D8BB4,                         MarinaDSP.ground_collision_)
    Character.add_new_action(NMARINA, DSPA_Begin,        -1,             ActionParams.DSPA_Begin,        0x1E,           MarinaDSP.air_begin_main_,      0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_Wait,         -1,             ActionParams.DSPA_Wait,         0x1E,           MarinaDSP.air_wait_main_,       0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_Absorb,       -1,             ActionParams.DSPA_Absorb,       0x1E,           MarinaDSP.air_absorb_main_,     0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_End,          -1,             ActionParams.DSPA_End,          0x1E,           MarinaDSP.air_end_main_,        0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_Pull,         -1,             ActionParams.DSPA_Pull,         0x1E,           MarinaDSP.pull_main_,           0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_Pull_Fail,    -1,             ActionParams.DSPA_Pull_Fail,    0x1E,           0x800D94E8,                     0,                              0x800D90E0,                         MarinaDSP.air_collision_)
    Character.add_new_action(NMARINA, DSPA_Stow,         -1,             ActionParams.DSPA_Stow,         0x1E,           MarinaDSP.stow_main_,           0,                              0x800D90E0,                         MarinaDSP.air_collision_)

    // Modify Menu Action Parameters              // Action     // Animation                // Moveset Data             // Flags
    Character.edit_menu_action_parameters(NMARINA, 0x0,          File.MARINA_IDLE,           Marina.IDLE,                -1)
    Character.edit_menu_action_parameters(NMARINA, 0x1,          File.MARINA_VICTORY_1,      NO_COMMAND,                 -1)
    Character.edit_menu_action_parameters(NMARINA, 0x2,          File.MARINA_VICTORY_2,      NO_COMMAND,                 -1)
    Character.edit_menu_action_parameters(NMARINA, 0x3,          File.MARINA_VICTORY_3,      NO_COMMAND,                 -1)
    Character.edit_menu_action_parameters(NMARINA, 0x4,          File.MARINA_VICTORY_1,      NO_COMMAND,                 -1)
    Character.edit_menu_action_parameters(NMARINA, 0x5,          File.MARINA_CLAP,           Marina.CLAP,                -1)
    Character.edit_menu_action_parameters(NMARINA, 0x9,          File.MARINA_CONTINUE_FALL,  -1,                         -1)
    Character.edit_menu_action_parameters(NMARINA, 0xA,          File.MARINA_CONTINUE_UP,    -1,                         -1)
    Character.edit_menu_action_parameters(NMARINA, 0xD,          File.MARINA_1P_POSE,        Marina.ONEP,                -1)
    Character.edit_menu_action_parameters(NMARINA, 0xE,          File.MARINA_CPU_POSE,       Marina.ONEP,                -1)

    Character.table_patch_start(jab_3, Character.id.NMARINA, 0x4)
    dw      Character.jab_3.DISABLED        // disable jab 3
    OS.patch_end()
    Character.table_patch_start(rapid_jab_begin_action, Character.id.NMARINA, 0x4)
    dw      0x8014F13C                      // copied from FOX
    OS.patch_end()
    Character.table_patch_start(rapid_jab_loop_action, Character.id.NMARINA, 0x4)
    dw      0x8014F3F4                      // copied from FOX
    OS.patch_end()
    Character.table_patch_start(rapid_jab_ending_action, Character.id.NMARINA, 0x4)
    dw      0x8014F490                      // copied from FOX
    OS.patch_end()
    Character.table_patch_start(rapid_jab_unknown, Character.id.NMARINA, 0x4)
    dw      0x8014F5B0                      // copied from FOX
    OS.patch_end()

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NMARINA, 0x4)
    float32 0.63
    OS.patch_end()

    // Set action strings
    Character.table_patch_start(action_string, Character.id.NMARINA, 0x4)
    dw  Marina.Action.action_string_table
    OS.patch_end()

    // Set Magnifying Glass Scale Override
    Character.table_patch_start(magnifying_glass_zoom, Character.id.NMARINA, 0x2)
    dh  0x0053
    OS.patch_end()

    // Remove entry for now.
    Character.table_patch_start(entry_action, Character.id.NMARINA, 0x8)
    dw 0x6; dw 0x6
    OS.patch_end()
    Character.table_patch_start(entry_script, Character.id.NMARINA, 0x4)
    dw 0x8013DD68                           // skips entry script
    OS.patch_end()

    Character.table_patch_start(initial_script, Character.id.NMARINA, 0x4)
    dw      0x800D7DEC                      // use samus jump
    OS.patch_end()

    // Remove grounded script.
    Character.table_patch_start(grounded_script, Character.id.NMARINA, 0x4)
    dw Character.grounded_script.DISABLED   // skips grounded script
    OS.patch_end()

	// Set CPU SD prevent routine
    Character.table_patch_start(ai_attack_prevent, Character.id.NMARINA, 0x4)
    dw    	AI.PREVENT_ATTACK.ROUTINE.NONE
    OS.patch_end()

	// Handles common things for Polygons
	Character.polygon_setup(NMARINA, MARINA)

}
