// NMewtwo.asm

// This file contains file inclusions, action edits, and assembly for Polygon Mewtwo.

scope NMewtwo {
    // Modify Action Parameters             // Action                   // Animation                // Moveset Data             // Flags
    Character.edit_action_parameters(NMTWO,  Action.DeadU,               File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ScreenKO,            File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Entry,               File.MTWO_IDLE,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  0x006,                      File.MTWO_IDLE,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Revive1,             File.MTWO_DOWN_BNCE_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Revive2,             File.MTWO_DOWN_STND_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ReviveWait,          File.MTWO_IDLE,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Idle,                File.MTWO_IDLE,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Walk1,               File.MTWO_WALK_1,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Walk2,               File.MTWO_WALK_2,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Walk3,               File.MTWO_WALK_3,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  0x00E,                      File.MTWO_WALK_END,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Dash,                File.MTWO_DASH,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Run,                 File.MTWO_RUN,              Mewtwo.RUN_LOOP,                   0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.RunBrake,            File.MTWO_RUN_BRAKE,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Turn,                File.MTWO_TURN,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.TurnRun,             File.MTWO_TURN_RUN,         Mewtwo.RUN_TURN,                   0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.JumpSquat,           File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldJumpSquat,     File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.JumpF,               File.MTWO_JUMP_F,           Mewtwo.JUMP_1,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.JumpB,               File.MTWO_JUMP_B,           Mewtwo.JUMP_1,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.JumpAerialF,         File.MTWO_JUMP_AERIAL_F,    Mewtwo.JUMP_2,                     0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.JumpAerialB,         File.MTWO_JUMP_AERIAL_B,    Mewtwo.JUMP_2,                     0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.Fall,                File.MTWO_FALL,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FallAerial,          File.MTWO_FALL_AERIAL,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Crouch,              File.MTWO_CROUCH_BEGIN,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.CrouchIdle,          File.MTWO_CROUCH_IDLE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.CrouchEnd,           File.MTWO_CROUCH_END,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingLight,        File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingHeavy,        File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Pass,                File.MTWO_PLAT_DROP,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldDrop,          File.MTWO_PLAT_DROP,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Teeter,              File.MTWO_TEETER,           0x80000000,                        0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.TeeterStart,         File.MTWO_TEETER_START,     0x80000000,                        0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageHigh1,         File.MTWO_DMG_HIGH_1,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageHigh2,         File.MTWO_DMG_HIGH_2,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageHigh3,         File.MTWO_DMG_HIGH_3,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageMid1,          File.MTWO_DMG_MID_1,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageMid2,          File.MTWO_DMG_MID_2,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageMid3,          File.MTWO_DMG_MID_3,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageLow1,          File.MTWO_DMG_LOW_1,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageLow2,          File.MTWO_DMG_LOW_2,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageLow3,          File.MTWO_DMG_LOW_3,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageAir1,          File.MTWO_DMG_AIR_1,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageAir2,          File.MTWO_DMG_AIR_2,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageAir3,          File.MTWO_DMG_AIR_3,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageElec1,         File.MTWO_DMG_ELEC,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageElec2,         File.MTWO_DMG_ELEC,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageFlyHigh,       File.MTWO_DMG_FLY_HIGH,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageFlyMid,        File.MTWO_DMG_FLY_MID,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageFlyLow,        File.MTWO_DMG_FLY_LOW,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageFlyTop,        File.MTWO_DMG_FLY_TOP,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DamageFlyRoll,       File.MTWO_DMG_FLY_ROLL,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.WallBounce,          File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Tumble,              File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FallSpecial,         File.MTWO_FALL_SPECIAL,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingSpecial,      File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Tornado,             File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.EnterPipe,           File.MTWO_ENTER_PIPE,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ExitPipe,            File.MTWO_EXIT_PIPE,        -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ExitPipeWalk,        File.MTWO_EXIT_PIPE_WALK,   -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.CeilingBonk,         File.MTWO_CEILING_BONK,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DownBounceD,         File.MTWO_DOWN_BNCE_D,      Mewtwo.DOWN_BOUNCE,                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DownBounceU,         File.MTWO_DOWN_BNCE_U,      Mewtwo.DOWN_BOUNCE,                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DownStandD,          File.MTWO_DOWN_STND_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DownStandU,          File.MTWO_DOWN_STND_U,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.TechF,               File.MTWO_TECH_F,           Mewtwo.TECH_ROLL,                  0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.TechB,               File.MTWO_TECH_B,           Mewtwo.TECH_ROLL,                  0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.DownForwardD,        File.MTWO_DOWN_FWRD_D,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.DownForwardU,        File.MTWO_DOWN_FWRD_U,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.DownBackD,           File.MTWO_DOWN_BACK_D,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.DownBackU,           File.MTWO_DOWN_BACK_U,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.DownAttackD,         File.MTWO_DOWN_ATTK_D,      Mewtwo.DOWN_ATTACK_D,              0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DownAttackU,         File.MTWO_DOWN_ATTK_U,      Mewtwo.DOWN_ATTACK_U,              0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Tech,                File.MTWO_TECH,             Mewtwo.TECH,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  0x053,                      File.MTWO_UNKNOWN_053,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffCatch,          File.MTWO_CLF_CATCH,        Mewtwo.EDGE_GRAB,                  0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffWait,           File.MTWO_CLF_WAIT,         Mewtwo.EDGE_WAIT,                  0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffQuick,          File.MTWO_CLF_QUICK,        -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffClimbQuick1,    File.MTWO_CLF_CLM_Q_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffClimbQuick2,    File.MTWO_CLF_CLM_Q_2,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffSlow,           File.MTWO_CLF_SLOW,         -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffClimbSlow1,     File.MTWO_CLF_CLM_S_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffClimbSlow2,     File.MTWO_CLF_CLM_S_2,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffAttackQuick1,   File.MTWO_CLF_ATK_Q_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffAttackQuick2,   File.MTWO_CLF_ATK_Q_2,      Mewtwo.EDGE_ATTACK_QUICK_2,        0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffAttackSlow1,    File.MTWO_CLF_ATK_S_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffAttackSlow2,    File.MTWO_CLF_ATK_S_2,      Mewtwo.EDGE_ATTACK_SLOW_2,         0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffEscapeQuick1,   File.MTWO_CLF_ESC_Q_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffEscapeQuick2,   File.MTWO_CLF_ESC_Q_2,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffEscapeSlow1,    File.MTWO_CLF_ESC_S_1,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.CliffEscapeSlow2,    File.MTWO_CLF_ESC_S_2,      -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.LightItemPickup,     File.MTWO_L_ITM_PICKUP,     -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HeavyItemPickup,     File.MTWO_H_ITM_PICKUP,     -1,                                0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemDrop,            File.MTWO_ITM_DROP,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowDash,       File.MTWO_ITM_THROW_DASH,   -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowF,          File.MTWO_ITM_THROW_F,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowB,          File.MTWO_ITM_THROW_F,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowU,          File.MTWO_ITM_THROW_U,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowD,          File.MTWO_ITM_THROW_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowSmashF,     File.MTWO_ITM_THROW_F,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowSmashB,     File.MTWO_ITM_THROW_F,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowSmashU,     File.MTWO_ITM_THROW_U,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowSmashD,     File.MTWO_ITM_THROW_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirF,       File.MTWO_ITM_THROW_AIR_F,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirB,       File.MTWO_ITM_THROW_AIR_F,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirU,       File.MTWO_ITM_THROW_AIR_U,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirD,       File.MTWO_ITM_THROW_AIR_D,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirSmashF,  File.MTWO_ITM_THROW_AIR_F,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirSmashB,  File.MTWO_ITM_THROW_AIR_F,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirSmashU,  File.MTWO_ITM_THROW_AIR_U,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ItemThrowAirSmashD,  File.MTWO_ITM_THROW_AIR_D,  -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HeavyItemThrowF,     File.MTWO_HEAVY_ITM_THROW,  -1,                                0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.HeavyItemThrowB,     File.MTWO_HEAVY_ITM_THROW,  -1,                                0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.HeavyItemThrowSmashF,File.MTWO_HEAVY_ITM_THROW,  -1,                                0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.HeavyItemThrowSmashB,File.MTWO_HEAVY_ITM_THROW,  -1,                                0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.BeamSwordNeutral,    File.MTWO_ITM_NEUTRAL,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.BeamSwordTilt,       File.MTWO_ITM_TILT,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.BeamSwordSmash,      File.MTWO_ITM_SMASH,        -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.BeamSwordDash,       File.MTWO_ITM_DASH,         -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.BatNeutral,          File.MTWO_ITM_NEUTRAL,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.BatTilt,             File.MTWO_ITM_TILT,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.BatSmash,            File.MTWO_ITM_SMASH,        -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.BatDash,             File.MTWO_ITM_DASH,         -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.FanNeutral,          File.MTWO_ITM_NEUTRAL,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FanTilt,             File.MTWO_ITM_TILT,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FanSmash,            File.MTWO_ITM_SMASH,        -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.FanDash,             File.MTWO_ITM_DASH,         -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.StarRodNeutral,      File.MTWO_ITM_NEUTRAL,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StarRodTilt,         File.MTWO_ITM_TILT,         -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StarRodSmash,        File.MTWO_ITM_SMASH,        -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.StarRodDash,         File.MTWO_ITM_DASH,         -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.RayGunShoot,         File.MTWO_ITM_SHOOT,        Mewtwo.ITEM_SHOOT,                 0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.RayGunShootAir,      File.MTWO_ITM_SHOOT_AIR,    Mewtwo.ITEM_SHOOT,                 0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FireFlowerShoot,     File.MTWO_ITM_SHOOT,        Mewtwo.ITEM_SHOOT,                 0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FireFlowerShootAir,  File.MTWO_ITM_SHOOT_AIR,    Mewtwo.ITEM_SHOOT,                 0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerIdle,          File.MTWO_HAMMER_IDLE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerWalk,          File.MTWO_HAMMER_MOVE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerTurn,          File.MTWO_HAMMER_MOVE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerJumpSquat,     File.MTWO_HAMMER_MOVE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerAir,           File.MTWO_HAMMER_MOVE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.HammerLanding,       File.MTWO_HAMMER_MOVE,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldOn,            File.MTWO_SHIELD_ON,        -1,                                0xA0000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldOff,           File.MTWO_SHIELD_OFF,       -1,                                0xA0000000)
    Character.edit_action_parameters(NMTWO,  Action.RollF,               File.MTWO_ROLL_F,           -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.RollB,               File.MTWO_ROLL_B,           -1,                                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldBreak,         File.MTWO_DMG_FLY_TOP,      Mewtwo.SHIELD_BREAK,               0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ShieldBreakFall,     File.MTWO_TUMBLE,           Mewtwo.SPARKLE,                    0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StunLandD,           File.MTWO_DOWN_BNCE_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StunLandU,           File.MTWO_DOWN_BNCE_U,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StunStartD,          File.MTWO_DOWN_STND_D,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.StunStartU,          File.MTWO_DOWN_STND_U,      -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Stun,                File.MTWO_STUN,             Mewtwo.STUN,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Sleep,               File.MTWO_STUN,             Mewtwo.ASLEEP,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Grab,                File.MTWO_CATCH,            Mewtwo.GRAB,                       0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.GrabPull,            File.MTWO_CATCH_PULL,       Mewtwo.GRAB_PULL,                  0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.ThrowF,              File.MTWO_THROW_F,          Mewtwo.FTHROW,                     0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.ThrowB,              File.MTWO_THROW_B,          Mewtwo.BTHROW,                     0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.CapturePulled,       File.MTWO_CAPTURE_PULLED,   -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.InhalePulled,        File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.InhaleSpat,          File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.InhaleCopied,        File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.EggLayPulled,        File.MTWO_CAPTURE_PULLED,   -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.EggLay,              File.MTWO_IDLE,             -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FalconDivePulled,    File.MTWO_DMG_HIGH_3,       -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  0x0B4,                      File.MTWO_TUMBLE,           -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.ThrownDKPulled,      File.MTWO_THROWN_DK_PULLED, -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.ThrownMarioBros,     File.MTWO_THROWN_BROS,      -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.ThrownDK,            File.MTWO_THROWN_DK,        -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.Thrown1,             File.MTWO_THROWN_1,         -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.Thrown2,             File.MTWO_THROWN_2,         -1,                                0x80000000)
    Character.edit_action_parameters(NMTWO,  Action.Taunt,               File.MTWO_TAUNT,            Mewtwo.TAUNT,                      0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Jab1,                File.MTWO_JAB_1,            Mewtwo.JAB_1,                      0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.Jab2,                0,                          0x80000000,                        0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DashAttack,          File.MTWO_DASH_ATTACK,      Mewtwo.DASH_ATTACK,                0x40000000)
    Character.edit_action_parameters(NMTWO,  Action.FTiltHigh,           File.MTWO_FTILT_HIGH,       Mewtwo.FTILT_HI,                   0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FTilt,               File.MTWO_FTILT,            Mewtwo.FTILT,                      0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FTiltLow,            File.MTWO_FTILT_LOW,        Mewtwo.FTILT_LO,                   0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.UTilt,               File.MTWO_UTILT,            Mewtwo.UTILT,                      0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DTilt,               File.MTWO_DTILT,            Mewtwo.DTILT,                      0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FSmashHigh,          File.MTWO_FSMASH_HIGH,      Mewtwo.FSMASH_HI,                  0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FSmash,              File.MTWO_FSMASH,           Mewtwo.FSMASH,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.FSmashLow,           File.MTWO_FSMASH_LOW,       Mewtwo.FSMASH_LO,                  0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.USmash,              File.MTWO_USMASH,           Mewtwo.USMASH,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.DSmash,              File.MTWO_DSMASH,           Mewtwo.DSMASH,                     0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.AttackAirN,          File.MTWO_ATTACK_AIR_N,     Mewtwo.NAIR,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.AttackAirF,          File.MTWO_ATTACK_AIR_F,     Mewtwo.FAIR,                       0x10000000)
    Character.edit_action_parameters(NMTWO,  Action.AttackAirB,          File.MTWO_ATTACK_AIR_B,     Mewtwo.BAIR,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.AttackAirU,          File.MTWO_ATTACK_AIR_U,     Mewtwo.UAIR,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.AttackAirD,          File.MTWO_ATTACK_AIR_D,     Mewtwo.DAIR,                       0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirN,         File.MTWO_LANDING_AIR_N,    Mewtwo.NAIR_LANDING,               0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirF,         File.MTWO_LANDING_AIR_F,    Mewtwo.FAIR_LANDING,               0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirB,         File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirU,         File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirD,         File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  Action.LandingAirX,         File.MTWO_LANDING,          -1,                                0x00000000)
    Character.edit_action_parameters(NMTWO,  0xDC,                       File.MTWO_IDLE,             0x80000000,                        0x00000000)
    Character.edit_action_parameters(NMTWO,  0xDD,                       File.MTWO_IDLE,             0x80000000,                        0x00000000)
    Character.edit_action_parameters(NMTWO,  0xDE,                       File.MTWO_NSPG_BEGIN,       Mewtwo.NSPG_BEGIN,                 0x10000000)
    Character.edit_action_parameters(NMTWO,  0xDF,                       File.MTWO_NSPG_CHARGE,      Mewtwo.NSPG_CHARGE,                0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE0,                       File.MTWO_NSPG_SHOOT,       Mewtwo.NSPG_SHOOT,                 0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE1,                       File.MTWO_NSPA_BEGIN,       Mewtwo.NSPA_BEGIN,                 0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE2,                       File.MTWO_NSPA_CHARGE,      Mewtwo.NSPA_CHARGE,                0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE4,                       File.MTWO_NSPA_SHOOT,       Mewtwo.NSPA_SHOOT,                 0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE5,                       File.MTWO_DSPG,             Mewtwo.DSP,                        0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE6,                       File.MTWO_DSPA,             Mewtwo.DSP,                        0x10000000)
    Character.edit_action_parameters(NMTWO,  0xE7,                       File.MTWO_JAB_2,            Mewtwo.JAB_LOOP_START,             0x00000000)
    Character.edit_action_parameters(NMTWO,  0xE8,                       File.MTWO_JAB_2_LOOP,       Mewtwo.JAB_LOOP,                   0x00000000)
    Character.edit_action_parameters(NMTWO,  0xE9,                       File.MTWO_JAB_2_END,        0x80000000,                 0x00000000)

    // Modify Actions            // Action          // Staling ID   // Main ASM                     // Interrupt/Other ASM              // Movement/Physics ASM         // Collision ASM    
    Character.edit_action(NMTWO, 0xDC,                -1,              0x8013D994,                   0x00000000,                         0x00000000,                     0x00000000)
    Character.edit_action(NMTWO, 0xDD,                -1,              0x8013D994,                   0x00000000,                         0x00000000,                     0x00000000)
    Character.edit_action(NMTWO, 0xDE,               0x12,             MewtwoNSP.begin_main_,        0x8015D464,                         0x800D8BB4,                     MewtwoNSP.ground_begin_collision_)  //NSP_Ground_Begin
    Character.edit_action(NMTWO, 0xDF,               0x12,             MewtwoNSP.charge_main_,       MewtwoNSP.ground_charge_interrupt_, 0x800D8BB4,                     MewtwoNSP.ground_charge_collision_) //NSP_Ground_Charge
    Character.edit_action(NMTWO, 0xE0,               0x12,             MewtwoNSP.shoot_main_,        0,                                  0x800D8BB4,                     MewtwoNSP.ground_shoot_collision_)  //NSP_Ground_Shoot
    Character.edit_action(NMTWO, 0xE1,               0x12,             MewtwoNSP.begin_main_,        0x8015D464,                         0x800D90E0,                     MewtwoNSP.air_begin_collision_)     //NSP_Air_Begin
    Character.edit_action(NMTWO, 0xE2,               0x12,             MewtwoNSP.charge_main_,       MewtwoNSP.air_charge_interrupt_,    0x800D91EC,                     MewtwoNSP.air_charge_collision_)    //NSP_Air_Charge
    Character.edit_action(NMTWO, 0xE4,               0x12,             MewtwoNSP.shoot_main_,        0,                                  0x800D91EC,                     MewtwoNSP.air_shoot_collision_)     //NSP_Air_Shoot
    Character.edit_action(NMTWO, 0xE5,               0x1E,             0x800D94C4,                   0,                                  0x800D8BB4,                     MewtwoDSP.ground_collision_)        //DSP_Ground
    Character.edit_action(NMTWO, 0xE6,               0x1E,             0x800D94E8,                   0,                                  0x800D91EC,                     MewtwoDSP.air_collision_)           //DSP_Air
    Character.edit_action(NMTWO, 0xE5,               0x1E,             0x800D94C4,                   0,                                  0x800D8BB4,                     MewtwoDSP.ground_collision_)        //DSP_Ground_Begin
    Character.edit_action(NMTWO, 0xE6,               0x1E,             0x800D94E8,                   0,                                  0x800D91EC,                     MewtwoDSP.air_collision_)           //DSP_Air
    Character.edit_action(NMTWO, 0xE7,               0x4,              0x8014F0D0,                   0,                                  0x800D8BB4,                     0x800DDF44)                         //RapidJabStart
    Character.edit_action(NMTWO, 0xE8,               0x4,              0x8014F2A8,                   0x8014F388,                         0x800D8BB4,                     0x800DDF44)                         //RapidJabLoop
    Character.edit_action(NMTWO, 0xE9,               0x4,              0x800D94C4,                   0,                                  0x800D8BB4,                     0x800DDF44)                         //RapidJabEnd
    
    // Add Action Parameters                // Action Name      // Base Action  // Animation                // Moveset Data             // Flags
    Character.add_new_action_params(NMTWO,   USP_Ground_Begin,   -1,             File.MTWO_USPG_BEGIN,       Mewtwo.USP_BEGIN,                  0)
    Character.add_new_action_params(NMTWO,   USP_Ground_End,     -1,             File.MTWO_USPG_END,         Mewtwo.USP_END,                    0)
    Character.add_new_action_params(NMTWO,   USP_Air_Begin,      -1,             File.MTWO_USPA_BEGIN,       Mewtwo.USP_BEGIN,                  0)
    Character.add_new_action_params(NMTWO,   USP_Air_End,        -1,             File.MTWO_USPA_END,         Mewtwo.USP_END,                    0)

    // Add Actions                   // Action Name     // Base Action  //Parameters                        // Staling ID   // Main ASM                     // Interrupt/Other ASM          // Movement/Physics ASM             // Collision ASM
    Character.add_new_action(NMTWO,   USP_Ground_Begin,  -1,             ActionParams.USP_Ground_Begin,      0x11,           MewtwoUSP.begin_main_,          0,                              0x800D8BB4,                         MewtwoUSP.ground_begin_collision_)
    Character.add_new_action(NMTWO,   USP_Ground_Move,   -1,             -1,                                 0x11,           MewtwoUSP.move_main_,           0,                              MewtwoUSP.move_physics_,            MewtwoUSP.ground_move_collision_)
    Character.add_new_action(NMTWO,   USP_Ground_End,    -1,             ActionParams.USP_Ground_End,        0x11,           MewtwoUSP.ground_end_main_,     0,                              0x800D8BB4,                         MewtwoUSP.end_collision_)
    Character.add_new_action(NMTWO,   USP_Air_Begin,     -1,             ActionParams.USP_Air_Begin,         0x11,           MewtwoUSP.begin_main_,          0,                              0x800D91EC,                         MewtwoUSP.air_begin_collision_)
    Character.add_new_action(NMTWO,   USP_Air_Move,      -1,             -1,                                 0x11,           MewtwoUSP.move_main_,           0,                              MewtwoUSP.move_physics_,            MewtwoUSP.air_move_collision_)
    Character.add_new_action(NMTWO,   USP_Air_End,       -1,             ActionParams.USP_Air_End,           0x11,           MewtwoUSP.air_end_main_,        0,                              0x800D91EC,                         MewtwoUSP.end_collision_)

    // Modify Menu Action Parameters                // Action       // Animation                 // Moveset Data             // Flags
    Character.edit_menu_action_parameters(NMTWO,     0x0,            File.MTWO_IDLE,             -1,                         -1)
    Character.edit_menu_action_parameters(NMTWO,     0x1,            File.MTWO_VICTORY_1,        Mewtwo.VICTORY_1,                  -1)
    Character.edit_menu_action_parameters(NMTWO,     0x2,            File.MTWO_VICTORY_2,        Mewtwo.VICTORY_2,                  -1)
    Character.edit_menu_action_parameters(NMTWO,     0x3,            File.MTWO_VICTORY_3,        Mewtwo.VICTORY_3,                  -1)
    Character.edit_menu_action_parameters(NMTWO,     0x4,            File.MTWO_VICTORY_2,        Mewtwo.VICTORY_2,                  -1)
    Character.edit_menu_action_parameters(NMTWO,     0x5,            File.MTWO_CLAP,             0x80000000,                 -1)
    Character.edit_menu_action_parameters(NMTWO,     0x9,            File.MTWO_CONTINUE_FALL,    0x80000000,                 -1)
    Character.edit_menu_action_parameters(NMTWO,     0xA,            File.MTWO_CONTINUE_UP,      0x80000000,                 -1)
    Character.edit_menu_action_parameters(NMTWO,     0xD,            File.MTWO_POSE_1P,          0x80000000,                 -1)
    Character.edit_menu_action_parameters(NMTWO,     0xE,            File.MTWO_1P_CPU_POSE,      0x80000000,                 -1)

    // Set subroutines for special move initiations.
    Character.table_patch_start(ground_nsp, Character.id.NMTWO, 0x4)
    dw      MewtwoNSP.ground_begin_initial_
    OS.patch_end()
    Character.table_patch_start(air_nsp, Character.id.NMTWO, 0x4)
    dw      MewtwoNSP.air_begin_initial_
    OS.patch_end()
    Character.table_patch_start(ground_usp, Character.id.NMTWO, 0x4)
    dw      MewtwoUSP.ground_begin_initial_
    OS.patch_end()
    Character.table_patch_start(air_usp, Character.id.NMTWO, 0x4)
    dw      MewtwoUSP.air_begin_initial_
    OS.patch_end()
    Character.table_patch_start(ground_dsp, Character.id.NMTWO, 0x4)
    dw      MewtwoDSP.ground_initial_
    OS.patch_end()
    Character.table_patch_start(air_dsp, Character.id.NMTWO, 0x4)
    dw      MewtwoDSP.air_initial_
    OS.patch_end()

    // Set subroutines for rapid jab actions.
    Character.table_patch_start(rapid_jab_begin_action, Character.id.NMTWO, 0x4)
    dw      Mewtwo.set_rapid_jab_begin_action_
    OS.patch_end()
    Character.table_patch_start(rapid_jab_loop_action, Character.id.NMTWO, 0x4)
    dw      Mewtwo.set_rapid_jab_loop_action_
    OS.patch_end()
    Character.table_patch_start(rapid_jab_ending_action, Character.id.NMTWO, 0x4)
    dw      Mewtwo.set_rapid_jab_ending_action_
    OS.patch_end()

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NMTWO, 0x4)
    float32 0.9
    OS.patch_end()
    
    // Set Magnifying Glass Scale Override
    Character.table_patch_start(magnifying_glass_zoom, Character.id.NMTWO, 0x2)
    dh  0x006B
    OS.patch_end()

    // @ Description
    // NMewtwo's extra actions
    scope Action {
        constant Appear1(0x0DC)
        constant Appear2(0x0DD)
        constant ShadowBallStart(0x0DE)
        constant ShadowBallCharge(0x0DF)
        constant ShadowBallShoot(0x0E0)
        constant ShadowBallStartAir(0x0E1)
        constant ShadowBallChargeAir(0x0E2)
        //constant x(0x0E3)
        constant ShadowBallShootAir(0x0E4)
        constant Disable(0x0E5)
        constant DisableAir(0x0E6)
        constant JabLoopStart(0x0E7)
        constant JabLoop(0x0E8)
        constant JabLoopEnd(0x0E9)
        constant TeleportStart(0x0EA)
        constant Teleport(0x0EB)
        constant TeleportEnd(0x0EC)
        constant TeleportStartAir(0x0ED)
        constant TeleportAir(0x0EE)
        constant TeleportEndAir(0x0EF)
    }

    // Set action strings
    Character.table_patch_start(action_string, Character.id.NMTWO, 0x4)
    dw  Mewtwo.Action.action_string_table
    OS.patch_end()
    
    // Handles common things for Polygons
    Character.polygon_setup(NMTWO, MTWO)
   }
