// Action.asm

// This file contains constants for known action IDs
scope Action {
    constant DeadD(0x000)
    constant DeadS(0x001)
    constant DeadU(0x002)
    constant ScreenKO(0x003)
    constant ScreenKOWait(0x004)
    constant Entry(0x005)
    // constant ?(0x006)
    constant Revive1(0x007)
    constant Revive2(0x008)
    constant ReviveWait(0x009)
    constant Idle(0x00A)
    constant Walk1(0x00B)
    constant Walk2(0x00C)
    constant Walk3(0x00D)
    // constant WalkEnd(0x00E)
    constant Dash(0x00F)
    constant Run(0x010)
    constant RunBrake(0x011)
    constant Turn(0x012)
    constant TurnRun(0x013)
    constant JumpSquat(0x014)
    constant ShieldJumpSquat(0x015)
    constant JumpF(0x016)
    constant JumpB(0x017)
    constant JumpAerialF(0x018)
    constant JumpAerialB(0x019)
    constant Fall(0x01A)
    constant FallAerial(0x01B)
    constant Crouch(0x01C)
    constant CrouchIdle(0x01D)
    constant CrouchEnd(0x01E)
    constant LandingLight(0x01F)
    constant LandingHeavy(0x020)
    constant Pass(0x021)
    constant ShieldDrop(0x022)
    constant Teeter(0x023)
    constant TeeterStart(0x024)
    constant DamageHigh1(0x025)
    constant DamageHigh2(0x026)
    constant DamageHigh3(0x027)
    constant DamageMid1(0x028)
    constant DamageMid2(0x029)
    constant DamageMid3(0x02A)
    constant DamageLow1(0x02B)
    constant DamageLow2(0x02C)
    constant DamageLow3(0x02D)
    constant DamageAir1(0x02E)
    constant DamageAir2(0x02F)
    constant DamageAir3(0x030)
    constant DamageElec1(0x031)
    constant DamageElec2(0x032)
    constant DamageFlyHigh(0x033)
    constant DamageFlyMid(0x034)
    constant DamageFlyLow(0x035)
    constant DamageFlyTop(0x036)
    constant DamageFlyRoll(0x037)
    constant WallBounce(0x038)
    constant Tumble(0x039)
    constant FallSpecial(0x03A)
    constant LandingSpecial(0x03B)
    constant Tornado(0x03C)
    constant Barrel(0x03D)
    constant EnterPipe(0x03E)
    constant Pipe(0x03F)
    constant ExitPipe(0x040)
    constant ExitPipeWalk(0x041)
    constant CeilingBonk(0x042)
    constant DownBounceD(0x043)
    constant DownBounceU(0x044)
    constant DownWaitD(0x045)
    constant DownWaitU(0x046)
    constant DownStandD(0x047)
    constant DownStandU(0x048)
    constant TechF(0x049)
    constant TechB(0x04A)
    constant DownForwardD(0x04B)
    constant DownForwardU(0x04C)
    constant DownBackD(0x04D)
    constant DownBackU(0x04E)
    constant DownAttackD(0x04F)
    constant DownAttackU(0x050)
    constant Tech(0x051)
    constant Clang(0x052)
    constant ClangRecoil(0x053)
    constant CliffCatch(0x054)
    constant CliffWait(0x055)
    constant CliffQuick(0x056)
    constant CliffClimbQuick1(0x057)
    constant CliffClimbQuick2(0x058)
    constant CliffSlow(0x059)
    constant CliffClimbSlow1(0x05A)
    constant CliffClimbSlow2(0x05B)
    constant CliffAttackQuick1(0x05C)
    constant CliffAttackQuick2(0x05D)
    constant CliffAttackSlow1(0x05E)
    constant CliffAttackSlow2(0x05F)
    constant CliffEscapeQuick1(0x060)
    constant CliffEscapeQuick2(0x061)
    constant CliffEscapeSlow1(0x062)
    constant CliffEscapeSlow2(0x063)
    constant LightItemPickup(0x064)
    constant HeavyItemPickup(0x065)
    constant HeavyItemHold(0x066)
    constant HeavyItemTurn(0x067)
    constant ItemDrop(0x068)
    constant ItemThrowDash(0x069)
    constant ItemThrowF(0x06A)
    constant ItemThrowB(0x06B)
    constant ItemThrowU(0x06C)
    constant ItemThrowD(0x06D)
    constant ItemThrowSmashF(0x06E)
    constant ItemThrowSmashB(0x06F)
    constant ItemThrowSmashU(0x070)
    constant ItemThrowSmashD(0x071)
    constant ItemThrowAirF(0x072)
    constant ItemThrowAirB(0x073)
    constant ItemThrowAirU(0x074)
    constant ItemThrowAirD(0x075)
    constant ItemThrowAirSmashF(0x076)
    constant ItemThrowAirSmashB(0x077)
    constant ItemThrowAirSmashU(0x078)
    constant ItemThrowAirSmashD(0x079)
    constant HeavyItemThrowF(0x07A)
    constant HeavyItemThrowB(0x07B)
    constant HeavyItemThrowSmashF(0x07C)
    constant HeavyItemThrowSmashB(0x07D)
    constant BeamSwordNeutral(0x07E)
    constant BeamSwordTilt(0x07F)
    constant BeamSwordSmash(0x080)
    constant BeamSwordDash(0x081)
    constant BatNeutral(0x082)
    constant BatTilt(0x083)
    constant BatSmash(0x084)
    constant BatDash(0x085)
    constant FanNeutral(0x086)
    constant FanTilt(0x087)
    constant FanSmash(0x088)
    constant FanDash(0x089)
    constant StarRodNeutral(0x08A)
    constant StarRodTilt(0x08B)
    constant StarRodSmash(0x08C)
    constant StarRodDash(0x08D)
    constant RayGunShoot(0x08E)
    constant RayGunShootAir(0x08F)
    constant FireFlowerShoot(0x090)
    constant FireFlowerShootAir(0x091)
    constant HammerIdle(0x092)
    constant HammerWalk(0x093)
    constant HammerTurn(0x094)
    constant HammerJumpSquat(0x095)
    constant HammerAir(0x096)
    constant HammerLanding(0x097)
    constant ShieldOn(0x098)
    constant Shield(0x099)
    constant ShieldOff(0x09A)
    constant ShieldStun(0x09B)
    constant RollF(0x09C)
    constant RollB(0x09D)
    constant ShieldBreak(0x09E)
    constant ShieldBreakFall(0x09F)
    constant StunLandD(0x0A0)
    constant StunLandU(0x0A1)
    constant StunStartD(0x0A2)
    constant StunStartU(0x0A3)
    constant Stun(0x0A4)
    constant Sleep(0x0A5)
    constant Grab(0x0A6)
    constant GrabPull(0x0A7)
    constant GrabWait(0x0A8)
    constant ThrowF(0x0A9)
    constant ThrowB(0x0AA)
    constant CapturePulled(0x0AB)
    constant CaptureWait(0x0AC)
    constant InhalePulled(0x0AD)
    constant InhaleWait(0x0AE)
    constant InhaleSpat(0x0AF)
    constant InhaleCopied(0x0B0)
    constant EggLayPulled(0x0B1)
    constant EggLay(0x0B2)
    constant FalconDivePulled(0x0B3)
    // constant ?(0x0B4)
    constant ThrownDKPulled(0x0B5)
    constant ThrownMarioBros(0x0B6)
    constant ThrownFoxFStart(0x0B7)
    constant ThrownDK(0x0B8)
    constant Thrown1(0x0B9)
    constant Thrown2(0x0BA)
    constant Thrown3(0x0BB)
    constant ThrownFoxB(0x0BC)
    constant Taunt(0x0BD)
    constant Jab1(0x0BE)
    constant Jab2(0x0BF)
    constant DashAttack(0x0C0)
    constant FTiltHigh(0x0C1)
    constant FTiltMidHigh(0x0C2)
    constant FTilt(0x0C3)
    constant FTiltMidLow(0x0C4)
    constant FTiltLow(0x0C5)
    // constant UtiltF(0x0C6) [forward angled up tilt, you can assign an animation and moveset data to that action and it actually works and takes the input]
    constant UTilt(0x0C7)
    // constant ?(0x0C8)
    constant DTilt(0x0C9)
    constant FSmashHigh(0x0CA)
    constant FSmashMidHigh(0x0CB)
    constant FSmash(0x0CC)
    constant FSmashMidLow(0x0CD)
    constant FSmashLow(0x0CE)
    constant USmash(0x0CF)
    constant DSmash(0x0D0)
    constant AttackAirN(0x0D1)
    constant AttackAirF(0x0D2)
    constant AttackAirB(0x0D3)
    constant AttackAirU(0x0D4)
    constant AttackAirD(0x0D5)
    constant LandingAirN(0x0D6)
    constant LandingAirF(0x0D7)
    constant LandingAirB(0x0D8)
    constant LandingAirU(0x0D9)
    constant LandingAirD(0x0DA)
    constant LandingAirX(0x0DB)

    // strings!
    string_0x000:; String.insert("DeadD")
    string_0x001:; String.insert("DeadS")
    string_0x002:; String.insert("DeadU")
    string_0x003:; String.insert("ScreenKO")
    // string_0x004:; String.insert("?")
    string_0x005:; String.insert("Entry")
    // string_0x006:; String.insert("?")
    string_0x007:; String.insert("Revive1")
    string_0x008:; String.insert("Revive2")
    string_0x009:; String.insert("ReviveWait")
    string_0x00A:; String.insert("Idle")
    string_0x00B:; String.insert("Walk1")
    string_0x00C:; String.insert("Walk2")
    string_0x00D:; String.insert("Walk3")
    // string_0x00E:; String.insert("WalkEnd")
    string_0x00F:; String.insert("Dash")
    string_0x010:; String.insert("Run")
    string_0x011:; String.insert("RunBrake")
    string_0x012:; String.insert("Turn")
    string_0x013:; String.insert("TurnRun")
    string_0x014:; String.insert("JumpSquat")
    string_0x015:; String.insert("ShieldJumpSquat")
    string_0x016:; String.insert("JumpF")
    string_0x017:; String.insert("JumpB")
    string_0x018:; String.insert("JumpAerialF")
    string_0x019:; String.insert("JumpAerialB")
    string_0x01A:; String.insert("Fall")
    string_0x01B:; String.insert("FallAerial")
    string_0x01C:; String.insert("Crouch")
    string_0x01D:; String.insert("CrouchIdle")
    string_0x01E:; String.insert("CrouchEnd")
    string_0x01F:; String.insert("LandingLight")
    string_0x020:; String.insert("LandingHeavy")
    string_0x021:; String.insert("Pass")
    string_0x022:; String.insert("ShieldDrop")
    string_0x023:; String.insert("Teeter")
    string_0x024:; String.insert("TeeterStart")
    string_0x025:; String.insert("DamageHigh1")
    string_0x026:; String.insert("DamageHigh2")
    string_0x027:; String.insert("DamageHigh3")
    string_0x028:; String.insert("DamageMid1")
    string_0x029:; String.insert("DamageMid2")
    string_0x02A:; String.insert("DamageMid3")
    string_0x02B:; String.insert("DamageLow1")
    string_0x02C:; String.insert("DamageLow2")
    string_0x02D:; String.insert("DamageLow3")
    string_0x02E:; String.insert("DamageAir1")
    string_0x02F:; String.insert("DamageAir2")
    string_0x030:; String.insert("DamageAir3")
    string_0x031:; String.insert("DamageElec1")
    string_0x032:; String.insert("DamageElec2")
    string_0x033:; String.insert("DamageFlyHigh")
    string_0x034:; String.insert("DamageFlyMid")
    string_0x035:; String.insert("DamageFlyLow")
    string_0x036:; String.insert("DamageFlyTop")
    string_0x037:; String.insert("DamageFlyRoll")
    string_0x038:; String.insert("WallBounce")
    string_0x039:; String.insert("Tumble")
    string_0x03A:; String.insert("FallSpecial")
    string_0x03B:; String.insert("LandingSpecial")
    string_0x03C:; String.insert("Tornado")
    string_0x03D:; String.insert("Barrel")
    string_0x03E:; String.insert("EnterPipe")
    string_0x03F:; String.insert("Pipe")
    string_0x040:; String.insert("ExitPipe")
    string_0x041:; String.insert("ExitPipeWalk")
    string_0x042:; String.insert("CeilingBonk")
    string_0x043:; String.insert("DownBounceD")
    string_0x044:; String.insert("DownBounceU")
    string_0x045:; String.insert("DownWaitD")
    string_0x046:; String.insert("DownWaitU")
    string_0x047:; String.insert("DownStandD")
    string_0x048:; String.insert("DownStandU")
    string_0x049:; String.insert("TechF")
    string_0x04A:; String.insert("TechB")
    string_0x04B:; String.insert("DownForwardD")
    string_0x04C:; String.insert("DownForwardU")
    string_0x04D:; String.insert("DownBackD")
    string_0x04E:; String.insert("DownBackU")
    string_0x04F:; String.insert("DownAttackD")
    string_0x050:; String.insert("DownAttackU")
    string_0x051:; String.insert("Tech")
    string_0x052:; String.insert("Clang")
    string_0x053:; String.insert("ClangRecoil")
    string_0x054:; String.insert("CliffCatch")
    string_0x055:; String.insert("CliffWait")
    string_0x056:; String.insert("CliffQuick")
    string_0x057:; String.insert("CliffClimbQuick1")
    string_0x058:; String.insert("CliffClimbQuick2")
    string_0x059:; String.insert("CliffSlow")
    string_0x05A:; String.insert("CliffClimbSlow1")
    string_0x05B:; String.insert("CliffClimbSlow2")
    string_0x05C:; String.insert("CliffAttackQuick1")
    string_0x05D:; String.insert("CliffAttackQuick2")
    string_0x05E:; String.insert("CliffAttackSlow1")
    string_0x05F:; String.insert("CliffAttackSlow2")
    string_0x060:; String.insert("CliffEscapeQuick1")
    string_0x061:; String.insert("CliffEscapeQuick2")
    string_0x062:; String.insert("CliffEscapeSlow1")
    string_0x063:; String.insert("CliffEscapeSlow2")
    string_0x064:; String.insert("LightItemPickup")
    string_0x065:; String.insert("HeavyItemPickup")
    string_0x066:; String.insert("HeavyItemHold")
    string_0x067:; String.insert("HeavyItemTurn")
    string_0x068:; String.insert("ItemDrop")
    string_0x069:; String.insert("ItemThrowDash")
    string_0x06A:; String.insert("ItemThrowF")
    string_0x06B:; String.insert("ItemThrowB")
    string_0x06C:; String.insert("ItemThrowU")
    string_0x06D:; String.insert("ItemThrowD")
    string_0x06E:; String.insert("ItemThrowSmashF")
    string_0x06F:; String.insert("ItemThrowSmashB")
    string_0x070:; String.insert("ItemThrowSmashU")
    string_0x071:; String.insert("ItemThrowSmashD")
    string_0x072:; String.insert("ItemThrowAirF")
    string_0x073:; String.insert("ItemThrowAirB")
    string_0x074:; String.insert("ItemThrowAirU")
    string_0x075:; String.insert("ItemThrowAirD")
    string_0x076:; String.insert("ItemThrowAirSmashF")
    string_0x077:; String.insert("ItemThrowAirSmashB")
    string_0x078:; String.insert("ItemThrowAirSmashU")
    string_0x079:; String.insert("ItemThrowAirSmashD")
    string_0x07A:; String.insert("HeavyItemThrowF")
    string_0x07B:; String.insert("HeavyItemThrowB")
    string_0x07C:; String.insert("HeavyItemThrowSmashF")
    string_0x07D:; String.insert("HeavyItemThrowSmashB")
    string_0x07E:; String.insert("BeamSwordNeutral")
    string_0x07F:; String.insert("BeamSwordTilt")
    string_0x080:; String.insert("BeamSwordSmash")
    string_0x081:; String.insert("BeamSwordDash")
    string_0x082:; String.insert("BatNeutral")
    string_0x083:; String.insert("BatTilt")
    string_0x084:; String.insert("BatSmash")
    string_0x085:; String.insert("BatDash")
    string_0x086:; String.insert("FanNeutral")
    string_0x087:; String.insert("FanTilt")
    string_0x088:; String.insert("FanSmash")
    string_0x089:; String.insert("FanDash")
    string_0x08A:; String.insert("StarRodNeutral")
    string_0x08B:; String.insert("StarRodTilt")
    string_0x08C:; String.insert("StarRodSmash")
    string_0x08D:; String.insert("StarRodDash")
    string_0x08E:; String.insert("RayGunShoot")
    string_0x08F:; String.insert("RayGunShootAir")
    string_0x090:; String.insert("FireFlowerShoot")
    string_0x091:; String.insert("FireFlowerShootAir")
    string_0x092:; String.insert("HammerIdle")
    string_0x093:; String.insert("HammerWalk")
    string_0x094:; String.insert("HammerTurn")
    string_0x095:; String.insert("HammerJumpSquat")
    string_0x096:; String.insert("HammerAir")
    string_0x097:; String.insert("HammerLanding")
    string_0x098:; String.insert("ShieldOn")
    string_0x099:; String.insert("Shield")
    string_0x09A:; String.insert("ShieldOff")
    string_0x09B:; String.insert("ShieldStun")
    string_0x09C:; String.insert("RollF")
    string_0x09D:; String.insert("RollB")
    string_0x09E:; String.insert("ShieldBreak")
    string_0x09F:; String.insert("ShieldBreakFall")
    string_0x0A0:; String.insert("StunLandD")
    string_0x0A1:; String.insert("StunLandU")
    string_0x0A2:; String.insert("StunStartD")
    string_0x0A3:; String.insert("StunStartU")
    string_0x0A4:; String.insert("Stun")
    string_0x0A5:; String.insert("Sleep")
    string_0x0A6:; String.insert("Grab")
    string_0x0A7:; String.insert("GrabPull")
    string_0x0A8:; String.insert("GrabWait")
    string_0x0A9:; String.insert("ThrowF")
    string_0x0AA:; String.insert("ThrowB")
    string_0x0AB:; String.insert("CapturePulled")
    string_0x0AC:; String.insert("CaptureWait")
    string_0x0AD:; String.insert("InhalePulled")
    string_0x0AE:; String.insert("InhaleWait")
    string_0x0AF:; String.insert("InhaleSpat")
    string_0x0B0:; String.insert("InhaleCopied")
    string_0x0B1:; String.insert("EggLayPulled")
    string_0x0B2:; String.insert("EggLay")
    string_0x0B3:; String.insert("FalconDivePulled")
    // string_0x0B4:; String.insert("?")
    string_0x0B5:; String.insert("ThrownDKPulled")
    string_0x0B6:; String.insert("ThrownMarioBros")
    string_0x0B7:; String.insert("ThrownFoxFStart")
    string_0x0B8:; String.insert("ThrownDK")
    string_0x0B9:; String.insert("Thrown1")
    string_0x0BA:; String.insert("Thrown2")
    string_0x0BB:; String.insert("Thrown3")
    string_0x0BC:; String.insert("ThrownFoxB")
    string_0x0BD:; String.insert("Taunt")
    string_0x0BE:; String.insert("Jab1")
    string_0x0BF:; String.insert("Jab2")
    string_0x0C0:; String.insert("DashAttack")
    string_0x0C1:; String.insert("FTiltHigh")
    string_0x0C2:; String.insert("FTiltMidHigh")
    string_0x0C3:; String.insert("FTilt")
    string_0x0C4:; String.insert("FTiltMidLow")
    string_0x0C5:; String.insert("FTiltLow")
    // string_0x0C6:; String.insert("?")
    string_0x0C7:; String.insert("UTilt")
    // string_0x0C8:; String.insert("?")
    string_0x0C9:; String.insert("DTilt")
    string_0x0CA:; String.insert("FSmashHigh")
    string_0x0CB:; String.insert("FSmashMidHigh")
    string_0x0CC:; String.insert("FSmash")
    string_0x0CD:; String.insert("FSmashMidLow")
    string_0x0CE:; String.insert("FSmashLow")
    string_0x0CF:; String.insert("USmash")
    string_0x0D0:; String.insert("DSmash")
    string_0x0D1:; String.insert("AttackAirN")
    string_0x0D2:; String.insert("AttackAirF")
    string_0x0D3:; String.insert("AttackAirB")
    string_0x0D4:; String.insert("AttackAirU")
    string_0x0D5:; String.insert("AttackAirD")
    string_0x0D6:; String.insert("LandingAirN")
    string_0x0D7:; String.insert("LandingAirF")
    string_0x0D8:; String.insert("LandingAirB")
    string_0x0D9:; String.insert("LandingAirU")
    string_0x0DA:; String.insert("LandingAirD")
    string_0x0DB:; String.insert("LandingAirX")

    // @ Description
    // This table holds pointers to all the shared action strings
    shared_action_string_table:
    dw string_0x000
    dw string_0x001
    dw string_0x002
    dw string_0x003
    dw 0 // string_0x004
    dw string_0x005
    dw 0 // string_0x006
    dw string_0x007
    dw string_0x008
    dw string_0x009
    dw string_0x00A
    dw string_0x00B
    dw string_0x00C
    dw string_0x00D
    dw 0 // string_0x00E
    dw string_0x00F
    dw string_0x010
    dw string_0x011
    dw string_0x012
    dw string_0x013
    dw string_0x014
    dw string_0x015
    dw string_0x016
    dw string_0x017
    dw string_0x018
    dw string_0x019
    dw string_0x01A
    dw string_0x01B
    dw string_0x01C
    dw string_0x01D
    dw string_0x01E
    dw string_0x01F
    dw string_0x020
    dw string_0x021
    dw string_0x022
    dw string_0x023
    dw string_0x024
    dw string_0x025
    dw string_0x026
    dw string_0x027
    dw string_0x028
    dw string_0x029
    dw string_0x02A
    dw string_0x02B
    dw string_0x02C
    dw string_0x02D
    dw string_0x02E
    dw string_0x02F
    dw string_0x030
    dw string_0x031
    dw string_0x032
    dw string_0x033
    dw string_0x034
    dw string_0x035
    dw string_0x036
    dw string_0x037
    dw string_0x038
    dw string_0x039
    dw string_0x03A
    dw string_0x03B
    dw string_0x03C
    dw string_0x03D
    dw string_0x03E
    dw string_0x03F
    dw string_0x040
    dw string_0x041
    dw string_0x042
    dw string_0x043
    dw string_0x044
    dw string_0x045
    dw string_0x046
    dw string_0x047
    dw string_0x048
    dw string_0x049
    dw string_0x04A
    dw string_0x04B
    dw string_0x04C
    dw string_0x04D
    dw string_0x04E
    dw string_0x04F
    dw string_0x050
    dw string_0x051
    dw string_0x052
    dw string_0x053
    dw string_0x054
    dw string_0x055
    dw string_0x056
    dw string_0x057
    dw string_0x058
    dw string_0x059
    dw string_0x05A
    dw string_0x05B
    dw string_0x05C
    dw string_0x05D
    dw string_0x05E
    dw string_0x05F
    dw string_0x060
    dw string_0x061
    dw string_0x062
    dw string_0x063
    dw string_0x064
    dw string_0x065
    dw string_0x066
    dw string_0x067
    dw string_0x068
    dw string_0x069
    dw string_0x06A
    dw string_0x06B
    dw string_0x06C
    dw string_0x06D
    dw string_0x06E
    dw string_0x06F
    dw string_0x070
    dw string_0x071
    dw string_0x072
    dw string_0x073
    dw string_0x074
    dw string_0x075
    dw string_0x076
    dw string_0x077
    dw string_0x078
    dw string_0x079
    dw string_0x07A
    dw string_0x07B
    dw string_0x07C
    dw string_0x07D
    dw string_0x07E
    dw string_0x07F
    dw string_0x080
    dw string_0x081
    dw string_0x082
    dw string_0x083
    dw string_0x084
    dw string_0x085
    dw string_0x086
    dw string_0x087
    dw string_0x088
    dw string_0x089
    dw string_0x08A
    dw string_0x08B
    dw string_0x08C
    dw string_0x08D
    dw string_0x08E
    dw string_0x08F
    dw string_0x090
    dw string_0x091
    dw string_0x092
    dw string_0x093
    dw string_0x094
    dw string_0x095
    dw string_0x096
    dw string_0x097
    dw string_0x098
    dw string_0x099
    dw string_0x09A
    dw string_0x09B
    dw string_0x09C
    dw string_0x09D
    dw string_0x09E
    dw string_0x09F
    dw string_0x0A0
    dw string_0x0A1
    dw string_0x0A2
    dw string_0x0A3
    dw string_0x0A4
    dw string_0x0A5
    dw string_0x0A6
    dw string_0x0A7
    dw string_0x0A8
    dw string_0x0A9
    dw string_0x0AA
    dw string_0x0AB
    dw string_0x0AC
    dw string_0x0AD
    dw string_0x0AE
    dw string_0x0AF
    dw string_0x0B0
    dw string_0x0B1
    dw string_0x0B2
    dw string_0x0B3
    dw 0 // string_0x0B4
    dw string_0x0B5
    dw string_0x0B6
    dw string_0x0B7
    dw string_0x0B8
    dw string_0x0B9
    dw string_0x0BA
    dw string_0x0BB
    dw string_0x0BC
    dw string_0x0BD
    dw string_0x0BE
    dw string_0x0BF
    dw string_0x0C0
    dw string_0x0C1
    dw string_0x0C2
    dw string_0x0C3
    dw string_0x0C4
    dw string_0x0C5
    dw 0 // string_0x0C6
    dw string_0x0C7
    dw 0 // string_0x0C8
    dw string_0x0C9
    dw string_0x0CA
    dw string_0x0CB
    dw string_0x0CC
    dw string_0x0CD
    dw string_0x0CE
    dw string_0x0CF
    dw string_0x0D0
    dw string_0x0D1
    dw string_0x0D2
    dw string_0x0D3
    dw string_0x0D4
    dw string_0x0D5
    dw string_0x0D6
    dw string_0x0D7
    dw string_0x0D8
    dw string_0x0D9
    dw string_0x0DA
    dw string_0x0DB

    // @ Description
    // Common strings for use in extra action tables below
    scope COMMON {
    	string_jab3:; String.insert("Jab3")
    	string_jabloopstart:; String.insert("JabLoopStart")
    	string_jabloop:; String.insert("JabLoop")
    	string_jabloopend:; String.insert("JabLoopEnd")
        string_appear1:; String.insert("Appear1")
        string_appear2:; String.insert("Appear2")
    }

    // @ Description
    // Mario's extra actions
    scope MARIO {
        constant Jab3(0x0DC)
        constant Appear1(0x0DD)
        constant Appear2(0x0DE)
        constant Fireball(0x0DF)
        constant FireballAir(0x0E0)
        constant SuperJumpPunch(0x0E1)
        constant SuperJumpPunchAir(0x0E2)
        constant MarioTornado(0x0E3)
        constant MarioTornadoAir(0x0E4)

        // strings!
        //string_0x0DC:; String.insert("Jab3")
        //string_0x0DD:; String.insert("Appear1")
        //string_0x0DE:; String.insert("Appear2")
        string_0x0DF:; String.insert("Fireball")
        string_0x0E0:; String.insert("FireballAir")
        string_0x0E1:; String.insert("SuperJumpPunch")
        string_0x0E2:; String.insert("SuperJumpPunchAir")
        string_0x0E3:; String.insert("MarioTornado")
        string_0x0E4:; String.insert("MarioTornadoAir")

        action_string_table:
        dw COMMON.string_jab3
        dw COMMON.string_appear1
        dw COMMON.string_appear2
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
    }

    // @ Description
    // Fox's extra actions
    scope FOX {
        constant JabLoopStart(0x0DC)
        constant JabLoop(0x0DD)
        constant JabLoopEnd(0x0DE)
        constant Appear1(0x0DF)
        constant Appear2(0x0E0)
        constant Laser(0x0E1)
        constant LaserAir(0x0E2)
        constant FireFoxStart(0x0E3)
        constant FireFoxStartAir(0x0E4)
        constant ReadyingFireFox(0x0E5)
        constant ReadyingFireFoxAir(0x0E6)
        constant FireFox(0x0E7)
        constant FireFoxAir(0x0E8)
        constant FireFoxEnd(0x0E9)
        constant FireFoxEndAir(0x0EA)
        constant LandingFireFoxAir(0x0EB)
        constant ReflectorStart(0x0EC)
        constant Reflecting(0x0ED)
        constant ReflectorEnd(0x0EE)
        constant ReflectorLoop(0x0EF)
        constant ReflectorTurn(0x0F0)
        constant ReflectorStartAir(0x0F1)
        constant ReflectingAir(0x0F2)
        constant ReflectorEndAir(0x0F3)
        constant ReflectorAir(0x0F4)
        constant ReflectorTurnAir(0x0F5)

        // strings!
        //string_0x0DC:; String.insert("JabLoopStart")
        //string_0x0DD:; String.insert("JabLoop")
        //string_0x0DE:; String.insert("JabLoopEnd")
        //string_0x0DF:; String.insert("Appear1")
        //string_0x0E0:; String.insert("Appear2")
        string_0x0E1:; String.insert("Laser")
        string_0x0E2:; String.insert("LaserAir")
        string_0x0E3:; String.insert("FireFoxStart")
        string_0x0E4:; String.insert("FireFoxStartAir")
        string_0x0E5:; String.insert("ReadyingFireFox")
        string_0x0E6:; String.insert("ReadyingFireFoxAir")
        string_0x0E7:; String.insert("FireFox")
        string_0x0E8:; String.insert("FireFoxAir")
        string_0x0E9:; String.insert("FireFoxEnd")
        string_0x0EA:; String.insert("FireFoxEndAir")
        string_0x0EB:; String.insert("FireFoxBounce")
        string_0x0EC:; String.insert("ReflectorStart")
        string_0x0ED:; String.insert("Reflecting")
        string_0x0EE:; String.insert("ReflectorEnd")
        string_0x0EF:; String.insert("ReflectorLoop")
        string_0x0F0:; String.insert("ReflectorTurn")
        string_0x0F1:; String.insert("ReflectorStartAir")
        string_0x0F2:; String.insert("ReflectingAir")
        string_0x0F3:; String.insert("ReflectorEndAir")
        string_0x0F4:; String.insert("ReflectorAir")
        string_0x0F5:; String.insert("ReflectorTurnAir")

        action_string_table:
        dw COMMON.string_jabloopstart
        dw COMMON.string_jabloop
        dw COMMON.string_jabloopend
        dw COMMON.string_appear1
        dw COMMON.string_appear2
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
        dw string_0x0EE
        dw string_0x0EF
        dw string_0x0F0
        dw string_0x0F1
        dw 0 //dw string_0x0F2
        dw string_0x0F3
        dw string_0x0F4
        dw string_0x0F5
    }

    // @ Description
    // DK's extra actions
    scope DK {
        constant Appear1(0x0DC)
        constant Appear2(0x0DD)
        constant GiantPunchLoopStart(0x0DE)
        constant GiantPunchLoopStartAir(0x0DF)
        constant GiantPunchLoop(0x0E0)
        constant GiantPunchLoopAir(0x0E1)
        constant GiantPunch(0x0E2)
        constant GiantPunchAir(0x0E3)
        constant GiantPunchFullyCharged(0x0E4)
        constant GiantPunchFullyChargedAir(0x0E5)
        constant SpinningKong(0x0E6)
        constant SpinningKongAir(0x0E7)
        constant HandSlapStart(0x0E8)
        constant HandSlapLoop(0x0E9)
        constant HandSlapEnd(0x0EA)
        constant Cargo(0x0EB)
        constant CargoVerySlowWalk(0x0EC)
        constant CargoSlowWalk(0x0ED)
        constant CargoWalk(0x0EE)
        constant CargoTurn(0x0EF)
        constant CargoJumpsquat(0x0F0)
        constant CargoJump(0x0F1)
        constant CargoLanding(0x0F2)
        //constant ?(0x0F3)
        constant CargoThrow(0x0F4)
        constant CargoThrowAir(0x0F5)
        constant HeavyItemThrowF(0x0F6)
        constant HeavyItemThrowB(0x0F7)
        constant HeavyItemThrowSmashF(0x0F8)
        constant HeavyItemThrowSmashB(0x0F9)

        // strings!
        string_0x0DC:; String.insert("Appear1")
        string_0x0DD:; String.insert("Appear2")
        string_0x0DE:; String.insert("GiantPunchLoopStart")
        string_0x0DF:; String.insert("GiantPunchLoopStartAir")
        string_0x0E0:; String.insert("GiantPunchLoop")
        string_0x0E1:; String.insert("GiantPunchLoopAir")
        string_0x0E2:; String.insert("GiantPunch")
        string_0x0E3:; String.insert("GiantPunchAir")
        string_0x0E4:; String.insert("GiantPunchFullyCharged")
        string_0x0E5:; String.insert("GiantPunchFullyChargedAir")
        string_0x0E6:; String.insert("SpinningKong")
        string_0x0E7:; String.insert("SpinningKongAir")
        string_0x0E8:; String.insert("HandSlapStart")
        string_0x0E9:; String.insert("HandSlapLoop")
        string_0x0EA:; String.insert("HandSlapEnd")
        string_0x0EB:; String.insert("Cargo")
        string_0x0EC:; String.insert("CargoVerySlowWalk")
        string_0x0ED:; String.insert("CargoSlowWalk")
        string_0x0EE:; String.insert("CargoWalk")
        string_0x0EF:; String.insert("CargoTurn")
        string_0x0F0:; String.insert("CargoJumpsquat")
        string_0x0F1:; String.insert("CargoJump")
        string_0x0F2:; String.insert("CargoLanding")
        //string_0x0F3:; String.insert("?")
        string_0x0F4:; String.insert("CargoThrow")
        string_0x0F5:; String.insert("CargoThrowAir")
        string_0x0F6:; String.insert("HeavyItemThrowF")
        string_0x0F7:; String.insert("HeavyItemThrowB")
        string_0x0F8:; String.insert("HeavyItemThrowSmashF")
        string_0x0F9:; String.insert("HeavyItemThrowSmashB")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
        dw string_0x0EE
        dw string_0x0EF
        dw string_0x0F0
        dw string_0x0F1
        dw string_0x0F2
        dw 0 // dw string_0x0F3
        dw string_0x0F4
        dw string_0x0F5
        dw string_0x0F6
        dw string_0x0F7
        dw string_0x0F8
        dw string_0x0F9
    }

    // @ Description
    // Samus's extra actions
    scope SAMUS {
        constant Appear1(0x0DC)
        constant Appear2(0x0DD)
        constant ChargeShotStart(0x0DE)
        constant ChargeShotCharging(0x0DF)
        constant ChargeShotShooting(0x0E0)
        constant ChargeShotStartAir(0x0E1)
        constant ChargeShotShootingAir(0x0E2)
        constant ScrewAttack(0x0E3)
        constant ScrewAttackAir(0x0E4)
        constant Bomb(0x0E5)
        constant BombAir(0x0E6)

        // strings!
        string_0x0DC:; String.insert("Appear1")
        string_0x0DD:; String.insert("Appear2")
        string_0x0DE:; String.insert("ChargeShotStart")
        string_0x0DF:; String.insert("ChargeShotCharging")
        string_0x0E0:; String.insert("ChargeShotShooting")
        string_0x0E1:; String.insert("ChargeShotStartAir")
        string_0x0E2:; String.insert("ChargeShotShootingAir")
        string_0x0E3:; String.insert("ScrewAttack")
        string_0x0E4:; String.insert("ScrewAttackAir")
        string_0x0E5:; String.insert("Bomb")
        string_0x0E6:; String.insert("BombAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
    }

    // @ Description
    // Luigi's extra actions
    scope LUIGI {
        constant Jab3(0x0DC)
        constant Appear1(0x0DD)
        constant Appear2(0x0DE)
        constant Fireball(0x0DF)
        constant FireballAir(0x0E0)
        constant SuperJumpPunch(0x0E1)
        constant SuperJumpPunchAir(0x0E2)
        constant LuigiCyclone(0x0E3)
        constant LuigiCycloneAir(0x0E4)

        // strings!
        //string_0x0DC:; String.insert("Jab3")
        //string_0x0DD:; String.insert("Appear1")
        //string_0x0DE:; String.insert("Appear2")
        //string_0x0DF:; String.insert("Fireball")
        //string_0x0E0:; String.insert("FireballAir")
        //string_0x0E1:; String.insert("SuperJumpPunch")
        //string_0x0E2:; String.insert("SuperJumpPunchAir")
        string_0x0E3:; String.insert("LuigiCyclone")
        string_0x0E4:; String.insert("LuigiCycloneAir")

        action_string_table:
        dw COMMON.string_jab3
        dw COMMON.string_appear1
        dw COMMON.string_appear2
        dw MARIO.string_0x0DF
        dw MARIO.string_0x0E0
        dw MARIO.string_0x0E1
        dw MARIO.string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
    }

    // @ Description
    // Link's extra actions
    scope LINK {
        constant Jab3(0x0DC)
        constant JabLoopStart(0x0DD)
        constant JabLoop(0x0DE)
        constant JabLoopEnd(0x0DF)
        constant Appear1(0x0E0)
        constant Appear2(0x0E1)
        constant SpinAttack(0x0E2)
        constant SpinAttackEnd(0x0E3)
        constant SpinAttackAir(0x0E4)
        constant Boomerang(0x0E5)
        constant BoomerangCatch(0x0E6)
        constant BoomerangMiss(0x0E7)
        constant BoomerangAir(0x0E8)
        constant BoomerangCatchAir(0x0E9)
        constant BoomerangMissAir(0x0EA)
        constant Bomb(0x0EB)
        constant BombAir(0x0EC)

        // strings!
        string_0x0DC:; String.insert("Jab3")
        string_0x0DD:; String.insert("JabLoopStart")
        string_0x0DE:; String.insert("JabLoop")
        string_0x0DF:; String.insert("JabLoopEnd")
        string_0x0E0:; String.insert("Appear1")
        string_0x0E1:; String.insert("Appear2")
        string_0x0E2:; String.insert("SpinAttack")
        string_0x0E3:; String.insert("SpinAttackEnd")
        string_0x0E4:; String.insert("SpinAttackAir")
        string_0x0E5:; String.insert("Boomerang")
        string_0x0E6:; String.insert("BoomerangCatch")
        string_0x0E7:; String.insert("BoomerangMiss")
        string_0x0E8:; String.insert("BoomerangAir")
        string_0x0E9:; String.insert("BoomerangCatchAir")
        string_0x0EA:; String.insert("BoomerangMissAir")
        string_0x0EB:; String.insert("Bomb")
        string_0x0EC:; String.insert("BombAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
    }

    // @ Description
    // Yoshi's extra actions
    scope YOSHI {
        constant Appear1(0x0DC)
        constant Appear2(0x0DD)
        constant EggThrow(0x0DE)
        constant EggThrowAir(0x0DF)
        constant GroundPoundStart(0x0E0)
        constant GroundPoundLanding(0x0E1)
        constant GroundPoundAir(0x0E2)
        constant GroundPoundDrop(0x0E3)
        constant EggLayUseMiss(0x0E4)
        constant EggLayGrabOut(0x0E5)
        constant EggLayGrabIn(0x0E6)
        constant EggLayUseMissAir(0x0E7)
        constant EggLayGrabOutAir(0x0E8)
        constant EggLayGrabInAir(0x0E9)

        // strings!
        string_0x0DC:; String.insert("Appear1")
        string_0x0DD:; String.insert("Appear2")
        string_0x0DE:; String.insert("EggThrow")
        string_0x0DF:; String.insert("EggThrowAir")
        string_0x0E0:; String.insert("GroundPoundStart")
        string_0x0E1:; String.insert("GroundPoundLanding")
        string_0x0E2:; String.insert("GroundPoundAir")
        string_0x0E3:; String.insert("GroundPoundDrop")
        string_0x0E4:; String.insert("EggLayUseMiss")
        string_0x0E5:; String.insert("EggLayGrabOut")
        string_0x0E6:; String.insert("EggLayGrabIn")
        string_0x0E7:; String.insert("EggLayUseMissAir")
        string_0x0E8:; String.insert("EggLayGrabOutAir")
        string_0x0E9:; String.insert("EggLayGrabInAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
    }

    // @ Description
    // Captain's extra actions
    scope CAPTAIN {
        constant Jab3(0x0DC)
        constant JabLoopStart(0x0DD)
        constant JabLoop(0x0DE)
        constant JabLoopEnd(0x0DF)
        constant Appear(0x0E0)
        constant AppearAir(0x0E1)
        constant BlueFalcon1(0x0E2)
        constant BlueFalcon2(0x0E3)
        constant FalconPunch(0x0E4)
        constant FalconPunchAir(0x0E5)
        constant FalconKick(0x0E6)
        constant FalconKickFromGroundAir(0x0E7)
        constant LandingFalconKick(0x0E8)
        constant FalconKickEnd(0x0E9)
        constant CollisionFalconKick(0x0EA)
        constant FalconDive(0x0EB)
        constant FalconDiveCatch(0x0EC)
        constant FalconDiveEnd1(0x0ED)
        constant FalconDiveEnd2(0x0EE)

        // strings!
        string_0x0DC:; String.insert("Jab3")
        string_0x0DD:; String.insert("JabLoopStart")
        string_0x0DE:; String.insert("JabLoop")
        string_0x0DF:; String.insert("JabLoopEnd")
        string_0x0E0:; String.insert("Appear")
        string_0x0E1:; String.insert("AppearAir")
        string_0x0E2:; String.insert("BlueFalcon1")
        string_0x0E3:; String.insert("BlueFalcon2")
        string_0x0E4:; String.insert("FalconPunch")
        string_0x0E5:; String.insert("FalconPunchAir")
        string_0x0E6:; String.insert("FalconKick")
        string_0x0E7:; String.insert("FalconKickFromGroundAir")
        string_0x0E8:; String.insert("LandingFalconKick")
        string_0x0E9:; String.insert("FalconKickAir")
        string_0x0EA:; String.insert("FalconKickRecoil")
        string_0x0EB:; String.insert("FalconDiveGround")
        string_0x0EC:; String.insert("FalconDiveCatch")
        string_0x0ED:; String.insert("FalconDiveRelease")
        string_0x0EE:; String.insert("FalconDiveAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
        dw string_0x0EE
    }

    // @ Description
    // Kirby's extra actions
    scope KIRBY {
        constant JabLoopStart(0x0DC)
        constant JabLoop(0x0DD)
        constant JabLoopEnd(0x0DE)
        constant Jump2(0x0DF)
        constant Jump3(0x0E0)
        constant Jump4(0x0E1)
        constant Jump5(0x0E2)
        constant Jump6(0x0E3)
        constant ForwardThrow(0x0E4)
        constant ForwardThrowFall(0x0E5)
        constant ForwardThrowRecoil(0x0E6)
        constant MarioFireball(0x0E7)
        constant MarioFireballAir(0x0E8)
        constant LuigiFireball(0x0E9)
        constant LuigiFireballAir(0x0EA)
        constant Laser(0x0EB)
        constant LaserAir(0x0EC)
        constant ChargeShotStart(0x0ED)
        constant Charging(0x0EE)
        constant ShootingChargeShot(0x0EF)
        constant ChargeShotAir(0x0F0)
        constant ShootingChargeShotAir(0x0F1)
        constant ChargePunchStart(0x0F2)
        constant ChargePunchStartAir(0x0F3)
        constant ChargePunch(0x0F4)
        constant ChargePunchAir(0x0F5)
        constant Punch(0x0F6)
        constant PunchAir(0x0F7)
        constant FullyChargedPunch(0x0F8)
        constant FullyChargedPunchAir(0x0F9)
        constant Staring1(0x0FA)
        constant Staring2(0x0FB)
        constant Lightning(0x0FC)
        constant LightningAir(0x0FD)
        constant PKFire(0x0FE)
        constant PKFireAir(0x0FF)
        constant FinalCutter(0x100)
        constant FinalCutterLand(0x101)
        constant FinalCutterAir(0x102)
        constant FinalCutterFall(0x103)
        constant StoneStart(0x104)
        // constant ?(0x105)
        constant Stone(0x106)
        constant StoneEnd(0x107)
        constant StoneStartAir(0x108)
        constant StoneFall(0x109)
        constant StoneLanding(0x10A)
        constant StoneFall2(0x10B)
        constant StoneEndAir(0x10C)
        constant InhaleStart(0x10D)
        constant Inhale(0x10E)
        constant InhaleEnd(0x10F)
        constant InhalePull(0x110)
        constant InhaleSwallow(0x111)
        constant InhaleSpit(0x112)
        constant InhaleIdle(0x113)
        constant InhaleTurn(0x114)
        constant InhaleCopy(0x115)
        constant InhaleStartAir(0x116)
        constant InhaleAir(0x117)
        constant InhaleEndAir(0x118)
        constant InhalePullAir(0x119)
        constant InhaleSwallowAir(0x11A)
        constant InhaleSpitAir(0x11B)
        constant InhaleFall(0x11C)
        constant InhaleTurnAir(0x11D)
        constant InhaleCopyAir(0x11E)
        constant Boomerang(0x11F)
        constant BoomerangCatch(0x120)
        constant BoomerangMissCatch(0x121)
        constant BoomerangAir(0x122)
        constant BoomerangCatchAir(0x123)
        constant BoomerangMissCatchAir(0x124)
        constant Pound(0x125)
        constant PoundAir(0x126)
        constant FalconPunch(0x127)
        constant FalconPunchAir(0x128)
        constant EggLay(0x129)
        constant SucceedingEggLay(0x12A)
        constant EggLayEnd(0x12B)
        constant EggLayAir(0x12C)
        constant SucceedingEggLayAir(0x12D)
        constant EggLayEndAir(0x12E)
        constant WarlockPunch(0x12F)
        constant WarlockPunchAir(0x130)
        constant Capsule(0x131)
        constant CapsuleAir(0x132)
        constant DSCharging(0x133)
        constant YLBoomerang(0x134)
        constant YLBoomerangAir(0x135)
        constant LucasPKFire(0x136)
        constant LucasPKFireAir(0x137)
        constant BodySlam(0x138)
        constant BodySlamAir(0x139)
        constant BodySlamRecoil(0x13A)
        constant BodySlamRecoilAir(0x13B)
        constant Phantasm(0x13C)
        constant PhantasmAir(0x13D)
        constant FlameBreath(0x13E)
        constant FlameBreathAir(0x13F)
        constant Book(0x140)
        constant BookAir(0x141)
        constant Blaster(0x142)
        constant BlasterAir(0x143)
        constant CatapultStart(0x144)
        constant CatapultCharge(0x145)
        constant CatapultShoot(0x146)
        constant CatapultStartAir(0x147)
        constant CatapultChargeAir(0x148)
        constant CatapultShootAir(0x149)
        constant ShadowBallStart(0x14A)
        constant ShadowBallCharge(0x14B)
        constant ShadowBallShoot(0x14C)
        constant ShadowBallStartAir(0x14D)
        constant ShadowBallChargeAir(0x14E)
        constant ShadowBallShootAir(0x14F)
        constant DancingBlade1(0x150)
        constant DancingBlade2High(0x151)
        constant DancingBlade2Mid(0x152)
        constant DancingBlade2Low(0x153)
        constant DancingBlade3High(0x154)
        constant DancingBlade3Mid(0x155)
        constant DancingBlade3Low(0x156)
        constant DancingBlade1Air(0x157)
        constant DancingBlade2HighAir(0x158)
        constant DancingBlade2MidAir(0x159)
        constant DancingBlade2LowAir(0x15A)
        constant DancingBlade3HighAir(0x15B)
        constant DancingBlade3MidAir(0x15C)
        constant DancingBlade3LowAir(0x15D)
        constant HomingStart(0x15E)
        constant HomingMove(0x15F)
        constant HomingLockedMove(0x160)
        constant HomingEndGround(0x161)
        constant HomingEndAir(0x162)
        constant HomingRecoilGround(0x163)
        constant HomingRecoilAir(0x164)
        constant HomingBounce(0x165)
        constant NeedleStormStartGround(0x166)
        constant NeedleStormChargeGround(0x167)
        constant NeedleStormShootGround(0x168)
        constant NeedleStormStartAir(0x169)
        constant NeedleStormChargeAir(0x16A)
        constant NeedleStormShootAir(0x16B)
        constant DededeInhaleStart(0x16C)
        constant DededeInhale(0x16D)
        constant DededeInhalePull(0x16E)
        constant DededeInhaleSwallow(0x16F)
        constant DededeInhaleIdle(0x170)
        constant DededeInhaleSpit(0x171)
        constant DededeInhaleTurn(0x172)
        constant DededeInhaleEnd(0x173)
        constant DededeInhaleStartAir(0x174)
        constant DededeInhaleAir(0x175)
        constant DededeInhalePullAir(0x176)
        constant DededeInhaleSwallowAir(0x177)
        constant DededeInhaleFall(0x178)
        constant DededeInhaleSpitAir(0x179)
        constant DededeInhaleTurnAir(0x17A)
        constant DededeInhaleEndAir(0x17B)
        constant DededeSwallowWalk1(0x17C)
        constant DededeSwallowWalk2(0x17D)
        constant DededeSwallowWalk3(0x17E)
        constant MarinaNSPG(0x17F)
        constant MarinaNSPGPull(0x180)
        constant MarinaNSPGThrow(0x181)
        constant MarinaNSPGThrowU(0x182)
        constant MarinaNSPGThrowD(0x183)
        constant MarinaNSPA(0x184)
        constant MarinaNSPAPull(0x185)
        constant MarinaNSPAThrow(0x186)
        constant MarinaNSPAThrowU(0x187)
        constant MarinaNSPAThrowD(0x188)
        constant GoemonNSPGBegin(0x189)
        constant GoemonNSPGWait(0x18A)
        constant GoemonNSPGWalk1(0x18B)
        constant GoemonNSPGWalk2(0x18C)
        constant GoemonNSPGBWalk1(0x18D)
        constant GoemonNSPGBWalk2(0x18E)
        constant GoemonNSPGEnd(0x18F)
        constant GoemonNSPABegin(0x190)
        constant GoemonNSPAWait(0x191)
        constant GoemonNSPAEnd(0x192)
        constant SlippyNSPG(0x193)
        constant SlippyNSPA(0x194)
        constant RevolverBeginGround(0x195)
        constant RevolverChargeGround(0x196)
        constant RevolverShootGround(0x197)
        constant RevolverBeginAir(0x198)
        constant RevolverChargeAir(0x199)
        constant RevolverShootAir(0x19A)
        constant BanjoNSPBeginG(0x19B)
        constant BanjoNSPForwardG(0x19C)
        constant BanjoNSPBackwardG(0x19D)
        constant BanjoNSPBeginA(0x19E)
        constant BanjoNSPForwardA(0x19F)
        constant BanjoNSPBackwardA(0x1A0)
        constant EbiNSPGroundBegin(0x1A1)
        constant EbiNSPGroundWait(0x1A2)
        constant EbiNSPGroundWalk1(0x1A3)
        constant EbiNSPGroundWalk2(0x1A4)
        constant EbiNSPGroundBWalk1(0x1A5)
        constant EbiNSPGroundBWalk2(0x1A6)
        constant EbiNSPGroundEnd(0x1A7)
        constant EbiNSPAirBegin(0x1A8)
        constant EbiNSPAirIdle(0x1A9)
        constant EbiNSPAirEnd(0x1AA)
        constant DragonKingNSPGround(0x1AB)
        constant DragonKingNSPAir(0x1AC)


        // strings!
        string_0x0DC:; String.insert("JabLoopStart")
        string_0x0DD:; String.insert("JabLoop")
        string_0x0DE:; String.insert("JabLoopEnd")
        string_0x0DF:; String.insert("Jump2")
        string_0x0E0:; String.insert("Jump3")
        string_0x0E1:; String.insert("Jump4")
        string_0x0E2:; String.insert("Jump5")
        string_0x0E3:; String.insert("Jump6")
        string_0x0E4:; String.insert("ForwardThrow")
        string_0x0E5:; String.insert("ForwardThrowFall")
        string_0x0E6:; String.insert("ForwardThrowRecoil")
        string_0x0E7:; String.insert("MarioFireball")
        string_0x0E8:; String.insert("MarioFireballAir")
        string_0x0E9:; String.insert("LuigiFireball")
        string_0x0EA:; String.insert("LuigiFireballAir")
        string_0x0EB:; String.insert("Laser")
        string_0x0EC:; String.insert("LaserAir")
        string_0x0ED:; String.insert("ChargeShotStart")
        string_0x0EE:; String.insert("Charging")
        string_0x0EF:; String.insert("ShootingChargeShot")
        string_0x0F0:; String.insert("ChargeShotAir")
        string_0x0F1:; String.insert("ShootingChargeShotAir")
        string_0x0F2:; String.insert("ChargePunchStart")
        string_0x0F3:; String.insert("ChargePunchStartAir")
        string_0x0F4:; String.insert("ChargePunch")
        string_0x0F5:; String.insert("ChargePunchAir")
        string_0x0F6:; String.insert("Punch")
        string_0x0F7:; String.insert("PunchAir")
        string_0x0F8:; String.insert("FullyChargedPunch")
        string_0x0F9:; String.insert("FullyChargedPunchAir")
        string_0x0FA:; String.insert("Staring1")
        string_0x0FB:; String.insert("Staring2")
        string_0x0FC:; String.insert("Lightning")
        string_0x0FD:; String.insert("LightningAir")
        string_0x0FE:; String.insert("PKFire")
        string_0x0FF:; String.insert("PKFireAir")
        string_0x100:; String.insert("FinalCutter")
        string_0x101:; String.insert("FinalCutterLand")
        string_0x102:; String.insert("FinalCutterAir")
        string_0x103:; String.insert("FinalCutterFall")
        string_0x104:; String.insert("StoneStart")
        // string_0x105:; String.insert("?")
        string_0x106:; String.insert("Stone")
        string_0x107:; String.insert("StoneEnd")
        string_0x108:; String.insert("StoneStartAir")
        string_0x109:; String.insert("StoneFall")
        string_0x10A:; String.insert("StoneLanding")
        string_0x10B:; String.insert("StoneFall2")
        string_0x10C:; String.insert("StoneEndAir")
        string_0x10D:; String.insert("InhaleStart")
        string_0x10E:; String.insert("Inhale")
        string_0x10F:; String.insert("InhaleEnd")
        string_0x110:; String.insert("InhalePull")
        string_0x111:; String.insert("InhaleSwallow")
        string_0x112:; String.insert("InhaleSpit")
        string_0x113:; String.insert("InhaleIdle")
        string_0x114:; String.insert("InhaleTurn")
        string_0x115:; String.insert("InhaleCopy")
        string_0x116:; String.insert("InhaleStartAir")
        string_0x117:; String.insert("InhaleAir")
        string_0x118:; String.insert("InhaleEndAir")
        string_0x119:; String.insert("InhalePullAir")
        string_0x11A:; String.insert("InhaleSwallowAir")
        string_0x11B:; String.insert("InhaleSpitAir")
        string_0x11C:; String.insert("InhaleFall")
        string_0x11D:; String.insert("InhaleTurnAir")
        string_0x11E:; String.insert("InhaleCopyAir")
        string_0x11F:; String.insert("Boomerang")
        string_0x120:; String.insert("BoomerangCatch")
        string_0x121:; String.insert("BoomerangMissCatch")
        string_0x122:; String.insert("BoomerangAir")
        string_0x123:; String.insert("BoomerangCatchAir")
        string_0x124:; String.insert("BoomerangMissCatchAir")
        string_0x125:; String.insert("Pound")
        string_0x126:; String.insert("PoundAir")
        string_0x127:; String.insert("FalconPunch")
        string_0x128:; String.insert("FalconPunchAir")
        string_0x129:; String.insert("EggLay")
        string_0x12A:; String.insert("SucceedingEggLay")
        string_0x12B:; String.insert("EggLayEnd")
        string_0x12C:; String.insert("EggLayAir")
        string_0x12D:; String.insert("SucceedingEggLayAir")
        string_0x12E:; String.insert("EggLayEndAir")
        string_0x12F:; String.insert("WarlockPunch")
        string_0x130:; String.insert("WarlockPunchAir")
        string_0x131:; String.insert("Capsule")
        string_0x132:; String.insert("CapsuleAir")
        string_0x133:; String.insert("DSCharging")
        string_0x134:; String.insert("YLBoomerang")
        string_0x135:; String.insert("YLBoomerangAir")
        string_0x136:; String.insert("LucasPKFire")
        string_0x137:; String.insert("LucasPKFireAir")
        string_0x138:; String.insert("BodySlam")
        string_0x139:; String.insert("BodySlamAir")
        string_0x13A:; String.insert("BodySlamRecoil")
        string_0x13B:; String.insert("BodySlamRecoilAir")
        string_0x13C:; String.insert("Phantasm")
        string_0x13D:; String.insert("PhantasmAir")
        string_0x13E:; String.insert("FlameBreath")
        string_0x13F:; String.insert("FlameBreathAir")
        string_0x140:; String.insert("Book")
        string_0x141:; String.insert("BookAir")
        string_0x142:; String.insert("Blaster")
        string_0x143:; String.insert("BlasterAir")
        string_0x144:; String.insert("CatapultStart")
        string_0x145:; String.insert("CatapultCharge")
        string_0x146:; String.insert("CatapultShoot")
        string_0x147:; String.insert("CatapultStartAir")
        string_0x148:; String.insert("CatapultChargeAir")
        string_0x149:; String.insert("CatapultShootAir")
        string_0x14A:; String.insert("ShadowBallStart")
        string_0x14B:; String.insert("ShadowBallCharge")
        string_0x14C:; String.insert("ShadowBallShoot")
        string_0x14D:; String.insert("ShadowBallStartAir")
        string_0x14E:; String.insert("ShadowBallChargeAir")
        string_0x14F:; String.insert("ShadowBallShootAir")
        string_0x150:; String.insert("DancingBlade1")
        string_0x151:; String.insert("DancingBlade2High")
        string_0x152:; String.insert("DancingBlade2Mid")
        string_0x153:; String.insert("DancingBlade2Low")
        string_0x154:; String.insert("DancingBlade3High")
        string_0x155:; String.insert("DancingBlade3Mid")
        string_0x156:; String.insert("DancingBlade3Low")
        string_0x157:; String.insert("DancingBlade1Air")
        string_0x158:; String.insert("DancingBlade2HighAir")
        string_0x159:; String.insert("DancingBlade2MidAir")
        string_0x15A:; String.insert("DancingBlade2LowAir")
        string_0x15B:; String.insert("DancingBlade3HighAir")
        string_0x15C:; String.insert("DancingBlade3MidAir")
        string_0x15D:; String.insert("DancingBlade3LowAir")
        string_0x15E:; String.insert("HomingStart")
        string_0x15F:; String.insert("HomingMove")
        string_0x160:; String.insert("HomingLockedMove")
        string_0x161:; String.insert("HomingEndGround")
        string_0x162:; String.insert("HomingEndAir")
        string_0x163:; String.insert("HomingRecoilGround")
        string_0x164:; String.insert("HomingRecoilAir")
        string_0x165:; String.insert("HomingBounce")
        string_0x166:; String.insert("NeedleStormStartGround")
        string_0x167:; String.insert("NeedleStormChargeGround")
        string_0x168:; String.insert("NeedleStormShootGround")
        string_0x169:; String.insert("NeedleStormStartAir")
        string_0x16A:; String.insert("NeedleStormChargeAir")
        string_0x16B:; String.insert("NeedleStormShootAir")
        string_0x16C:; String.insert("InhaleBeginG")
        string_0x16D:; String.insert("InhaleLoopG")
        string_0x16E:; String.insert("InhalePullG")
        string_0x16F:; String.insert("InhaleSwallowG")
        string_0x170:; String.insert("InhaleIdleG")
        string_0x171:; String.insert("InhaleSpitG")
        string_0x172:; String.insert("InhaleTurnG")
        string_0x173:; String.insert("InhaleEndG")
        string_0x174:; String.insert("InhaleBeginA")
        string_0x175:; String.insert("InhaleLoopA")
        string_0x176:; String.insert("InhalePullA")
        string_0x177:; String.insert("InhaleSwallowA")
        string_0x178:; String.insert("InhaleFall")
        string_0x179:; String.insert("InhaleSpitA")
        string_0x17A:; String.insert("InhaleTurnA")
        string_0x17B:; String.insert("InhaleEndA")
        string_0x17C:; String.insert("DededeWalk1")
        string_0x17D:; String.insert("DededeWalk2")
        string_0x17E:; String.insert("DededeWalk3")
        string_0x17F:; String.insert("JetSnatchG")
        string_0x180:; String.insert("JetSnatchPullG")
        string_0x181:; String.insert("JetSnatchThrowG")
        string_0x182:; String.insert("JetSnatchThrowUG")
        string_0x183:; String.insert("JetSnatchThrowDG")
        string_0x184:; String.insert("JetSnatchA")
        string_0x185:; String.insert("JetSnatchPullA")
        string_0x186:; String.insert("JetSnatchThrowA")
        string_0x187:; String.insert("JetSnatchThrowUA")
        string_0x188:; String.insert("JetSnatchThrowDA")
        string_0x189:; String.insert("RyoTossGroundBegin")
        string_0x18A:; String.insert("RyoTossGroundWait")
        string_0x18B:; String.insert("RyoTossGroundWalk1")
        string_0x18C:; String.insert("RyoTossGroundWalk2")
        string_0x18D:; String.insert("RyoTossGroundBWalk1")
        string_0x18E:; String.insert("RyoTossGroundBWalk2")
        string_0x18F:; String.insert("RyoTossGroundEnd")
        string_0x190:; String.insert("RyoTossAirBegin")
        string_0x191:; String.insert("RyoTossAirIdle")
        string_0x192:; String.insert("RyoTossAirEnd")
        string_0x193:; String.insert("DemonSniper")
        string_0x194:; String.insert("DemonSniperAir")
        string_0x195:; String.insert("RevolverBeginGround")
        string_0x196:; String.insert("RevolverChargeGround")
        string_0x197:; String.insert("RevolverShootGround")
        string_0x198:; String.insert("RevolverBeginAir")
        string_0x199:; String.insert("RevolverChargeAir")
        string_0x19A:; String.insert("RevolverShootAir")
        string_0x19B:; String.insert("EggBeginGround")
        string_0x19C:; String.insert("FireEggGround")
        string_0x19D:; String.insert("EggBounceGround")
        string_0x19E:; String.insert("EggBeginAir")
        string_0x19F:; String.insert("FireEggAir")
        string_0x1A0:; String.insert("EggBounceAir")
        string_0x1A1:; String.insert("MeatSaw-HammerGroundBegin")
        string_0x1A2:; String.insert("MeatSaw-HammerGroundWait")
        string_0x1A3:; String.insert("MeatSaw-HammerGroundWalk1")
        string_0x1A4:; String.insert("MeatSaw-HammerGroundWalk2")
        string_0x1A5:; String.insert("MeatSaw-HammerGroundBWalk1")
        string_0x1A6:; String.insert("MeatSaw-HammerGroundBWalk2")
        string_0x1A7:; String.insert("MeatSaw-HammerGroundAttack")
        string_0x1A8:; String.insert("MeatSaw-HammerAirBegin")
        string_0x1A9:; String.insert("MeatSaw-HammerAirIdle")
        string_0x1AA:; String.insert("MeatSaw-HammerAirAttack")
        string_0x1AB:; String.insert("DragonBallGround")
        string_0x1AC:; String.insert("DragonBallAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
        dw string_0x0EE
        dw string_0x0EF
        dw string_0x0F0
        dw string_0x0F1
        dw string_0x0F2
        dw string_0x0F3
        dw string_0x0F4
        dw string_0x0F5
        dw string_0x0F6
        dw string_0x0F7
        dw string_0x0F8
        dw string_0x0F9
        dw string_0x0FA
        dw string_0x0FB
        dw string_0x0FC
        dw string_0x0FD
        dw string_0x0FE
        dw string_0x0FF
        dw string_0x100
        dw string_0x101
        dw string_0x102
        dw string_0x103
        dw string_0x104
        dw 0 // dw string_0x105
        dw string_0x106
        dw string_0x107
        dw string_0x108
        dw string_0x109
        dw string_0x10A
        dw string_0x10B
        dw string_0x10C
        dw string_0x10D
        dw string_0x10E
        dw string_0x10F
        dw string_0x110
        dw string_0x111
        dw string_0x112
        dw string_0x113
        dw string_0x114
        dw string_0x115
        dw string_0x116
        dw string_0x117
        dw string_0x118
        dw string_0x119
        dw string_0x11A
        dw string_0x11B
        dw string_0x11C
        dw string_0x11D
        dw string_0x11E
        dw string_0x11F
        dw string_0x120
        dw string_0x121
        dw string_0x122
        dw string_0x123
        dw string_0x124
        dw string_0x125
        dw string_0x126
        dw string_0x127
        dw string_0x128
        dw string_0x129
        dw string_0x12A
        dw string_0x12B
        dw string_0x12C
        dw string_0x12D
        dw string_0x12E
        dw string_0x12F
        dw string_0x130
        dw string_0x131
        dw string_0x132
        dw string_0x133
        dw string_0x134
        dw string_0x135
        dw string_0x136
        dw string_0x137
        dw string_0x138
        dw string_0x139
        dw string_0x13A
        dw string_0x13B
        dw string_0x13C
        dw string_0x13D
        dw string_0x13E
        dw string_0x13F
        dw string_0x140
        dw string_0x141
        dw string_0x142
        dw string_0x143
        dw string_0x144
        dw string_0x145
        dw string_0x146
        dw string_0x147
        dw string_0x148
        dw string_0x149
        dw string_0x14A
        dw string_0x14B
        dw string_0x14C
        dw string_0x14D
        dw string_0x14E
        dw string_0x14F
        dw string_0x150
        dw string_0x151
        dw string_0x152
        dw string_0x153
        dw string_0x154
        dw string_0x155
        dw string_0x156
        dw string_0x157
        dw string_0x158
        dw string_0x159
        dw string_0x15A
        dw string_0x15B
        dw string_0x15C
        dw string_0x15D
        dw string_0x15E
        dw string_0x15F
        dw string_0x160
        dw string_0x161
        dw string_0x162
        dw string_0x163
        dw string_0x164
        dw string_0x165
        dw string_0x166
        dw string_0x167
        dw string_0x168
        dw string_0x169
        dw string_0x16A
        dw string_0x16B
        dw string_0x16C
		dw string_0x16D
		dw string_0x16E
		dw string_0x16F
		dw string_0x170
		dw string_0x171
		dw string_0x172
		dw string_0x173
		dw string_0x174
		dw string_0x175
		dw string_0x176
		dw string_0x177
		dw string_0x178
		dw string_0x179
		dw string_0x17A
		dw string_0x17B
		dw string_0x17C
		dw string_0x17D
		dw string_0x17E
        dw string_0x17F
        dw string_0x180
        dw string_0x181
        dw string_0x182
        dw string_0x183
        dw string_0x184
        dw string_0x185
        dw string_0x186
        dw string_0x187
        dw string_0x188
        dw string_0x189
        dw string_0x18A
        dw string_0x18B
        dw string_0x18C
        dw string_0x18D
        dw string_0x18E
        dw string_0x18F
        dw string_0x190
        dw string_0x191
        dw string_0x192
        dw string_0x193
        dw string_0x194
        dw string_0x195
        dw string_0x196
        dw string_0x197
        dw string_0x198
        dw string_0x199
        dw string_0x19A
        dw string_0x19B
        dw string_0x19C
        dw string_0x19E
        dw string_0x19D
        dw string_0x19F
        dw string_0x1A0
        dw string_0x1A1
        dw string_0x1A2
        dw string_0x1A3
        dw string_0x1A4
        dw string_0x1A5
        dw string_0x1A6
        dw string_0x1A7
        dw string_0x1A8
        dw string_0x1A9
        dw string_0x1AA
        dw string_0x1AB
        dw string_0x1AC
    }

    // @ Description
    // Pikachu's extra actions
    scope PIKACHU {
        constant Appear1(0x0DC)
        constant Appear2(0x0DD)
        constant ThunderJolt(0x0DE)
        constant ThunderJoltAir(0x0DF)
        constant ThunderStart(0x0E0)
        constant Thunder(0x0E1)
        constant ThunderHit(0x0E2)
        constant ThunderEnd(0x0E3)
        constant ThunderStartAir(0x0E4)
        constant ThunderAir(0x0E5)
        constant ThunderHitAir(0x0E6)
        constant ThunderEndAir(0x0E7)
        constant QuickAttackStart(0x0E8)
        constant QuickAttack(0x0E9)
        constant QuickAttackEnd(0x0EA)
        constant QuickAttackStartAir(0x0EB)
        constant QuickAttackAir(0x0EC)
        constant QuickAttackEndAir(0x0ED)

        // strings!
        string_0x0DC:; String.insert("Appear1")
        string_0x0DD:; String.insert("Appear2")
        string_0x0DE:; String.insert("ThunderJolt")
        string_0x0DF:; String.insert("ThunderJoltAir")
        string_0x0E0:; String.insert("ThunderStart")
        string_0x0E1:; String.insert("Thunder")
        string_0x0E2:; String.insert("ThunderHit")
        string_0x0E3:; String.insert("ThunderEnd")
        string_0x0E4:; String.insert("ThunderStartAir")
        string_0x0E5:; String.insert("ThunderAir")
        string_0x0E6:; String.insert("ThunderHitAir")
        string_0x0E7:; String.insert("ThunderEndAir")
        string_0x0E8:; String.insert("QuickAttackStart")
        string_0x0E9:; String.insert("QuickAttack")
        string_0x0EA:; String.insert("QuickAttackEnd")
        string_0x0EB:; String.insert("QuickAttackStartAir")
        string_0x0EC:; String.insert("QuickAttackAir")
        string_0x0ED:; String.insert("QuickAttackEndAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
    }

    // @ Description
    // Jiggly's extra actions
    scope JIGGLY {
        constant JabLoopStart(0x0DC)   // unused
        constant JabLoop(0x0DD)        // unused
        constant JabLoopEnd(0x0DE)     // unused
        constant Jump2(0x0DF)
        constant Jump3(0x0E0)
        constant Jump4(0x0E1)
        constant Jump5(0x0E2)
        constant Jump6(0x0E3)
        constant Appear1(0x0E4)
        constant Appear2(0x0E5)
        constant Pound(0x0E6)
        constant PoundAir(0x0E7)
        constant Sing(0x0E8)
        constant SingAir(0x0E9)
        constant Rest(0x0EA)
        constant RestAir(0x0EB)
        //constant ?(0x0EC)
        //constant ?(0x0ED)

        // strings!
        //string_0x0DC:; String.insert("JabLoopStart")
        //string_0x0DD:; String.insert("JabLoop")
        //string_0x0DE:; String.insert("JabLoopEnd")
        string_0x0DF:; String.insert("Jump2")
        string_0x0E0:; String.insert("Jump3")
        string_0x0E1:; String.insert("Jump4")
        string_0x0E2:; String.insert("Jump5")
        string_0x0E3:; String.insert("Jump6")
        string_0x0E4:; String.insert("Appear1")
        string_0x0E5:; String.insert("Appear2")
        string_0x0E6:; String.insert("Pound")
        string_0x0E7:; String.insert("PoundAir")
        string_0x0E8:; String.insert("Sing")
        string_0x0E9:; String.insert("SingAir")
        string_0x0EA:; String.insert("Rest")
        string_0x0EB:; String.insert("RestAir")
        //string_0x0EC:; String.insert("?")
        //string_0x0ED:; String.insert("?")

        action_string_table:
        dw 0 //dw string_0x0DC
        dw 0 //dw string_0x0DD
        dw 0 //dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw 0 //dw string_0x0EC
        dw 0 //dw string_0x0ED
    }

    // @ Description
    // Ness's extra actions
    scope NESS {
        constant Jab3(0x0DC)
        constant AppearStart1(0x0DD)
        constant AppearStart2(0x0DE)
        constant Appear1(0x0DF)
        constant Appear2(0x0E0)
        constant AppearEnd(0x0E1)
        constant PKFire(0x0E2)
        constant PKFireAir(0x0E3)
        constant PKThunderStart1(0x0E4)
        constant PKThunderStart2(0x0E5)
        constant PKThunderEnd(0x0E6)
        constant PKTA(0x0E7)
        constant PKThunderStartAir(0x0E8)
        constant PKThunderAir(0x0E9)
        constant PKThunderEndAir(0x0EA)
        constant ClashingPKTA(0x0EB)
        constant PKTAAir(0x0EC)
        constant PsiMagnetStart(0x0ED)
        constant PsiMagnet(0x0EE)
        constant Healing(0x0EF)
        constant PsiMagnetEnd(0x0F0)
        constant PsiMagnetStartAir(0x0F1)
        constant PsiMagnetAir(0x0F2)
        constant HealingAir(0x0F3)
        constant PsiMagnetEndAir(0x0F4)

        // strings!
        string_0x0DC:; String.insert("Jab3")
        string_0x0DD:; String.insert("AppearStart1")
        string_0x0DE:; String.insert("AppearStart2")
        string_0x0DF:; String.insert("Appear1")
        string_0x0E0:; String.insert("Appear2")
        string_0x0E1:; String.insert("AppearEnd")
        string_0x0E2:; String.insert("PKFire")
        string_0x0E3:; String.insert("PKFireAir")
        string_0x0E4:; String.insert("PKThunderStart1")
        string_0x0E5:; String.insert("PKThunderStart2")
        string_0x0E6:; String.insert("PKThunderEnd")
        string_0x0E7:; String.insert("PKTA")
        string_0x0E8:; String.insert("PKThunderStartAir")
        string_0x0E9:; String.insert("PKThunderAir")
        string_0x0EA:; String.insert("PKThunderEndAir")
        string_0x0EB:; String.insert("ClashingPKTA")
        string_0x0EC:; String.insert("PKTAAir")
        string_0x0ED:; String.insert("PsiMagnetStart")
        string_0x0EE:; String.insert("PsiMagnet")
        string_0x0EF:; String.insert("Healing")
        string_0x0F0:; String.insert("PsiMagnetEnd")
        string_0x0F1:; String.insert("PsiMagnetStartAir")
        string_0x0F2:; String.insert("PsiMagnetAir")
        string_0x0F3:; String.insert("HealingAir")
        string_0x0F4:; String.insert("PsiMagnetEndAir")

        action_string_table:
        dw string_0x0DC
        dw string_0x0DD
        dw string_0x0DE
        dw string_0x0DF
        dw string_0x0E0
        dw string_0x0E1
        dw string_0x0E2
        dw string_0x0E3
        dw string_0x0E4
        dw string_0x0E5
        dw string_0x0E6
        dw string_0x0E7
        dw string_0x0E8
        dw string_0x0E9
        dw string_0x0EA
        dw string_0x0EB
        dw string_0x0EC
        dw string_0x0ED
        dw string_0x0EE
        dw string_0x0EF
        dw string_0x0F0
        dw string_0x0F1
        dw string_0x0F2
        dw string_0x0F3
        dw string_0x0F4
    }

    // @ Description
    // Basic action change routine
    // a0 must be player object
    // action_id - action to change to
    // fsm - frame speed multiplier. default = 0x3F80 (float 1.0)
    macro change(action_id, fsm) {
        lli     a1, {action_id}             // a1(action id) = action_id
        or      a2, r0, r0                  // a2(starting frame) = 0
        if {fsm} != -1 {
            lui     a3, {fsm}               // a3(frame speed multiplier) = 1.0
        } else {
            lui     a3, 0x3F80              // a3(frame speed multiplier) = 1.0
        }
        jal     0x800E6F24                  // change action
        sw      r0, 0x0010(sp)              // argument 4 = 0
    }

}
