// Color.asm (generated by color.c)
if !{defined __COLOR__} {
define __COLOR__()
print "included Color.asm\n"

// @ Description
// This file contains color constants.

scope Color {

    constant RED(0xF801)
    constant ORANGE(0xFD01)
    constant YELLOW(0xFFC1)
    constant GREEN(0x0401)
    constant BLUE(0x003F)
    constant PURPLE(0x8021)
    constant PINK(0xFE33)
    constant BROWN(0xA14B)
    constant BLACK(0x0001)
    constant GREY(0x8421)
    constant WHITE(0xFFFF)

    scope low {
        constant RED(0xF801)
        constant ORANGE(0xFD01)
        constant YELLOW(0xFFC1)
        constant GREEN(0x07C1)
        constant BLUE(0x003F)
        constant PURPLE(0x8021)
        constant PINK(0xFE33)
        constant BROWN(0xA14B)
        constant BLACK(0x0001)
        constant GREY(0x8421)
        constant WHITE(0xFFFF)
        constant MENU_BG(0x2993)
    }

    scope high {
        constant RED(0xFF0000FF)
        constant ORANGE(0xFFA500FF)
        constant YELLOW(0xFFFF00FF)
        constant GREEN(0x00FF00FF)
        constant BLUE(0x0000FFFF)
        constant PURPLE(0x800080FF)
        constant PINK(0xFFC0CBFF)
        constant BROWN(0xA52A2AFF)
        constant BLACK(0x000000FF)
        constant GREY(0x808080FF)
        constant WHITE(0xFFFFFFFF)
    }
}

} // __COLOR__