name: Run tests

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  check-sequential-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run sequential branches check
      run: |
        python scripts/test/sequential_branches.py

  check-duplicate-action-edit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run duplicate action edit check
      run: |
        python scripts/test/check_duplicate_action_edit.py