// Peach.asm

// This file contains file inclusions, action edits, and assembly for NPeach.

scope NPeach {

    // Modify Action Parameters             // Action                       // Animation                    // Moveset Data                 // Flags
    Character.edit_action_parameters(NPEACH, Action.DeadU,                   File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ScreenKO,                File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Entry,                   File.PEACH_IDLE,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, 0x006,                          File.PEACH_IDLE,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Revive1,                 File.PEACH_DOWN_BOUNCE_D,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Revive2,                 File.PEACH_DOWN_STAND_D,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ReviveWait,              File.PEACH_IDLE,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Idle,                    File.PEACH_IDLE,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Walk1,                   File.PEACH_WALK1,               -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Walk2,                   File.PEACH_WALK2,               -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Walk3,                   File.PEACH_WALK3,               -1,                               -1)
    Character.edit_action_parameters(NPEACH, 0x00E,                          File.PEACH_TEETER_START,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Dash,                    File.PEACH_DASH,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Run,                     File.PEACH_RUN,                 Peach.RUN,                        -1)
    Character.edit_action_parameters(NPEACH, Action.RunBrake,                File.PEACH_RUN_BRAKE,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Turn,                    File.PEACH_TURN,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.TurnRun,                 File.PEACH_TURN_RUN,            -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.JumpSquat,               File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldJumpSquat,         File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.JumpF,                   File.PEACH_JUMP_F,              Peach.JUMP_1,                     -1)
    Character.edit_action_parameters(NPEACH, Action.JumpB,                   File.PEACH_JUMP_B,              Peach.JUMP_1,                     -1)
    Character.edit_action_parameters(NPEACH, Action.JumpAerialF,             File.PEACH_JUMP_AERIAL_F,       Peach.JUMP_2,                     0x40000000)
    Character.edit_action_parameters(NPEACH, Action.JumpAerialB,             File.PEACH_JUMP_AERIAL_B,       Peach.JUMP_2,                     0x40000000)
    Character.edit_action_parameters(NPEACH, Action.Fall,                    File.PEACH_FALL,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.FallAerial,              File.PEACH_FALL_AERIAL,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Crouch,                  File.PEACH_CROUCH,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CrouchIdle,              File.PEACH_CROUCH_IDLE,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CrouchEnd,               File.PEACH_CROUCH_END,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LandingLight,            File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LandingHeavy,            File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Pass,                    File.PEACH_PLAT_DROP,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldDrop,              File.PEACH_PLAT_DROP,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Teeter,                  File.PEACH_TEETER,              Peach.TEETER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.TeeterStart,             File.PEACH_TEETER_START,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageHigh1,             File.PEACH_DAMAGE_HIGH1,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageHigh2,             File.PEACH_DAMAGE_HIGH2,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageHigh3,             File.PEACH_DAMAGE_HIGH3,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageMid1,              File.PEACH_DAMAGE_MID1,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageMid2,              File.PEACH_DAMAGE_MID2,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageMid3,              File.PEACH_DAMAGE_MID3,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageLow1,              File.PEACH_DAMAGE_LOW1,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageLow2,              File.PEACH_DAMAGE_LOW2,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageLow3,              File.PEACH_DAMAGE_LOW3,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageAir1,              File.PEACH_DAMAGE_AIR1,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageAir2,              File.PEACH_DAMAGE_AIR2,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageAir3,              File.PEACH_DAMAGE_AIR3,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageElec1,             File.PEACH_DAMAGE_ELEC,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageElec2,             File.PEACH_DAMAGE_ELEC,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageFlyHigh,           File.PEACH_DAMAGE_FLY_HIGH,     -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageFlyMid,            File.PEACH_DAMAGE_FLY_MID,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageFlyLow,            File.PEACH_DAMAGE_FLY_LOW,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageFlyTop,            File.PEACH_DAMAGE_FLY_TOP,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DamageFlyRoll,           File.PEACH_DAMAGE_FLY_ROLL,     -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.WallBounce,              File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Tumble,                  File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.FallSpecial,             File.PEACH_FALL_SPECIAL,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LandingSpecial,          File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Tornado,                 File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.EnterPipe,               File.PEACH_ENTER_PIPE,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ExitPipe,                File.PEACH_EXIT_PIPE,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ExitPipeWalk,            File.PEACH_EXIT_PIPE_WALK,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CeilingBonk,             File.PEACH_CEILING_BONK,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownBounceD,             File.PEACH_DOWN_BOUNCE_D,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownBounceU,             File.PEACH_DOWN_BOUNCE_U,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownStandD,              File.PEACH_DOWN_STAND_D,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownStandU,              File.PEACH_DOWN_STAND_U,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.TechF,                   File.PEACH_TECH_F,              Peach.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NPEACH, Action.TechB,                   File.PEACH_TECH_B,              Peach.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NPEACH, Action.DownForwardD,            File.PEACH_DOWN_FORWARD_D,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownForwardU,            File.PEACH_DOWN_FORWARD_U,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownBackD,               File.PEACH_DOWN_BACK_D,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownBackU,               File.PEACH_DOWN_BACK_U,         -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.DownAttackD,             File.PEACH_DOWN_ATK_D,          Peach.DOWN_ATTACK_D,              -1)
    Character.edit_action_parameters(NPEACH, Action.DownAttackU,             File.PEACH_DOWN_ATK_U,          Peach.DOWN_ATTACK_U,              -1)
    Character.edit_action_parameters(NPEACH, Action.Tech,                    File.PEACH_TECH,                Peach.TECH_STAND,                 -1)
    Character.edit_action_parameters(NPEACH, Action.ClangRecoil,             File.PEACH_CLANG_RECOIL,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffCatch,              File.PEACH_CLF_CATCH,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffWait,               File.PEACH_CLF_WAIT,            -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffQuick,              File.PEACH_CLF_Q,               -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffClimbQuick1,        File.PEACH_CLF_CLM_Q1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffClimbQuick2,        File.PEACH_CLF_CLM_Q2,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffSlow,               File.PEACH_CLF_S,               -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffClimbSlow1,         File.PEACH_CLF_CLM_S1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffClimbSlow2,         File.PEACH_CLF_CLM_S2,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffAttackQuick1,       File.PEACH_CLF_ATK_Q1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffAttackQuick2,       File.PEACH_CLF_ATK_Q2,          Peach.EDGE_ATTACK_QUICK_2,        -1)
    Character.edit_action_parameters(NPEACH, Action.CliffAttackSlow1,        File.PEACH_CLF_ATK_S1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffAttackSlow2,        File.PEACH_CLF_ATK_S2,          Peach.EDGE_ATTACK_SLOW_2,         -1)
    Character.edit_action_parameters(NPEACH, Action.CliffEscapeQuick1,       File.PEACH_CLF_ESC_Q1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffEscapeQuick2,       File.PEACH_CLF_ESC_Q2,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffEscapeSlow1,        File.PEACH_CLF_ESC_S1,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.CliffEscapeSlow2,        File.PEACH_CLF_ESC_S2,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LightItemPickup,         File.PEACH_L_ITM_PICKUP,        Peach.LIGHT_ITEM_PICKUP,          -1)
    Character.edit_action_parameters(NPEACH, Action.HeavyItemPickup,         File.PEACH_H_ITM_PICKUP,        Peach.HEAVY_ITEM_PICKUP,          -1)
    Character.edit_action_parameters(NPEACH, Action.ItemDrop,                File.PEACH_ITM_DROP,            Peach.ITEM_DROP,                  -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowDash,           File.PEACH_ITM_THROW_DASH,      Peach.ITEM_THROW_DASH,            -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowF,              File.PEACH_ITM_THROW_F,         Peach.ITEM_THROW_F,               -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowB,              File.PEACH_ITM_THROW_F,         Peach.ITEM_THROW_B,               -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowU,              File.PEACH_ITM_THROW_U,         Peach.ITEM_THROW_U,               -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowD,              File.PEACH_ITM_THROW_D,         Peach.ITEM_THROW_D,               -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowSmashF,         File.PEACH_ITM_THROW_F,         Peach.ITEM_THROW_SMASH_F,         -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowSmashB,         File.PEACH_ITM_THROW_F,         Peach.ITEM_THROW_SMASH_B,         -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowSmashU,         File.PEACH_ITM_THROW_U,         Peach.ITEM_THROW_SMASH_U,         -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowSmashD,         File.PEACH_ITM_THROW_D,         Peach.ITEM_THROW_SMASH_D,         -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirF,           File.PEACH_ITM_THROW_AIR_F,     Peach.ITEM_THROW_AIR_F,           -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirB,           File.PEACH_ITM_THROW_AIR_F,     Peach.ITEM_THROW_AIR_B,           -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirU,           File.PEACH_ITM_THROW_AIR_U,     Peach.ITEM_THROW_AIR_U,           -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirD,           File.PEACH_ITM_THROW_AIR_D,     Peach.ITEM_THROW_AIR_D,           -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirSmashF,      File.PEACH_ITM_THROW_AIR_F,     Peach.ITEM_THROW_AIR_SMASH_F,     -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirSmashB,      File.PEACH_ITM_THROW_AIR_F,     Peach.ITEM_THROW_AIR_SMASH_B,     -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirSmashU,      File.PEACH_ITM_THROW_AIR_U,     Peach.ITEM_THROW_AIR_SMASH_U,     -1)
    Character.edit_action_parameters(NPEACH, Action.ItemThrowAirSmashD,      File.PEACH_ITM_THROW_AIR_D,     Peach.ITEM_THROW_AIR_SMASH_D,     -1)
    Character.edit_action_parameters(NPEACH, Action.HeavyItemThrowF,         File.PEACH_H_ITM_THROW,         Peach.HEAVY_ITEM_THROW_F,         -1)
    Character.edit_action_parameters(NPEACH, Action.HeavyItemThrowB,         File.PEACH_H_ITM_THROW,         Peach.HEAVY_ITEM_THROW_B,         -1)
    Character.edit_action_parameters(NPEACH, Action.HeavyItemThrowSmashF,    File.PEACH_H_ITM_THROW,         Peach.HEAVY_ITEM_THROW_SMASH_F,   -1)
    Character.edit_action_parameters(NPEACH, Action.HeavyItemThrowSmashB,    File.PEACH_H_ITM_THROW,         Peach.HEAVY_ITEM_THROW_SMASH_B,   -1)
    Character.edit_action_parameters(NPEACH, Action.BeamSwordNeutral,        File.PEACH_ITM_JAB,             Peach.BEAMSWORD_JAB,              -1)
    Character.edit_action_parameters(NPEACH, Action.BeamSwordTilt,           File.PEACH_ITM_TILT,            Peach.BEAMSWORD_TILT,             -1)
    Character.edit_action_parameters(NPEACH, Action.BeamSwordSmash,          File.PEACH_ITM_SMASH,           Peach.BEAMSWORD_SMASH,            -1)
    Character.edit_action_parameters(NPEACH, Action.BeamSwordDash,           File.PEACH_ITM_DASH,            Peach.BEAMSWORD_DASH,             -1)
    Character.edit_action_parameters(NPEACH, Action.BatNeutral,              File.PEACH_ITM_JAB,             Peach.BAT_JAB,                    -1)
    Character.edit_action_parameters(NPEACH, Action.BatTilt,                 File.PEACH_ITM_TILT,            Peach.BAT_TILT,                   -1)
    Character.edit_action_parameters(NPEACH, Action.BatSmash,                File.PEACH_ITM_SMASH,           Peach.BAT_SMASH,                  -1)
    Character.edit_action_parameters(NPEACH, Action.BatDash,                 File.PEACH_ITM_DASH,            Peach.BAT_DASH,                   -1)
    Character.edit_action_parameters(NPEACH, Action.FanNeutral,              File.PEACH_ITM_JAB,             Peach.FAN_JAB,                    -1)
    Character.edit_action_parameters(NPEACH, Action.FanTilt,                 File.PEACH_ITM_TILT,            Peach.FAN_TILT,                   -1)
    Character.edit_action_parameters(NPEACH, Action.FanSmash,                File.PEACH_ITM_SMASH,           Peach.FAN_SMASH,                  -1)
    Character.edit_action_parameters(NPEACH, Action.FanDash,                 File.PEACH_ITM_DASH,            Peach.FAN_DASH,                   -1)
    Character.edit_action_parameters(NPEACH, Action.StarRodNeutral,          File.PEACH_ITM_JAB,             Peach.STARROD_JAB,                -1)
    Character.edit_action_parameters(NPEACH, Action.StarRodTilt,             File.PEACH_ITM_TILT,            Peach.STARROD_TILT,               -1)
    Character.edit_action_parameters(NPEACH, Action.StarRodSmash,            File.PEACH_ITM_SMASH,           Peach.STARROD_SMASH,              -1)
    Character.edit_action_parameters(NPEACH, Action.StarRodDash,             File.PEACH_ITM_DASH,            Peach.STARROD_DASH,               -1)
    Character.edit_action_parameters(NPEACH, Action.RayGunShoot,             File.PEACH_ITM_SHOOT,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.RayGunShootAir,          File.PEACH_ITM_SHOOT_AIR,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.FireFlowerShoot,         File.PEACH_ITM_SHOOT,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.FireFlowerShootAir,      File.PEACH_ITM_SHOOT_AIR,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.HammerIdle,              File.PEACH_HAMMER_IDLE,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.HammerWalk,              File.PEACH_HAMMER_WALK,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.HammerTurn,              File.PEACH_HAMMER_WALK,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.HammerJumpSquat,         File.PEACH_HAMMER_WALK,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.HammerAir,               File.PEACH_HAMMER_WALK,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.HammerLanding,           File.PEACH_HAMMER_WALK,         Peach.HAMMER,                     -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldOn,                File.PEACH_SHIELD_ON,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldOff,               File.PEACH_SHIELD_OFF,          -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.RollF,                   File.PEACH_ROLL_F,              Peach.FROLL,                      -1)
    Character.edit_action_parameters(NPEACH, Action.RollB,                   File.PEACH_ROLL_B,              Peach.BROLL,                      -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldBreak,             File.PEACH_DAMAGE_FLY_TOP,      Peach.SHIELD_BREAK,               -1)
    Character.edit_action_parameters(NPEACH, Action.ShieldBreakFall,         File.PEACH_TUMBLE,              Peach.SPARKLE,                    -1)
    Character.edit_action_parameters(NPEACH, Action.StunLandD,               File.PEACH_DOWN_BOUNCE_D,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.StunLandU,               File.PEACH_DOWN_BOUNCE_U,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.StunStartD,              File.PEACH_DOWN_STAND_D,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.StunStartU,              File.PEACH_DOWN_STAND_U,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Stun,                    File.PEACH_STUN,                Peach.STUN,                       -1)
    Character.edit_action_parameters(NPEACH, Action.Sleep,                   File.PEACH_STUN,                Peach.ASLEEP,                     -1)
    Character.edit_action_parameters(NPEACH, Action.Grab,                    File.PEACH_GRAB,                Peach.GRAB,                       -1)
    Character.edit_action_parameters(NPEACH, Action.GrabPull,                File.PEACH_GRAB_PULL,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ThrowF,                  File.PEACH_THROW_F,             Peach.THROW_F,                    -1)
    Character.edit_action_parameters(NPEACH, Action.ThrowB,                  File.PEACH_THROW_B,             Peach.THROW_B,                    -1)
    Character.edit_action_parameters(NPEACH, Action.CapturePulled,           File.PEACH_CAPTURE_PULLED,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.InhalePulled,            File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.InhaleSpat,              File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.InhaleCopied,            File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.EggLayPulled,            File.PEACH_CAPTURE_PULLED,      -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.EggLay,                  File.PEACH_IDLE,                -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.FalconDivePulled,        File.PEACH_DAMAGE_HIGH3,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, 0x0B4,                          File.PEACH_TUMBLE,              -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ThrownDKPulled,          File.PEACH_THROWN_DK_PULLED,    -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ThrownMarioBros,         File.PEACH_THROWN_MARIO_BROS,   -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ThrownDK,                File.PEACH_THROWN_DK,           -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Thrown1,                 File.PEACH_THROWN1,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Thrown2,                 File.PEACH_THROWN2,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Thrown3,                 File.PEACH_THROWN3,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.ThrownFoxB,              File.PEACH_THROWN_FOX_B,        -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.Taunt,                   File.PEACH_TAUNT,               Peach.TAUNT,                      -1)
    Character.edit_action_parameters(NPEACH, Action.Jab1,                    File.PEACH_JAB1,                Peach.JAB1,                       -1)
    Character.edit_action_parameters(NPEACH, Action.Jab2,                    File.PEACH_JAB2,                Peach.JAB2,                       -1)
    Character.edit_action_parameters(NPEACH, Action.DashAttack,              File.PEACH_DASH_ATTACK,         Peach.DASHATTACK,                 -1)
    Character.edit_action_parameters(NPEACH, Action.FTiltHigh,               0,                              0x80000000,                       -1)
    Character.edit_action_parameters(NPEACH, Action.FTiltMidHigh,            0,                              0x80000000,                       -1)
    Character.edit_action_parameters(NPEACH, Action.FTilt,                   File.PEACH_F_TILT,              Peach.FTILT,                      -1)
    Character.edit_action_parameters(NPEACH, Action.FTiltMidLow,             0,                              0x80000000,                       -1)
    Character.edit_action_parameters(NPEACH, Action.FTiltLow,                0,                              0x80000000,                       -1)
    Character.edit_action_parameters(NPEACH, Action.UTilt,                   File.PEACH_U_TILT,              Peach.UTILT,                      -1)
    Character.edit_action_parameters(NPEACH, Action.DTilt,                   File.PEACH_D_TILT,              Peach.DTILT,                      -1)
    Character.edit_action_parameters(NPEACH, Action.FSmashHigh,              File.PEACH_F_SMASH,             Peach.FSMASH_HIGH,                 0)
    Character.edit_action_parameters(NPEACH, Action.FSmashMidHigh,           File.PEACH_F_SMASH,             Peach.FSMASH_HIGH,                 0)
    Character.edit_action_parameters(NPEACH, Action.FSmash,                  File.PEACH_F_SMASH,             Peach.FSMASH,                      0)
    Character.edit_action_parameters(NPEACH, Action.FSmashMidLow,            File.PEACH_F_SMASH,             Peach.FSMASH_LOW,                  0)
    Character.edit_action_parameters(NPEACH, Action.FSmashLow,               File.PEACH_F_SMASH,             Peach.FSMASH_LOW,                  0)
    Character.edit_action_parameters(NPEACH, Action.USmash,                  File.PEACH_U_SMASH,             Peach.USMASH,                     -1)
    Character.edit_action_parameters(NPEACH, Action.DSmash,                  File.PEACH_D_SMASH,             Peach.DSMASH,                     -1)
    Character.edit_action_parameters(NPEACH, Action.AttackAirN,              File.PEACH_ATTACK_AIR_N,        Peach.NAIR,                       -1)
    Character.edit_action_parameters(NPEACH, Action.AttackAirF,              File.PEACH_ATTACK_AIR_F,        Peach.FAIR,                       -1)
    Character.edit_action_parameters(NPEACH, Action.AttackAirB,              File.PEACH_ATTACK_AIR_B,        Peach.BAIR,                       -1)
    Character.edit_action_parameters(NPEACH, Action.AttackAirU,              File.PEACH_ATTACK_AIR_U,        Peach.UAIR,                       -1)
    Character.edit_action_parameters(NPEACH, Action.AttackAirD,              File.PEACH_ATTACK_AIR_D,        Peach.DAIR,                       -1)
    Character.edit_action_parameters(NPEACH, Action.LandingAirF,             File.PEACH_LANDING_AIR_F,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LandingAirB,             File.PEACH_LANDING_AIR_B,       -1,                               -1)
    Character.edit_action_parameters(NPEACH, Action.LandingAirX,             File.PEACH_LANDING,             -1,                               -1)
    Character.edit_action_parameters(NPEACH, Peach.Action.EntryL,            File.PEACH_IDLE,                0x80000000,                       0)
    Character.edit_action_parameters(NPEACH, Peach.Action.EntryR,            File.PEACH_IDLE,                0x80000000,                       0)
    Character.edit_action_parameters(NPEACH, Peach.Action.Float,             File.PEACH_FLOAT,               Peach.FLOAT,                      0)
    Character.edit_action_parameters(NPEACH, Peach.Action.NSPG,              File.PEACH_NSP_G,               Peach.NSP,                        0)
    Character.edit_action_parameters(NPEACH, Peach.Action.NSPA,              File.PEACH_NSP_A,               Peach.NSP,                        0)
    Character.edit_action_parameters(NPEACH, Peach.Action.NSPRecoil,         File.PEACH_NSP_RECOIL,          Peach.NSP_RECOIL,                 0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPG,              File.PEACH_USPG,                Peach.USP,                        0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPA,              File.PEACH_USPA,                Peach.USP,                        0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPOpen,           File.PEACH_USP_OPEN,            Peach.USP_OPEN,                   0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPFloat,          File.PEACH_USP_FLOAT,           Peach.USP_FLOAT,                  0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPClose,          File.PEACH_USP_CLOSE,           Peach.USP_CLOSE,                  0)
    Character.edit_action_parameters(NPEACH, Peach.Action.USPFall,           File.PEACH_FALL_SPECIAL,        Peach.USP_FALL,                   0)
    Character.edit_action_parameters(NPEACH, Peach.Action.DSPPull,           File.PEACH_TURNIPPULL,          Peach.DSP,                       -1)

    // Modify Actions             // Action                // Staling ID   // Main ASM                 // Interrupt/Other ASM          // Movement/Physics ASM         // Collision ASM
    Character.edit_action(NPEACH, Peach.Action.EntryL,     -1,             0x8013D994,                 0,                              0,                              0)
    Character.edit_action(NPEACH, Peach.Action.EntryR,     -1,             0x8013D994,                 0,                              0,                              0)
    Character.edit_action(NPEACH, Peach.Action.Float,      0,              PeachFloat.main_,           PeachFloat.interrupt_,          0x800D9160,                     0x800DE99C)
    Character.edit_action(NPEACH, Peach.Action.NSPG,       0x12,           0x800D94C4,                 0,                              PeachNSP.ground_physics_,       PeachNSP.ground_collision_)
    Character.edit_action(NPEACH, Peach.Action.NSPA,       0x12,           0x800D94E8,                 0,                              PeachNSP.air_physics_,          PeachNSP.air_collision_)
    Character.edit_action(NPEACH, Peach.Action.NSPRecoil,  0x12,           0x800D94E8,                 0,                              0x800D91EC,                     0x800DE99C)
    Character.edit_action(NPEACH, Peach.Action.USPG,       0x11,           PeachUSP.main_,             PeachUSP.change_direction_,     PeachUSP.physics_,              PeachUSP.collision_)
    Character.edit_action(NPEACH, Peach.Action.USPA,       0x11,           PeachUSP.main_,             PeachUSP.change_direction_,     PeachUSP.physics_,              PeachUSP.collision_)
    Character.edit_action(NPEACH, Peach.Action.USPOpen,    0x11,           PeachUSP.open_main_,        0,                              PeachUSP.float_physics_,        PeachUSP.collision_)
    Character.edit_action(NPEACH, Peach.Action.USPFloat,   0x11,           0,                          PeachUSP.float_interrupt_,      PeachUSP.float_physics_,        PeachUSP.collision_)
    Character.edit_action(NPEACH, Peach.Action.USPClose,   0x11,           PeachUSP.close_main_,       0,                              0x800D9160,                     PeachUSP.collision_)
    Character.edit_action(NPEACH, Peach.Action.USPFall,    0x11,           0,                          PeachUSP.fall_interrupt_,       0x80143750,                     0x8014384C)
    Character.edit_action(NPEACH, Peach.Action.DSPPull,    0x1E,           PeachDSP.main,              0,                              0x800D8BB4,                     0x800DDF44)

    // Modify Menu Action Parameters              // Action // Animation                // Moveset Data             // Flags
    Character.edit_menu_action_parameters(NPEACH,  0x0,      File.PEACH_IDLE,            -1,                         -1)
    Character.edit_menu_action_parameters(NPEACH,  0x1,      File.PEACH_VICTORY1,        Peach.VICTORY1,             -1)
    Character.edit_menu_action_parameters(NPEACH,  0x2,      File.PEACH_VICTORY2,        Peach.VICTORY2,             -1)
    Character.edit_menu_action_parameters(NPEACH,  0x3,      File.PEACH_VICTORY3,        0x80000000,                 -1)
    Character.edit_menu_action_parameters(NPEACH,  0x4,      File.PEACH_VICTORY3,        0x80000000,                 -1)
    Character.edit_menu_action_parameters(NPEACH,  0x5,      File.PEACH_CLAP,            0x80000000,                 -1)
    Character.edit_menu_action_parameters(NPEACH,  0x9,      File.PEACH_CONTINUE_FALL,   -1,                         -1)
    Character.edit_menu_action_parameters(NPEACH,  0xA,      File.PEACH_CONTINUE_UP,     -1,                         -1)
    Character.edit_menu_action_parameters(NPEACH,  0xD,      File.PEACH_1P_POSE,         -1,                         -1)
    Character.edit_menu_action_parameters(NPEACH,  0xE,      File.PEACH_CPU_POSE,        -1,                         -1)

    Character.table_patch_start(air_usp, Character.id.NPEACH, 0x4)
    dw      PeachUSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_usp, Character.id.NPEACH, 0x4)
    dw      PeachUSP.ground_initial_
    OS.patch_end()
    Character.table_patch_start(air_dsp, Character.id.NPEACH, 0x4)
    dw      PeachDSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_dsp, Character.id.NPEACH, 0x4)
    dw      PeachDSP.ground_initial_
    OS.patch_end()
    Character.table_patch_start(air_nsp, Character.id.NPEACH, 0x4)
    dw      PeachNSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_nsp, Character.id.NPEACH, 0x4)
    dw      PeachNSP.ground_initial_
    OS.patch_end()

    // Use Mario's initial/grounded script.
    Character.table_patch_start(initial_script, Character.id.NPEACH, 0x4)
    dw 0x800D7DCC
    OS.patch_end()
    Character.table_patch_start(grounded_script, Character.id.NPEACH, 0x4)
    dw Peach.grounded_script_
    OS.patch_end()

    // Set entry action
    Character.table_patch_start(entry_action, Character.id.NPEACH, 0x8)
    dw Peach.Action.EntryR, Peach.Action.EntryL
    OS.patch_end()

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NPEACH, 0x4)
    float32 1.225
    OS.patch_end()

    Character.table_patch_start(jab_3, Character.id.NPEACH, 0x4)
    dw      Character.jab_3.DISABLED        // disable jab 3
    OS.patch_end()

    // Set action strings
    Character.table_patch_start(action_string, Character.id.NPEACH, 0x4)
    dw  Peach.Action.action_string_table
    OS.patch_end()

    // Set special Jump2 physics
    Character.table_patch_start(ness_jump, Character.id.NPEACH, 0x1)
    db      OS.TRUE;     OS.patch_end();

    // Set Charge Smash attacks entry
    ChargeSmashAttacks.set_charged_smash_attacks(Character.id.NPEACH, Peach.charge_smash_frames)

    // Handles common things for Polygons
    Character.polygon_setup(NPEACH, PEACH)

}
