// NMarth.asm

// This file contains file inclusions, action edits, and assembly for Polygon Marth.

scope NMarth {
    // @ Description
    // NMarth's extra actions
    scope Action {
        constant Entry_R(0xDC)
        constant Entry_L(0xDD)
        constant USPG(0xDE)
        constant USPA(0xDF)
        constant NSPG_1(0xE0)
        constant NSPG_2_High(0xE1)
        constant NSPG_2_Mid(0xE2)
        constant NSPG_2_Low(0xE3)
        constant NSPG_3_High(0xE4)
        constant NSPG_3_Mid(0xE5)
        constant NSPG_3_Low(0xE6)
        constant NSPA_1(0xE7)
        constant NSPA_2_High(0xE8)
        constant NSPA_2_Mid(0xE9)
        constant NSPA_2_Low(0xEA)
        constant NSPA_3_High(0xEB)
        constant NSPA_3_Mid(0xEC)
        constant NSPA_3_Low(0xED)
        //constant ?(0xEE)
        constant DSPG(0xEF)
        constant DSPG_Attack(0xF0)
        constant DSPGA(0xF1)
        constant DSPGA_Attack(0xF2)
    }
    
    // Modify Action Parameters             // Action                       // Animation                        // Moveset Data             // Flags
    Character.edit_action_parameters(NMARTH, Action.DeadU,                   File.MARTH_TUMBLE,                  Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.ScreenKO,                File.MARTH_TUMBLE,                  Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Entry,                   File.MARTH_IDLE,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, 0x006,                          File.MARTH_IDLE,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Revive1,                 File.MARTH_DOWN_BOUNCE_D,           -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Revive2,                 File.MARTH_DOWN_STAND_D,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ReviveWait,              File.MARTH_IDLE,                    Marth.IDLE,                       -1)
    Character.edit_action_parameters(NMARTH, Action.Idle,                    File.MARTH_IDLE,                    Marth.IDLE,                       -1)
    Character.edit_action_parameters(NMARTH, Action.Walk1,                   File.MARTH_WALK_1,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Walk2,                   File.MARTH_WALK_2,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Walk3,                   File.MARTH_WALK_3,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, 0x00E,                          File.MARTH_WALK_END,                -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Dash,                    File.MARTH_DASH,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Run,                     File.MARTH_RUN,                     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.RunBrake,                File.MARTH_RUN_BRAKE,               -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Turn,                    File.MARTH_TURN,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.TurnRun,                 File.MARTH_TURN_RUN,                -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.JumpSquat,               File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldJumpSquat,         File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.JumpF,                   File.MARTH_JUMP_F,                  Marth.JUMP,                       -1)
    Character.edit_action_parameters(NMARTH, Action.JumpB,                   File.MARTH_JUMP_B,                  Marth.JUMP,                       -1)
    Character.edit_action_parameters(NMARTH, Action.JumpAerialF,             File.MARTH_JUMP_AERIAL_F,           Marth.JUMP_AERIAL,                -1)
    Character.edit_action_parameters(NMARTH, Action.JumpAerialB,             File.MARTH_JUMP_AERIAL_B,           Marth.JUMP_AERIAL,                -1)
    Character.edit_action_parameters(NMARTH, Action.Fall,                    File.MARTH_FALL,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.FallAerial,              File.MARTH_FALL_AERIAL,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Crouch,                  File.MARTH_CROUCH,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CrouchIdle,              File.MARTH_CROUCH_IDLE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CrouchEnd,               File.MARTH_CROUCH_END,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingLight,            File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingHeavy,            File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Pass,                    File.MARTH_PASS,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldDrop,              File.MARTH_PASS,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Teeter,                  File.MARTH_TEETER,                  Marth.TEETER,                     -1)
    Character.edit_action_parameters(NMARTH, Action.TeeterStart,             File.MARTH_TEETER_START,            Marth.TEETER_START,               -1)
    Character.edit_action_parameters(NMARTH, Action.DamageHigh1,             File.MARTH_DAMAGE_HIGH_1,           Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageHigh2,             File.MARTH_DAMAGE_HIGH_2,           Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageHigh3,             File.MARTH_DAMAGE_HIGH_3,           Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageMid1,              File.MARTH_DAMAGE_MID_1,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageMid2,              File.MARTH_DAMAGE_MID_2,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageMid3,              File.MARTH_DAMAGE_MID_3,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageLow1,              File.MARTH_DAMAGE_LOW_1,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageLow2,              File.MARTH_DAMAGE_LOW_2,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageLow3,              File.MARTH_DAMAGE_LOW_3,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageAir1,              File.MARTH_DAMAGE_AIR_1,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageAir2,              File.MARTH_DAMAGE_AIR_2,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageAir3,              File.MARTH_DAMAGE_AIR_3,            Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageElec1,             File.MARTH_DAMAGE_ELEC,             Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageElec2,             File.MARTH_DAMAGE_ELEC,             Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageFlyHigh,           File.MARTH_DAMAGE_FLY_HIGH,         Marth.DMG_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageFlyMid,            File.MARTH_DAMAGE_FLY_MID,          Marth.DMG_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageFlyLow,            File.MARTH_DAMAGE_FLY_LOW,          Marth.DMG_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageFlyTop,            File.MARTH_DAMAGE_FLY_TOP,          Marth.DMG_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DamageFlyRoll,           File.MARTH_DAMAGE_FLY_ROLL,         Marth.DMG_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.WallBounce,              File.MARTH_TUMBLE,                  Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Tumble,                  File.MARTH_TUMBLE,                  Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.FallSpecial,             File.MARTH_FALL_SPECIAL,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingSpecial,          File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Tornado,                 File.MARTH_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.EnterPipe,               File.MARTH_ENTER_PIPE,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ExitPipe,                File.MARTH_EXIT_PIPE,               -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ExitPipeWalk,            File.MARTH_EXIT_PIPE_WALK,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CeilingBonk,             File.MARTH_CEILING_BONK,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.DownBounceD,             File.MARTH_DOWN_BOUNCE_D,           Marth.DOWN_BOUNCE,                -1)
    Character.edit_action_parameters(NMARTH, Action.DownBounceU,             File.MARTH_DOWN_BOUNCE_U,           Marth.DOWN_BOUNCE,                -1)
    Character.edit_action_parameters(NMARTH, Action.DownStandD,              File.MARTH_DOWN_STAND_D,            Marth.DOWN_STAND,                 -1)
    Character.edit_action_parameters(NMARTH, Action.DownStandU,              File.MARTH_DOWN_STAND_U,            Marth.DOWN_STAND,                 -1)
    Character.edit_action_parameters(NMARTH, Action.TechF,                   File.MARTH_TECH_F,                  Marth.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NMARTH, Action.TechB,                   File.MARTH_TECH_B,                  Marth.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NMARTH, Action.DownForwardD,            File.MARTH_DOWN_FORWARD_D,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.DownForwardU,            File.MARTH_DOWN_FORWARD_U,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.DownBackD,               File.MARTH_DOWN_BACK_D,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.DownBackU,               File.MARTH_DOWN_BACK_U,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.DownAttackD,             File.MARTH_DOWN_ATTACK_D,           Marth.DOWN_ATTACK_D,              -1)
    Character.edit_action_parameters(NMARTH, Action.DownAttackU,             File.MARTH_DOWN_ATTACK_U,           Marth.DOWN_ATTACK_U,              -1)
    Character.edit_action_parameters(NMARTH, Action.Tech,                    File.MARTH_TECH,                    Marth.TECH,                       -1)
    Character.edit_action_parameters(NMARTH, 0x053,                          File.MARTH_UNKNOWN_053,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffCatch,              File.MARTH_CLIFF_CATCH,             Marth.EDGE_GRAB,                  -1)
    Character.edit_action_parameters(NMARTH, Action.CliffWait,               File.MARTH_CLIFF_WAIT,              Marth.EDGE_IDLE,                  -1)
    Character.edit_action_parameters(NMARTH, Action.CliffQuick,              File.MARTH_CLIFF_QUICK,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffClimbQuick1,        File.MARTH_CLIFF_CLIMB_QUICK_1,     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffClimbQuick2,        File.MARTH_CLIFF_CLIMB_QUICK_2,     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffSlow,               File.MARTH_CLIFF_SLOW,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffClimbSlow1,         File.MARTH_CLIFF_CLIMB_SLOW_1,      -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffClimbSlow2,         File.MARTH_CLIFF_CLIMB_SLOW_2,      -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffAttackQuick1,       File.MARTH_CLIFF_ATTACK_QUICK_1,    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffAttackQuick2,       File.MARTH_CLIFF_ATTACK_QUICK_2,    Marth.EDGE_ATTACK_QUICK_2,        -1)
    Character.edit_action_parameters(NMARTH, Action.CliffAttackSlow1,        File.MARTH_CLIFF_ATTACK_SLOW_1,     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffAttackSlow2,        File.MARTH_CLIFF_ATTACK_SLOW_2,     Marth.EDGE_ATTACK_SLOW_2,         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffEscapeQuick1,       File.MARTH_CLIFF_ESCAPE_QUICK_1,    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffEscapeQuick2,       File.MARTH_CLIFF_ESCAPE_QUICK_2,    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffEscapeSlow1,        File.MARTH_CLIFF_ESCAPE_SLOW_1,     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.CliffEscapeSlow2,        File.MARTH_CLIFF_ESCAPE_SLOW_2,     -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LightItemPickup,         File.MARTH_LIGHT_ITEM_PICKUP,       -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HeavyItemPickup,         File.MARTH_HEAVY_ITEM_PICKUP,       -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemDrop,                File.MARTH_ITEM_DROP,               -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowDash,           File.MARTH_ITEM_THROW_DASH,         -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowF,              File.MARTH_ITEM_THROW,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowB,              File.MARTH_ITEM_THROW,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowU,              File.MARTH_ITEM_THROW_U,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowD,              File.MARTH_ITEM_THROW_D,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowSmashF,         File.MARTH_ITEM_THROW,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowSmashB,         File.MARTH_ITEM_THROW,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowSmashU,         File.MARTH_ITEM_THROW_U,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowSmashD,         File.MARTH_ITEM_THROW_D,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirF,           File.MARTH_ITEM_THROW_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirB,           File.MARTH_ITEM_THROW_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirU,           File.MARTH_ITEM_THROW_AIR_U,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirD,           File.MARTH_ITEM_THROW_AIR_D,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirSmashF,      File.MARTH_ITEM_THROW_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirSmashB,      File.MARTH_ITEM_THROW_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirSmashU,      File.MARTH_ITEM_THROW_AIR_U,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ItemThrowAirSmashD,      File.MARTH_ITEM_THROW_AIR_D,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HeavyItemThrowF,         File.MARTH_HEAVY_ITEM_THROW,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HeavyItemThrowB,         File.MARTH_HEAVY_ITEM_THROW,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HeavyItemThrowSmashF,    File.MARTH_HEAVY_ITEM_THROW,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HeavyItemThrowSmashB,    File.MARTH_HEAVY_ITEM_THROW,        -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.BeamSwordNeutral,        File.MARTH_ITEM_NEUTRAL,            Marth.BEAMSWORD_JAB,              -1)
    Character.edit_action_parameters(NMARTH, Action.BeamSwordTilt,           File.MARTH_ITEM_TILT,               Marth.BEAMSWORD_TILT,             -1)
    Character.edit_action_parameters(NMARTH, Action.BeamSwordSmash,          File.MARTH_ITEM_SMASH,              Marth.BEAMSWORD_SMASH,            -1)
    Character.edit_action_parameters(NMARTH, Action.BeamSwordDash,           File.MARTH_ITEM_DASH_ATTACK,        Marth.BEAMSWORD_DASH,             -1)
    Character.edit_action_parameters(NMARTH, Action.BatNeutral,              File.MARTH_ITEM_NEUTRAL,            Marth.BAT_JAB,                    -1)
    Character.edit_action_parameters(NMARTH, Action.BatTilt,                 File.MARTH_ITEM_TILT,               Marth.BAT_TILT,                   -1)
    Character.edit_action_parameters(NMARTH, Action.BatSmash,                File.MARTH_ITEM_SMASH,              Marth.BAT_SMASH,                  -1)
    Character.edit_action_parameters(NMARTH, Action.BatDash,                 File.MARTH_ITEM_DASH_ATTACK,        Marth.BAT_DASH,                   -1)
    Character.edit_action_parameters(NMARTH, Action.FanNeutral,              File.MARTH_ITEM_NEUTRAL,            Marth.FAN_JAB,                    -1)
    Character.edit_action_parameters(NMARTH, Action.FanTilt,                 File.MARTH_ITEM_TILT,               Marth.FAN_TILT,                   -1)
    Character.edit_action_parameters(NMARTH, Action.FanSmash,                File.MARTH_ITEM_SMASH,              Marth.FAN_SMASH,                  -1)
    Character.edit_action_parameters(NMARTH, Action.FanDash,                 File.MARTH_ITEM_DASH_ATTACK,        Marth.FAN_DASH,                   -1)
    Character.edit_action_parameters(NMARTH, Action.StarRodNeutral,          File.MARTH_ITEM_NEUTRAL,            Marth.STARROD_JAB,                -1)
    Character.edit_action_parameters(NMARTH, Action.StarRodTilt,             File.MARTH_ITEM_TILT,               Marth.STARROD_TILT,               -1)
    Character.edit_action_parameters(NMARTH, Action.StarRodSmash,            File.MARTH_ITEM_SMASH,              Marth.STARROD_SMASH,              -1)
    Character.edit_action_parameters(NMARTH, Action.StarRodDash,             File.MARTH_ITEM_DASH_ATTACK,        Marth.STARROD_DASH,               -1)
    Character.edit_action_parameters(NMARTH, Action.RayGunShoot,             File.MARTH_ITEM_SHOOT,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.RayGunShootAir,          File.MARTH_ITEM_SHOOT_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.FireFlowerShoot,         File.MARTH_ITEM_SHOOT,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.FireFlowerShootAir,      File.MARTH_ITEM_SHOOT_AIR,          -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerIdle,              File.MARTH_HAMMER_IDLE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerWalk,              File.MARTH_HAMMER_MOVE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerTurn,              File.MARTH_HAMMER_MOVE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerJumpSquat,         File.MARTH_HAMMER_MOVE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerAir,               File.MARTH_HAMMER_MOVE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.HammerLanding,           File.MARTH_HAMMER_MOVE,             -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldOn,                File.MARTH_SHIELD_ON,               -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldOff,               File.MARTH_SHIELD_OFF,              -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.RollF,                   File.MARTH_ROLL_F,                  Marth.ROLL_F,                     -1)
    Character.edit_action_parameters(NMARTH, Action.RollB,                   File.MARTH_ROLL_B,                  Marth.ROLL_B,                     -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldBreak,             File.MARTH_DAMAGE_FLY_TOP,          Marth.SHIELD_BREAK,               -1)
    Character.edit_action_parameters(NMARTH, Action.ShieldBreakFall,         File.MARTH_TUMBLE,                  Marth.SPARKLE,                    -1)
    Character.edit_action_parameters(NMARTH, Action.StunLandD,               File.MARTH_DOWN_BOUNCE_D,           -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.StunLandU,               File.MARTH_DOWN_BOUNCE_U,           -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.StunStartD,              File.MARTH_DOWN_STAND_D,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.StunStartU,              File.MARTH_DOWN_STAND_U,            -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Stun,                    File.MARTH_STUN,                    Marth.STUN,                       -1)
    Character.edit_action_parameters(NMARTH, Action.Sleep,                   File.MARTH_STUN,                    Marth.ASLEEP,                     -1)
    Character.edit_action_parameters(NMARTH, Action.Grab,                    File.MARTH_GRAB,                    Marth.GRAB,                       -1)
    Character.edit_action_parameters(NMARTH, Action.GrabPull,                File.MARTH_GRAB_PULL,               -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ThrowF,                  File.MARTH_THROW_F,                 Marth.THROW_F,                    -1)
    Character.edit_action_parameters(NMARTH, Action.ThrowB,                  File.MARTH_THROW_B,                 Marth.THROW_B,                    -1)
    Character.edit_action_parameters(NMARTH, Action.CapturePulled,           File.MARTH_CAPTURE_PULLED,          Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.InhalePulled,            File.MARTH_TUMBLE,                  Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.InhaleSpat,              File.MARTH_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.InhaleCopied,            File.MARTH_TUMBLE,                  -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.EggLayPulled,            File.MARTH_CAPTURE_PULLED,          Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.EggLay,                  File.MARTH_IDLE,                    -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.FalconDivePulled,        File.MARTH_DAMAGE_HIGH_3,           Marth.FALCON_DIVE_PULLED,         -1)
    Character.edit_action_parameters(NMARTH, 0x0B4,                          File.MARTH_TUMBLE,                  Marth.UNKNOWN_0B4,                -1)
    Character.edit_action_parameters(NMARTH, Action.ThrownDKPulled,          File.MARTH_THROWN_DK_PULLED,        Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.ThrownMarioBros,         File.MARTH_THROWN_MARIO_BROS,       Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, 0x0B7,                          -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.ThrownDK,                File.MARTH_THROWN_DK,               Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Thrown1,                 File.MARTH_THROWN_1,                Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Thrown2,                 File.MARTH_THROWN_2,                Marth.DMG_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Thrown3,                 -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, 0x0BC,                          -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Taunt,                   File.MARTH_TAUNT,                   Marth.TAUNT,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Jab1,                    File.MARTH_JAB_1,                   Marth.JAB_1,                      -1)
    Character.edit_action_parameters(NMARTH, Action.Jab2,                    File.MARTH_JAB_2,                   Marth.JAB_2,                      -1)
    Character.edit_action_parameters(NMARTH, Action.DashAttack,              File.MARTH_DASH_ATTACK,             Marth.DASH_ATTACK,                -1)
    Character.edit_action_parameters(NMARTH, Action.FTiltHigh,               0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FTiltMidHigh,            0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FTilt,                   File.MARTH_F_TILT,                  Marth.F_TILT,                     -1)
    Character.edit_action_parameters(NMARTH, Action.FTiltMidLow,             0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FTiltLow,                0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.UTilt,                   File.MARTH_U_TILT,                  Marth.U_TILT,                     -1)
    Character.edit_action_parameters(NMARTH, Action.DTilt,                   File.MARTH_D_TILT,                  Marth.D_TILT,                     -1)
    Character.edit_action_parameters(NMARTH, Action.FSmashHigh,              0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FSmashMidHigh,           0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FSmash,                  File.MARTH_F_SMASH,                 Marth.F_SMASH,                    -1)
    Character.edit_action_parameters(NMARTH, Action.FSmashMidLow,            0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.FSmashLow,               0,                                  0x80000000,                 0)
    Character.edit_action_parameters(NMARTH, Action.USmash,                  File.MARTH_U_SMASH,                 Marth.U_SMASH,                    0)
    Character.edit_action_parameters(NMARTH, Action.DSmash,                  File.MARTH_D_SMASH,                 Marth.D_SMASH,                    -1)
    Character.edit_action_parameters(NMARTH, Action.AttackAirN,              File.MARTH_ATTACK_AIR_N,            Marth.ATTACK_AIR_N,               -1)
    Character.edit_action_parameters(NMARTH, Action.AttackAirF,              File.MARTH_ATTACK_AIR_F,            Marth.ATTACK_AIR_F,               -1)
    Character.edit_action_parameters(NMARTH, Action.AttackAirB,              File.MARTH_ATTACK_AIR_B,            Marth.ATTACK_AIR_B,               -1)
    Character.edit_action_parameters(NMARTH, Action.AttackAirU,              File.MARTH_ATTACK_AIR_U,            Marth.ATTACK_AIR_U,               -1)
    Character.edit_action_parameters(NMARTH, Action.AttackAirD,              File.MARTH_ATTACK_AIR_D,            Marth.ATTACK_AIR_D,               -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirN,             -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirF,             File.MARTH_LANDING_AIR_F,           -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirB,             File.MARTH_LANDING_AIR_B,           -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirU,             -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirD,             -1,                                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.LandingAirX,             File.MARTH_LANDING,                 -1,                         -1)
    Character.edit_action_parameters(NMARTH, Action.Entry_R,                 File.MARTH_IDLE,                    0x80000000,                      0x00000000)
    Character.edit_action_parameters(NMARTH, Action.Entry_L,                 File.MARTH_IDLE,                    0x80000000,                      0x00000000)
    Character.edit_action_parameters(NMARTH, Action.USPG,                    File.MARTH_USP_GROUND,              Marth.USP,                        0)
    Character.edit_action_parameters(NMARTH, Action.USPA,                    File.MARTH_USP_AIR,                 Marth.USP,                        0)
    Character.edit_action_parameters(NMARTH, Action.NSPG_1,                  File.MARTH_IDLE,                    0x80000000,                      0x00000000)
    Character.edit_action_parameters(NMARTH, Action.NSPG_2_High,             File.MARTH_IDLE,                    0x80000000,                      0x00000000)
    Character.edit_action_parameters(NMARTH, Action.NSPG_2_Mid,              File.MARTH_NSPG_2,                  Marth.NSP_2,                      0)
    Character.edit_action_parameters(NMARTH, Action.NSPG_2_Low,              File.MARTH_NSPG_2_LO,               Marth.NSP_2_LOW,                  0)
    Character.edit_action_parameters(NMARTH, Action.NSPG_3_High,             File.MARTH_NSPG_3_HI,               Marth.NSP_3_HIGH,                 0x40000000)
    Character.edit_action_parameters(NMARTH, Action.NSPG_3_Mid,              File.MARTH_NSPG_3,                  Marth.NSP_3,                      0x40000000)
    Character.edit_action_parameters(NMARTH, Action.NSPG_3_Low,              File.MARTH_NSPG_3_LO,               Marth.NSP_3_LOW,                  0x40000000)
    Character.edit_action_parameters(NMARTH, Action.NSPA_1,                  File.MARTH_NSPA_1,                  Marth.NSP_1,                      0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_2_High,             File.MARTH_NSPA_2_HI,               Marth.NSP_2_HIGH,                 0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_2_Mid,              File.MARTH_NSPA_2,                  Marth.NSP_2,                      0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_2_Low,              File.MARTH_NSPA_2_LO,               Marth.NSP_2_LOW,                  0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_3_High,             File.MARTH_NSPA_3_HI,               Marth.NSP_3_HIGH,                 0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_3_Mid,              File.MARTH_NSPA_3,                  Marth.NSP_3,                      0)
    Character.edit_action_parameters(NMARTH, Action.NSPA_3_Low,              File.MARTH_NSPA_3_LO,               Marth.NSP_3_LOW,                  0)
    Character.edit_action_parameters(NMARTH, 0x0EE,                          0,                                  0x80000000,                 0)

    // Modify Actions            // Action              // Staling ID   // Main ASM                 // Interrupt/Other ASM          // Movement/Physics ASM         // Collision ASM
    Character.edit_action(NMARTH, Action.Entry_R,          -1,           0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)
    Character.edit_action(NMARTH, Action.Entry_L,          -1,           0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)
    Character.edit_action(NMARTH, Action.NSPG_1,           -1,           0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)
    Character.edit_action(NMARTH, Action.NSPG_2_High,      -1,           0x8013D994,                 0x00000000,                    0x00000000,                     0x00000000)

    // Modify Menu Action Parameters             // Action      // Animation                // Moveset Data             // Flags
    // TODO: add game over and continue
    Character.edit_menu_action_parameters(NMARTH, 0x0,           File.MARTH_MENU_IDLE,       Marth.IDLE,                 -1)
    Character.edit_menu_action_parameters(NMARTH, 0x1,           File.MARTH_VICTORY_1,       Marth.VICTORY_1,            -1)
    Character.edit_menu_action_parameters(NMARTH, 0x2,           File.MARTH_VICTORY_2,       Marth.VICTORY_2,            -1)
    Character.edit_menu_action_parameters(NMARTH, 0x3,           File.MARTH_VICTORY_3,       Marth.VICTORY_3,            -1)
    Character.edit_menu_action_parameters(NMARTH, 0x4,           File.MARTH_VICTORY_1,       Marth.SELECT,               -1)
    Character.edit_menu_action_parameters(NMARTH, 0x5,           File.MARTH_CLAP,            Marth.CLAP,                 -1)
    Character.edit_menu_action_parameters(NMARTH, 0x9,           File.MARTH_GAME_OVER,       -1,                         -1)
    Character.edit_menu_action_parameters(NMARTH, 0xA,           File.MARTH_GAME_CONTINUE,   -1,                         -1)
    Character.edit_menu_action_parameters(NMARTH, 0xD,           File.MARTH_POSE_1P,         0x80000000,                 -1)
    Character.edit_menu_action_parameters(NMARTH, 0xE,           File.MARTH_POSE_1P_CPU,     0x80000000,                 -1)

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NMARTH, 0x4)
    float32 0.93
    OS.patch_end()
    
    // Set Magnifying Glass Scale Override
    Character.table_patch_start(magnifying_glass_zoom, Character.id.NMARTH, 0x2)
    dh  0x0068
    OS.patch_end()
    
     // Set action strings
     Character.table_patch_start(action_string, Character.id.NMARTH, 0x4)
     dw  Marth.Action.action_string_table
     OS.patch_end()

    // Handles common things for Polygons
    Character.polygon_setup(NMARTH, MARTH)
}
